### ISSUE TITLE
Custom controls disappearing on Coursera.org videos

### ISSUE THREAD

**Issue by shiftplusplus** [igrigorik/videospeed#100]
Starting about 2 weeks ago, the (custom) control bar on Coursera.org videos disappeared, leaving only a floating position indicator. I thought this was a purposeful change, but recently doing a disable extension test confirmed this behaviour (problem) only appears with Video Speed Controller enabled.
It also turns closed-captioning is on by default when the video loads.

Default controls (right-click and select Show Controls) still works.

**Comment by LeMurphant** [comment]
I have the same problem. I also tried a [similar](https://github.com/benedictchen/google-chrome-html5video-controls) extension with the same result.

The mid-video quizzes also no longer appear, the video simply pauses.

**Comment by igrigorik** [comment]
Merging into https://github.com/igrigorik/videospeed/issues/103
