### ISSUE TITLE
Issues with a number of different sites

### ISSUE THREAD

**Issue by nickbarry** [igrigorik/videospeed#101]
**Udemy: Custom playback speed is reset to 1x speed after pausing Udemy videos**
On a bunch of Udemy videos I was watching recently, I would set a custom speed using the add-on. If I paused the video, then resumed it, the playback speed would go back to 1x speed.

**Codeschool: Interferes with video player controls**
On Codeschool, the extension interfered with the way the video player works. It seemed to hide/disable the video player buttons for volume, fullscreen, and a few others.

**Egghead.io: custom speed is overridden by speed setting on the Egghead video**
Like Udemy and Codeschool, the Egghead video allows setting its own speed. I prefer the extension because I like playing at 2.5x speed, and all of those video players only go up to 2x speed. On Egghead, I can't use the extension to set my custom speed, because the Egghead player's official speed overrides whatever speed I try to set with the extension.

**Comment by igrigorik** [comment]
Udemy: unfortunately that's their site logic kicking in and overriding our initial defaults. There is nothing we can do here.

Egghead.io: similar to above, except they also monitor same rateChange events and override them with own min and max. Nothing we can do here, unfortunately.

Codeschool: do you have an example? I can't reproduce this.
![image](https://cloud.githubusercontent.com/assets/10652/15093920/01ffe1c2-144a-11e6-9bbe-8004e338f178.png)

**Comment by andrewvarga** [comment]
The coursera videos are pretty much unusable with this extension.. (otherwise I like it a lot)

**Comment by igrigorik** [comment]
@andrewvarga can you elaborate on "unusable"?    

![image](https://cloud.githubusercontent.com/assets/10652/15330263/f87ab0ea-1c10-11e6-8e5d-e1db4e70abe2.png)

Works great here (note: I am running latest unreleased version).

**Comment by andrewvarga** [comment]
Sure: for me the UI controls (seekbar, buttons, etc) simply don't show with this extension enabled, also the videos pauses sometimes for a quick quiz (which opens as a div overlay on top of the video), and that quiz doesn't show up either. When I disable the extension the controls appear.
However the controls look a bit different than on your screenshot, this is the course I'm currently taking:
https://www.coursera.org/learn/machine-learning/lecture/rkTp3/cost-function

**Comment by igrigorik** [comment]
Andrew, can you please try with the latest extension? Check out the repo and install it as an "unpacked extension". Do you see the same problems?

**Comment by andrewvarga** [comment]
That solved it, thank you!

**Comment by igrigorik** [comment]
Cool, glad to hear. If all goes well, I'll release the new version this weekend.. Make sure you switch back to the stable build later, so you get updates moving forward.

**Comment by igrigorik** [comment]
Just released 0.3.0.

**Comment by andrewvarga** [comment]
Works nice, appreciated!
