### ISSUE TITLE
Custom opacity of overlay?

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#102]
I use a custom version of the addon where I changed the opacity of the overlay from I think 0.3 to 0.7 and it makes it alot easier to see and read the speed indicator whenever it is showing. 
There are times when a video has something going on in the top left that makes reading the speed quite difficult. When I changed the opacity, it made the background darker and the text brighter so it's alot easier to read no matter what is going on in the video.

So being able to set a custom opacity in the addon would be great.

Setting it manually in the addon files and then loading into Chrome isn't a big deal but having to deal with Chrome screaming at you that a custom addon is dangerous every time I restart Chrome is quite annoying.

**Comment by igrigorik** [comment]
Added new shortcut to hide/show the controller (https://github.com/igrigorik/videospeed/commit/3cadcb546396cb390b806908876ef87e0252abf4). Instead of changing opacity you can just toggle the controller visibility on/off as needed.

**Comment by Eisys** [comment]
Thank you.

However this feature is no use to me. I like that the controller only shows up when interacting with the player or changing the speed. Pressing a button to show/hide it is just extra work.

For now I am editing the 'shadow.css' file and changing 'opacity' from 0.3 to 0.7 to make it more easier to read.

The rest of the update is great. I love the blacklist feature.

And perhaps a small bug I'm noticing; The controller shows up a bit late when changing speed. In the last version it shows up instantly but now there is a half a second delay or so between me pressing my speed-up button and the indicator showing up. EDIT: Actually figured this one out. It's this part:
.ytp-autohide .vsc-controller {
  visibility: hidden;
  transition: opacity .25s cubic-bezier(0.4,0,0.2,1);
  opacity: 0;

Changing the .25 to .0 makes it come up instantly again. Curious why that delay is there in the first place.

**Comment by igrigorik** [comment]
> And perhaps a small bug I'm noticing; The controller shows up a bit late when changing speed. In the last version it shows up instantly but now there is a half a second delay or so between me pressing my speed-up button and the indicator showing up.

That behavior has been there for a while (https://github.com/igrigorik/videospeed/commit/d5e35d9d904b071bf5bd933ff33f5d31417a1ca9), we haven't changed it recently.

FWIW, I don't update the CSS files that much so it shouldn't be hard for you to keep your customizations while rebasing against latest code. Perhaps if more folks ask for such customizations in the future, we can revisit it then, but for now we'll stick with current defaults.
