### ISSUE TITLE
React-powered sites don't work with controller

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/videospeed#103]
A few examples: 
- https://www.coursera.org/learn/android-app
- videos on facebook.com

**Comment by igrigorik** [comment]
@shiftplusplus @LeMurphant in theory, https://github.com/igrigorik/videospeed/commit/3a3ac88e1045a9ad14f585dc4a24813db1cc0ecb should fix the problem on Coursera and number of other sites. Please give it a try! You'll have to check out the repo and install it as an "unpacked extension".

**Comment by LeMurphant** [comment]
The menu bar does appear both in regular viewing and in fullscreen. However, when not in fullscreen, the video icon appears twice, one at the upper left of the video as usual and once on the left out of the video frame:
![videostream_double_indicators](https://cloud.githubusercontent.com/assets/16197732/15121296/ed6bd2da-15e7-11e6-9968-b0bf55107856.png)

The icons may be removed individually with the "X", but re-appear on refresh.

It's just a minor inconvenience though. The pauses in the videos for quizzes are now functional again.

**Comment by igrigorik** [comment]
Resolved in trunk and rolling out with 0.3.0.
