### ISSUE TITLE
Have controls remain on screen

### ISSUE THREAD

**Issue by indy14** [igrigorik/videospeed#104]
First of all, awesome extension!

Would it be possible to create the option to have the controls remain on-screen and not disappear after a certain time?

It's my only minor gripe with the app currently.

Cheers.

**Comment by igrigorik** [comment]
@indy14 I assume this is for YouTube videos? If you hover over the video, the controls should reappear.

**Comment by indy14** [comment]
Yep YouTube videos. 

Yes the controls do reappear, but it would be awesome if there was an option to have the controls remain on screen and **never** disappear.

**Comment by igrigorik** [comment]
Added new shortcut to allow manual hide/show control. If you want the controller to stay permanently visible you'll have to first hide and then unhide it -- the hide action kicks in manual override and disables YouTubes autohide functionality.
