### ISSUE TITLE
How to block this extension on https://web.telegram.org/ ?

### ISSUE THREAD

**Issue by muktatma** [igrigorik/videospeed#1041]

**Comment by igrigorik** [comment]
Open options page and add it to blacklist.

**Comment by muktatma** [comment]
Thanks for answer! 
I'll tried to do it, but i had problem with formatting correct black list rule. Could you help me with correct syntacsis?

**Comment by igrigorik** [comment]
just adding a line with `telegram.com` ought to do the trick
