### ISSUE TITLE
Speed limited to x16

### ISSUE THREAD

**Issue by Maritoguionyo** [igrigorik/videospeed#1048]
I recently discovered that the extension no longer allows me to set the video speed beyond x16 on YouTube. Previously, I was able to go beyond the limit of 1000000000, which was a highly valued feature for me while watching videos.

I frequently utilized higher speed settings, such as 500, to quickly skim through lengthy videos and I was wondering if this limit was added to the extension

**Comment by igrigorik** [comment]
16x limit is enforced by the browser — it won't go any faster.
