### ISSUE TITLE
Spacebar Shortcut as "Pause" Key doesn't work anymore

### ISSUE THREAD

**Issue by arbaran** [igrigorik/videospeed#1068]
I've set the shortcut to pausing to the space key and saved my settings; picture attached.
![image](https://github.com/igrigorik/videospeed/assets/32419867/af2e4334-343a-4391-963a-ef9c306ec4a4)
However, when I try opening a video player (i.e. YouTube) when I press space it will strangely pause and then immediately unpause and pause again whenever I press spacebar, making the shortcut currently useless. When I manually pause by clicking it will not let me unpause with the spacebar either; in just milliseconds it unpauses then immediately pauses again each time, as if there is a wrong button-press delay, and holding it for longer doesn't work in either case, it just continually pauses and unpauses it, causing the video audio to cut in and out. Any help and is this a known issue?

**Comment by igrigorik** [comment]
It's clashing with built-in youtube control.. which uses space to pause video :)
