### ISSUE TITLE
Modify W Key

### ISSUE THREAD

**Issue by matbishop** [igrigorik/videospeed#1069]
Is it not possible to modify the behavior of the W key? I would like to be able to use W for 1.5x speed and E for 2x speed, pressing them again to reset. 

I have tried modifying as shown below, but it does not work as expected.
![VSC](https://github.com/igrigorik/videospeed/assets/108872176/925b9c45-73f9-4773-90e2-8043a5f82604)

**Comment by markygnlg** [comment]
YES!
I set it to 'R' (ie. reset):  YOU can then add 'W' for another function (I added another pair of keybinds for 'rewind/advance' - so I can control youtube 'shorts')


![0@_DelMeNow, now](https://github.com/igrigorik/videospeed/assets/62978705/fd838599-39cc-4865-ba3a-e704cc3250c7)

**Comment by markygnlg** [comment]
... you can _ALSO_ replace your default setting for 'Decrease speed / Increase speed' (ie. 'A' key=0.1 / 'S' key=0.1) to 0.5 ....



![0@_DelMeNow Drag2 A](https://github.com/igrigorik/videospeed/assets/62978705/8b10d5b2-b240-41eb-8ab2-c133c3b6fa10)

**Comment by matbishop** [comment]
I am not sure if you understand me correctly? The reason I have two W keys set, is because the first W setting cannot be changed to anything other than "Reset speed". I want the W key to be 1.5x speed, and the E key to be 2x speed. 

With the application I use for Safari (Accelarate), this can be done, and pressing W or E again will reset the speed to 1x. There is thus no need for a dedicated reset key.

My screenshot shows me attempting to configure this behavior, but it does not work. I don't want to modify A/S, they work as desired.

**Comment by markygnlg** [comment]
I understand you...

CHANGE YOUR:
"Reset speed .. W .. 1" to
"Reset speed .. R .. 1" (or ANY other letter)

You CAN change the 'W' key to ANYTHING, but you can not change the 'value=1' to another number.

Change letter 'W' to something else = YES
Change value '1' to something else = NO

**Comment by matbishop** [comment]
Thank you for the suggestion, it works!
