### ISSUE TITLE
Playback speed not stored on Chromium

### ISSUE THREAD

**Issue by IvanGoncharov** [igrigorik/videospeed#107]
Your chrome extension is absolutely great.
I checked `Remember Playback Speed`, but speed return to 1x every time I open a new tab.
In my workflow I step by step increasing speed for all videos that I watching.
I think it should be separate option, something like `Default speed`.

**Comment by igrigorik** [comment]
The speed is initialized when the tab is first opened, or when the video is injected into the page.. So, if you adjust the speed in one tab, it won't be reflected in another (already) open tab. However, the preference _should_ persist across new tabs.

**Comment by IvanGoncharov** [comment]
> However, the preference should persist across new tabs.

Not in my setup, plus I when I reload a page it also goes to x1.0 on this page.
To be sure I updated to latest chromium version:`Version 50.0.2661.102 Ubuntu 15.10 (64-bit)`

**Comment by IvanGoncharov** [comment]
@igrigorik I switch to chrome and everything works as expected, so this issue is `chromium`-specific.

**Comment by igrigorik** [comment]
@IvanGoncharov not sure I follow, this is a Chrome only extension..? Latest stable is M51, try updating?

**Comment by IvanGoncharov** [comment]
@igrigorik Chrome is built on top of [Chromium](https://www.chromium.org/) and both of them connected to the same Chrome store. It's important because by default Linux users can install only Chromium(at least in most popular distribution).

I use Chromium for the number of years and previously never experienced any problems with plugins or browser compatibility in general.

> Latest stable is M51, try updating?

As I wrote above I use `latest chromium version:Version 50.0.2661.102` available on `Ubuntu 15.10`.

I totally understand if you decide not to support Chromium because of the significantly smaller userbase.
But it should be stated in the README.

**Comment by igrigorik** [comment]
@IvanGoncharov can you please try with the latest version from master? I fixed a few things in there, which might help.. Also, as a sanity check: you have the "remember speed" option checked in your plugin settings, correct? :)

**Comment by IvanGoncharov** [comment]
@igrigorik Yes, it fixed in the new version.
Thank you.

**Comment by igrigorik** [comment]
\o/ .. thanks for confirming!
