### ISSUE TITLE
make it faster lol

### ISSUE THREAD

**Issue by AB39-the-little-goofy-goober** [igrigorik/videospeed#1071]
ok so i've been thinking about a couple things and i think couple suggestions
DISCLAIMER: I AM AN IDIOT PLEASE INFORM ME IF ANY OF THIS IS IMPOSSIBLE

ok so first off: 60x speed. imagine the possibilities! you could be done with a summoning salt video in just a minute! you could... ok i know there's not a lot of use for this, i just like speed

second: rewinding videos! not in the way it's already done with the z key, i mean playing videos in reverse. i just think it would be funny idk i'm stupid

third: checkbox to change pitch, this would just be funny

and yeah that's about it, thank you for coming to my ned talk
this is not an actual issue at all please ignore me if i sound dumb

**Comment by AB39-the-little-goofy-goober** [comment]
ok so as it turns out i am an actual idiot
apparently google chrome doesn't support videos being played faster than 16x or reversed
but i think maybe the pitch thing would be possible

**Comment by igrigorik** [comment]
Correct, media engine maxes out at 16x.
