### ISSUE TITLE
The ability to fully hide the grey pop up when increase speed. It some sort annoying. please thanks a lot 

### ISSUE THREAD

**Issue by YingDoge** [igrigorik/videospeed#1075]

**Comment by YingDoge** [comment]
Halo any update?

**Comment by igrigorik** [comment]
Hit "v" to toggle visibility.

**Comment by YingDoge** [comment]
> Hit "v" to toggle visibility.

That when you change the speed again that it will show up again. That i want a soultion of permtaly disabel it. it never show up ever.
