### ISSUE TITLE
Presentation speed vs Music speed

### ISSUE THREAD

**Issue by Kalindi-** [igrigorik/videospeed#108]
One problem I encounter, because I keep switching between watching presentations and listening to music, is that I often need to change from one speed to another.

Possible solution:
I notice there is the reset speed keyboard shortcut, could there be an additional one, where we can save another speed.

----

btw: Love the extension, keep referring it to people!
It has made my viewing experience much better, smoother, and also creative!
Plus I feel it has saved me time.

**Comment by queuebit** [comment]
I just listen to music at 2x. ;)

**Comment by Kalindi-** [comment]
haha!
Yeah, I actually did start listening to music at different speeds to fit emotions better sometimes, but to have emotions that need 2x music, that is quite a feat! But it sure gives a laugh.

As for the steps, I like to have them small, because it allows for more and constant customisation.

**Comment by queuebit** [comment]
I acknowledge that I am weird.

**Comment by igrigorik** [comment]
@Kalindi- if we allow custom "reset to" speed, instead of defaulting to 1.0, would that do the trick for your use case?

**Comment by Kalindi-** [comment]
I don't think so, because there are two types of speeds I use.

The default 1.0
and another faster one, that could be custom.

**Comment by igrigorik** [comment]
Let's merge this with #112.
