### ISSUE TITLE
Support for chrome app "Video Player offered by Awesome-Team"

### ISSUE THREAD

**Issue by dkjain** [igrigorik/videospeed#109]
Hi,
It would be gr8 if this extension integrates with this chrome app "Video Player
offered by Awesome-Team". I tried it but does not seems to work for me.

rgds
dkj

**Comment by dkjain** [comment]
Hi,

Ok. That apps seems to support  "THE  increase/decrease speed of the playback" by way of Keys + - [ ]. However, I still prefer your app so can this extension integrate/work with that app?

**Comment by igrigorik** [comment]
@dkjain unfortunately there is no good interface for interop with other extensions, so not much I can do from this end. Thanks for the suggestion!
