### ISSUE TITLE
Firefox version on it's way soon?

### ISSUE THREAD

**Issue by skinpup** [igrigorik/videospeed#111]
Hello
I loved your app on Chrome and really miss it now I'm stranded in the strange Java using world of Firefox.

Helllllllllppppppp

Martin

**Comment by igrigorik** [comment]
No official plans. In theory, FF is working on a Chrome-compatible API, but I'm not sure how far along that is... If someone is willing to do an experiment, that'd be great :-)

**Comment by skinpup** [comment]
I was going out of my tiny mind last night getting used to FF!!!!
Happy to test.

**Comment by igrigorik** [comment]
No immediate plans as FF API is still TBD. Perhaps in the future..

**Comment by jvschiavo** [comment]
> No immediate plans as FF API is still TBD. Perhaps in the future..

What about now?
