### ISSUE TITLE
Ability to have 2 rewind/advance times

### ISSUE THREAD

**Issue by Syhnd** [igrigorik/videospeed#112]
Hi,
I like to watch videos on some sites that doesn't have native rewind/advance abilities.
The problem is that for YouTube I use a small jump (1s) because there already is left/right keys for 5s jumps and J/L keys for 10s jumps.
My question is: could you implement a 2nd rewind/advance button with a custom jump time?

I know that the coding part is quite easy, since I don't know much about coding and got it to work by adding some lines.
I guess the problem for you is to add "advanced" features for everyone when only few people need it (eg issue #108 ), I thought about it and maybe a good way to do this is to add an "advanced settings" checkbox in the options?

Best regards.

**Comment by Syhnd** [comment]
Hi again,
Sorry I'm not familiar with github, I found a way to share my changes though:
https://github.com/Syhnd/videospeed

I added a way to have a 2nd advance and rewind jump step with U and I keys.
I set default jump to 60s in the file, but in my use I usually set "little" jump to 1s and "big" jump to 10s

Best regards.

**Comment by igrigorik** [comment]
Neat! Glad to see more folks experimenting with / customizing the plugin.. :-)

My preference is to keep things simple until/unless I hear the same request half a dozen times (a good proxy for a generally useful missing feature). What you're asking for makes sense, but you're the first so far.. I'll close this for time being, but if this reappears in the future, we can definitely come back and revisit.

Cheers.
