### ISSUE TITLE
please make it work for twitch vods

### ISSUE THREAD

**Issue by gusfringicd10** [igrigorik/videospeed#1133]

**Comment by hounvs** [comment]
It's worked on Twitch VODs for me for years and I just confirmed it still does. You'll probably need to provide more info to find what's preventing it on your end.

**Comment by sakgoyal** [comment]
you can just do 
```js
document.querySelector('video').playbackRate = 2.5; // or whatever speed
```
in the console manually. tried it today

**Comment by sakgoyal** [comment]
its still a bug so I would leave the issue open

**Comment by hounvs** [comment]
I've used this extension just fine on Twitch VODs across multiple PCs, on multiple versions of Windows, in Chrome, in Edge, and in Firefox. This should remain closed if more info isn't provided to identify the issue.

For example, it could just be that the video element wasn't in focus when trying to use it. That wouldn't be a bug, just a side-effect of Twitch's player. I think how they inject ads can interfere along with their overlays (e.g. Prime Shop) that cover the entire video with an "invisible" element. The latter also prevents the F key from making it full screen.

**Comment by sakgoyal** [comment]
when viewing a VOD today, I was able to use shortcuts to change speed, but the widget was still invisible.
