### ISSUE TITLE
The ability to fully hide the grey pop up (speed indicator ) when increase speed. It some sort annoying. please thanks a lot 

### ISSUE THREAD

**Issue by YingDoge** [igrigorik/videospeed#1134]

**Comment by YingDoge** [comment]
@igrigorik ha bro pelase help me with this bro. it is an very eays feasture for you to turn of the indicator

**Comment by YingDoge** [comment]
@kevin823lin
@stephenbrady

**Comment by YingDoge** [comment]
i would personal pay anyone 10 USD on paypal who can help do add this feature

**Comment by igrigorik** [comment]
This is already possible: hit "v" shortcut to toggle hide/display.
