### ISSUE TITLE
Request for adding dedicated preferred speed button

### ISSUE THREAD

**Issue by Navninja7** [igrigorik/videospeed#1138]
It would be handy to have a preferred speed button to quickly switch to the preferred speed, alongside the existing buttons that appear on hovering over the floating element. This is particularly useful for convertible laptops, as keyboard can't be accessed in tent or slate mode, and other touch devices.

**Comment by igrigorik** [comment]
You can already do this, in options: 
![image](https://github.com/user-attachments/assets/d3bb00ca-79d4-4f97-a1e9-25c39d971d3f)
