### ISSUE TITLE
Uncaught TypeError: mutation.addedNodes.forEach is not a function

### ISSUE THREAD

**Issue by wdhorton** [igrigorik/videospeed#114]
I've started getting this error from the `inject.js` file. The trace points to line 182:
```javascript
var observer = new MutationObserver(function(mutations) {
  mutations.forEach(function(mutation) {
    mutation.addedNodes.forEach(node => {
      if (typeof node === "function")
        return;

      checkForVideo(node, node.parentNode || mutation.target);
    })
  });
});
```

**Comment by wdhorton** [comment]
It looks like mutation.addedNodes is a `NodeList` rather than an `Array`, so you can't call `forEach` on it. [https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord](https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord)

**Comment by igrigorik** [comment]
@wdhorton what's your browser version?

**Comment by wdhorton** [comment]
Chrome Version 51.0.2704.103

**Comment by filkaris** [comment]
Same with Chrome Version 49.0.2623.87 (64-bit) in Ubuntu.

The controls are not displayed on the videos, and there are lots of errors happening.
Once loaded:
inject.js:103 Uncaught TypeError: shadow.querySelectorAll(...).forEach is not a function
inject.js:182 Uncaught TypeError: mutation.addedNodes.forEach is not a function
On clicking 'd':
inject.js:244 Uncaught TypeError: Cannot read property 'classList' of null

Until a few days ago it was working fine, I believe it stopped working around Sunday.

**Comment by igrigorik** [comment]
@filkaris this should be resolved via https://github.com/igrigorik/videospeed/pull/113 -- can you try installing latest version from master and confirm that it's working for you?

Aside: 49! Update! :-)

**Comment by filkaris** [comment]
Yes, it works now!

( Also got chrome 51 :+1:  )

**Comment by lencioni** [comment]
Thanks for the quick fix @OutOfBrain! When can we expect this fix to be released @igrigorik?

**Comment by igrigorik** [comment]
Rolled out yesterday night! 0.3.2 :-)
