### ISSUE TITLE
youtube full screen gets offset

### ISSUE THREAD

**Issue by TheEpirus** [igrigorik/videospeed#115]
this happens only when this extension is enabled, when i go into full screen mode the 1-2 cm at the top of the screen goes black and the video is moved down so the 1-2 cm at the bottom of the video gets cut off. this only happens in full screen and i can see the video fine when it is not in full screen

**Comment by darkkain** [comment]
> this only happens in full screen 

Nope. 
On 1920x1080 not full screen have small gap: ![notFullScreenYouTube](http://i.imgur.com/SUo4OGG.jpg) 

And on fullscreen:  ![FullScreenYouTube](http://i.imgur.com/qkZejDH.jpg)

**Comment by igrigorik** [comment]
Resolved via https://github.com/igrigorik/videospeed/pull/116.
