### ISSUE TITLE
Availability on mobile chrome app

### ISSUE THREAD

**Issue by avi99b** [igrigorik/videospeed#118]
Hey! 
I've been reading all about watching TV sped up, and the science behind this regarding reading and watching. 
Anyways, I happen to watch most TV on my phone, but your extension (described as the go to extension everywhere I read about this) is not available for download on my android, even though I'm using Chrome. I've tried chrome beta and dev, also doesn't work. Is there a functioning mobile version in the works? Because it would be awesome to be able to use this on the go, on my phone.
Thanks, 
Av

**Comment by igrigorik** [comment]
Unfortunately Chrome mobile does not support extensions, so you can't use videospeed there. :(
