### ISSUE TITLE
Ability to disable plugin on specific web sites

### ISSUE THREAD

**Issue by NeilM0** [igrigorik/videospeed#121]
This plugin is having trouble working on imgur.com (I just get the speed display and no animated gif's anymore) and I would like to disable it only for this site.  Having a blacklist/whitelist would be nice.

**Comment by igrigorik** [comment]
Hmm, seems to work fine here: 
![image](https://cloud.githubusercontent.com/assets/10652/16397931/11638f42-3c7c-11e6-90b3-10bb33f1ae94.png)

http://imgur.com/r/gifs/LHuV3dI

Can you give me an example or where it breaks?

**Comment by NeilM0** [comment]
I hit next twice after that image and wound up with this:

http://pasteboard.co/20McSDc7.png
http://imgur.com/r/gifs/7eWahac

I am also running ABP (It's the only other chrome addon I use)

This appears to be the error that pops up when it happens:
http://pasteboard.co/20MuxiJ1.png


Full Console error log:

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://s.imgur.com/min/px.js?ch=2 Failed to load resource:
net::ERR_BLOCKED_BY_CLIENT
http://c.amazon-adsystem.com/aax2/amzn_ads.js Failed to load resource:
net::ERR_BLOCKED_BY_CLIENT
https://secure-ads.pictela.net/rm/marketplace/pubtaglib/0_4_0/pubtaglib_0_4_0.js
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://ads.rubiconproject.com/header/8526.js Failed to load resource:
net::ERR_BLOCKED_BY_CLIENT
http://as.casalemedia.com/headertag?v=9&x3=1&fn=cygnus_index_parse_res&s=17…22ext%22%3A%20%7B%22sid%22%3A%223_1%22%2C%22siteID%22%3A172792%7D%7D%5D%7D
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
react-with-addons-0.13.3._DEVELOPMENT_.js:4486 Download the React DevTools
for a better development experience: https://fb.me/react-devtools
react-with-addons-0.13.3._DEVELOPMENT_.js:21628 Warning: Each child in an
array or iterator should have a unique "key" prop. Check the render method
of Notification.EventDropdown. See https://fb.me/react-warning-keys for
more information.
react-with-addons-0.13.3._DEVELOPMENT_.js:21628 Warning: Each child in an
array or iterator should have a unique "key" prop. Check the render method
of Gallery-SourceBar. See https://fb.me/react-warning-keys for more
information.
imcon.js:72
      _
     (_)
      _ _ __ ___   __ _ _   _ _ __
     | | '_ ` _ \ / _` | | | | '__|
     | | | | | | | (_| | |_| | |
     |_|_| |_| |_|\__, |\__,_|_|
                   __/ |
                  |___/
========================================
You opened the console! Know some code,
do you? Want to work for one of the best
startups around? http://imgur.com/jobs
========================================

imcon.js:72 No hash found in placement response. a
react-with-addons-0.13.3._DEVELOPMENT_.js:20309 Uncaught Error: Invariant
Violation: ReactMount: Two valid but unequal nodes with the same
`data-reactid`: .7.0:$7eWahac.0.1.1

**Comment by Eisys** [comment]
Having a white/blacklist in the options would be really nice.

Since update 0.3.0 or so, the speed controller started showing up when using Imagus.
Example; http://i.imgur.com/c4sP6CX.png
Which is pretty annoying since it's not needed on pictures. And I want to watch gifs at a normal speed as well. Imagus has its own speed control for gifs anyway.

So being able to disable some sites/domains would be a welcomed addition. 
Or perhaps add an option to make it work strictly on HTML5 video only.

For now I am using a custom version whitelisted to youtube.

**Comment by Cooluck** [comment]
Totally agree. If possible — on several sites I need standard speed, for ehample netflix.com
So, blacklist will be very useful.

**Comment by chris-carpenter** [comment]
I have the same issue, on this site (imgur.com). You can work around it by reloading the page, but that really goes against the feel of the site.

**Comment by igrigorik** [comment]
@NeilM0 @Eisys can you try the latest build from the repo on imgur? I can't reproduce the error anymore on this end. But that's orthogonal to exposing a custom blacklist..

**Comment by NeilM0** [comment]
It looks like the issue is fixed.  I haven't been able to reproduce it.

**Comment by igrigorik** [comment]
@NeilM0 yay, thanks for confirming!

**Comment by igrigorik** [comment]
You can now define a custom blacklist in options. If you're willing give it a try by installing the extension from master. If all goes well, should roll out with next version.

**Comment by NeilM0** [comment]
Nice, it works great.
