### ISSUE TITLE
Controls always visible on screen for netflix.

### ISSUE THREAD

**Issue by j-christ** [igrigorik/videospeed#123]
I love the extension, so thanks for this.  However, the number for the controller is always on screen unless manually dismissed.  Can there be an option to not show the controller at all?  I wonder if this is the way this is supposed to work, or if it's a result of work on issue #104.

**Comment by igrigorik** [comment]
This is, indeed, the intended behavior. The only site we auto-hide on is YouTube. 

Part of the problem is that I don't have a Netflix account to test on :(

**Comment by igrigorik** [comment]
One idea: add a shortcut to hide/unhide the controller.

**Comment by igrigorik** [comment]
Added new shortcut (https://github.com/igrigorik/videospeed/commit/3cadcb546396cb390b806908876ef87e0252abf4) to allow manual hide/show control. If you're interested you can install from git master and take it out for a spin. If all goes well, this should ship in the next release.
