### ISSUE TITLE
Alt+d triggers d hotkey

### ISSUE THREAD

**Issue by baz357** [igrigorik/videospeed#125]
Hello,

great extension, thank you! I found a bug: when you press Alt+d to move to the address bar, Video Speed Controller recognizes that as pressing the d hotkey, thus increasing the video's speed. IIRC this has only been the case since somewhat recently, I don't recall getting this behavior last year.

**Comment by WhyEvenTry** [comment]
Just tested it: All modifier keys are ignored (CTRL, SHIFT too).

**Comment by baz357** [comment]
That's weird, I can reproduce it here... do you have set "d" for increasing speed, too?

**Comment by WhyEvenTry** [comment]
I agreed with you.

**Comment by baz357** [comment]
Ok, let's see what igrigorik will say.

**Comment by igrigorik** [comment]
We _should_ support shift-{key} as a workaround for sites where {key} is already assigned to another function. However, I agree, we shouldn't hijack other modifiers. 

This may have been changed/introduced in: https://github.com/igrigorik/videospeed/commit/c7d7df2c1d896fdf2f80c460715af62d6c1560cc cc/ @alexkudrow

**Comment by baz357** [comment]
@igrigorik: can you confirm that this is a bug? (Alt+d)

**Comment by igrigorik** [comment]
Yes, I don't think we should hijack alt + other modifiers.. except shift.

**Comment by baz357** [comment]
@igrigorik: excellent, then I'm looking forward to a version where this is fixed. :-)
