### ISSUE TITLE
Add remaining time at current rate

### ISSUE THREAD

**Issue by adishavit** [igrigorik/videospeed#126]
Most players show the remaining play time at normal rate even when using the extension.  
It would be helpful if the extension also showed the remaining playing time at the current rate.

**Comment by igrigorik** [comment]
Thanks for the suggestion!

Unfortunately I think this a "wontfix" as this would send us down the path of starting to rebuild the entire player UI which we definitely don't want to take on.

**Comment by adishavit** [comment]
Too bad. Thanks.

**Comment by adishavit** [comment]
I just realized what you meant. I wasn't clear.
The request is not for modifying the player, I meant to display the sped-up remaining time on the widget itself, say between the rate and the left button.  
This seems like a self-contained change to the widget, no?

**Comment by igrigorik** [comment]
@adishavit we're on the same page.. that's how I read your original comment. However, same comment as before: if we go down this path we'll end up with a full control overlay, and that's not the intent of this plugin.

**Comment by adishavit** [comment]
Ok. As you wish. Great job regardless :-)
