### ISSUE TITLE
Unable to set special keys as shortcuts

### ISSUE THREAD

**Issue by Edenhofer** [igrigorik/videospeed#127]
It is not possible to change shortcut keys to certain characters which are only accessible in combination with e.g. `Alt+Gr` or `Shift`.
(Though I think it is probably not directly related, I have a german keyboard but so far never encountered any similar troubles.)

**Comment by igrigorik** [comment]
Thanks for your feedback!

This is not a keyboard limitation. As of today we (intentionally) do not support modifier combinations, mostly because they are much trickier to implement and persist. 

As of today, no plans to change that.. but if this resurfaces in the future, we can revisit.

**Comment by Edenhofer** [comment]
That is unfortunate.
Quite a few media players set `[` and `]` as hotkeys and I simply wanted to adjust videospeed to behave similarly. MPlayer and VLC both do so however resetting the speed is done with `=` in VLC and `backspace` is used by Mplayer. Especially VLC is very popular and Mplayer is common among Linux distributions. I therefore suggest at least adding an option to alter the hotkey to very popular alternatives.

**Comment by igrigorik** [comment]
@Edenhofer thanks for the context. I don't have any philosophical objections to allowing combination keys, it's more of a pragmatic implementation complexity / constraint on my part.. If you'd be willing to work on this.. we can revisit :-)
