### ISSUE TITLE
On Coursera two speed controls are displayed

### ISSUE THREAD

**Issue by WhyEvenTry** [igrigorik/videospeed#132]
Screenshot attached. Debugging on Coursera requires a *free* login, nothing I can do about that...

![untitled](https://cloud.githubusercontent.com/assets/199179/17136460/c163a3bc-5335-11e6-9c5a-90b26f42472e.png)

**Comment by igrigorik** [comment]
Thanks for the report!

This is (already) resolved in master branch, the fix will go out with the next release.
