### ISSUE TITLE
Can't interact with controller due to overlay

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/videospeed#134]
- Vimeo: https://github.com/igrigorik/videospeed/issues/133#issuecomment-236383502
- "When I play amazon prime video in chrome I can't really use this extension because clicking on the button for speed defaults to pausing or running the video. Its as if the speed controller button doesn't even exist even though I can see it in the upper left corner."

In both cases the controller is inject before the video player but below a site controlled overlay. This is not something easily (or at all) fixed via CSS.. I think the only viable solution here might be to add custom origin rules for where to inject the controller. This strategy will work, but it might be very brittle.. Need to ponder it some more.

**Comment by n4ppy** [comment]
Hi,

Ran into a similar issue on this google ;) video https://www.youtube.com/watch?v=WtsVV5c46Ow

The videospeed and 3d movement controls are fighting each other (both on screen and the (w)asd keyboard options)

Otherwise GREAT plugin for formula 1 replays and bald eagle snatches.

Perhaps a {T}ransport option to beam the control to another quadrant? One {T} moves it top left next bottom left etc etc.

Best,

Franc

**Comment by aesterling** [comment]
I would love the ability to specify controller location in the extension's options page! (or directly in the overlay if that makes more sense.)

**Comment by igrigorik** [comment]
@aesterling in the latest version you can drag the controller: click on the speed text/box and drag it  to another position.

**Comment by aesterling** [comment]
@igrigorik That's excellent! Thanks for your work! Is there a way to set a default position or remember where the controller is dragged to for future videos?

Also, why can I drag the controller closer to some edges than others on YouTube? (i.e. controller can touch the right and bottom edges but have a buffer between the left and top edges.)

**Comment by igrigorik** [comment]
@aesterling no, there is no way to override the initial position. Re, edges: bugs in the implementation, probably.. I'll take a look :)

**Comment by lencioni** [comment]
I'm not sure if this is helpful information, but I'm running into a similar, but possibly different, problem on SlidesLive (e.g. https://slideslive.com/38898201/refactoring-css-without-losing-your-mind).

**Comment by canadiannomad** [comment]
I find it really difficult to interact with the plugin in NetFlix due to the "back" overlay... 
I really wish there was a way to move the default position of the plugin.. Either editing CSS, having a "remember position" option, or a few "relative position" options.

**Comment by igrigorik** [comment]
It appears that Vimeo may have updated their player, as the overlay problem is gone both on the site and in the embeds - i.e. nothing stops you from interacting with the controller. That said, there are a few other sites where it's still an issue:

- Amazon Prime player adds an overlay above - e.g. https://www.amazon.com/dp/B00VO8D13K/
- SlidesLive does some weird "hide YouTube branding" hack that hides the controller entirely. - e.g. https://slideslive.com/38898201/refactoring-css-without-losing-your-mind

@n4ppy the 3D controller is a simple fix: https://github.com/igrigorik/videospeed/commit/ea7b013534d04e4935e63e7c0cb7eb246ed46a37

**Comment by chimzuk** [comment]
@igrigorik Sadly I'm still experiencing the same [vimeo problem](https://github.com/igrigorik/videospeed/issues/133#issuecomment-236383502), with no difference.

**Comment by igrigorik** [comment]
@chimzuk I can't reproduce it on this end. Do you have a particular link I can test?

**Comment by chimzuk** [comment]
@igrigorik I rechecked and it works the different way. The problem appeared cause I had vimeo into the blacklist. You can reproduce it by adding vimeo.com there.
Now clicking on the video itself doesn's make it fullscreen as before, it does nothing now, but the default behavior is play pause.

**Comment by igrigorik** [comment]
Interesting.. This is what I have in my settings:
![image](https://cloud.githubusercontent.com/assets/10652/21433971/f68e55b2-c826-11e6-9a41-de3b436c7666.png)

When I visit vimeo, I don't see the controller at all (as expected). You see it / can't interact with it?

**Comment by thetoolwiz** [comment]
Lately it seems YouTube displays the title of the video along the top of the video that's clickable. It overlays the control and makes it unreachable. I can see the control, and sometimes even get it to expand via a tiny little sliver of mouseover area, but it's impossible to use when a clickable title is displayed there. The ability to move it to a different corner, or make it taller and drop the controls down lower so they're below the title area would be great.

**Comment by igrigorik** [comment]
@thetoolwiz YT case was was fixed in https://github.com/igrigorik/videospeed/issues/178

**Comment by igrigorik** [comment]
Another similar edge case from https://github.com/igrigorik/videospeed/issues/227: 

> Controls does not shown on hover @ https://www.tesla.com/shareholdermeeting

**Comment by sflesch** [comment]
I didn't want to open another ticket just yet. I can no longer get at the controls in the upper left corner with Amazon. I can't move them to access them.

**Comment by hmemcpy** [comment]
Very sorry to bump an old thread, is there any workaround for SlidesLive?
