### ISSUE TITLE
No longer functions on mediasite for lecture videos

### ISSUE THREAD

**Issue by rocka-flocka** [igrigorik/videospeed#136]
Hello,

Post chrome update this extension stopped working for me. It actually happened half-way through watching one of my lectures. I went an entire year with this working perfectly and am reeeeally hoping it'll work again soon.

This is an example (although it might not work since I have to log in)
https://mediasite.utsouthwestern.edu/Mediasite/Play/12ccfef7358a4c3b9d1e2c58e4b0c0041d?catalog=ce601172-c5ff-4115-8d4f-283936b22270

**Comment by igrigorik** [comment]
Hmm, unfortunately I can't access that.. get a login screen. 

- Can you describe the error? Is controller visible? Do shortcuts work (even if controller is not visible)
- Any chance you can inspect devtools and see if there are any errors there?

**Comment by rocka-flocka** [comment]
So last year when I used this, I was able to use the D key to speed up by increments of 10%. All keyboard shortcuts used to work. 

Now they have stopped working entirely. No controller is visible.

I do have flash disabled through chrome.

When I did the inspect, I get:
"chrome-extension://nffaoalbilbmmfgbnbgppjihopabppdk/inject.js:346 Uncaught TypeError: Cannot read property 'classList' of null"

**Comment by fholy** [comment]
I am also experiencing the same problem as rocka-flocka on a mediasite lecture.  I have also tried disabling flash and that does not fix the problem.

Thanks in advance for looking into this and let me know if you need more info. It is a password protected site though

**Comment by igrigorik** [comment]
> When I did the inspect, I get:
> "chrome-extension://nffaoalbilbmmfgbnbgppjihopabppdk/inject.js:346 Uncaught TypeError: Cannot read property 'classList' of null"

Hmm, interesting.. Do you see any other errors firing from inject.js when the page is first loaded and video is initialized? 

I have a hunch: https://github.com/igrigorik/videospeed/commit/707c0c3f16e11a867cc09f5a5478fb792d5c30ab. How comfortable are you with git? :) Any chance you could rewind to commit just prior to that one and try running the unpacked extension locally?

**Comment by fholy** [comment]
I would love to help you get this working but sadly I am not very knowledgeable in these things

**Comment by rocka-flocka** [comment]
Yes, same here. I would love to be more useful, but a lot of this is just a bit over my head.

If it helps at all, the HTML5 Video Speed controller works on mediasite. Although it doesn't have the keyboard shortcuts that your extension provides.

**Comment by igrigorik** [comment]
I have a hunch that 221d107 may fix your issue... You can try the pre-release version: clone the repo and then [install unpacked extension](https://www.google.com/search?q=install+unpacked+extension+chrome).

**Comment by rocka-flocka** [comment]
WORKS AGAIN!!!

THANK YOU FROM MY ENTIRE CLASS!

**Comment by igrigorik** [comment]
\o/ .. glad to hear!

**Comment by renaidkim** [comment]
The same kind of problem is happening again with my school's mediasite. Worked fine until yesterday. I see that your last commit was 16 hours ago and I feel like the last update might have caused this? Controller works fine on Youtube, but not on mediasite
