### ISSUE TITLE
Was working great--no longer

### ISSUE THREAD

**Issue by Tom003** [igrigorik/videospeed#137]
I have been using Video Speed Controller mainly for lessons hosted on Wistia. This evening I returned to a video I had been watching this morning using VSC, but now the controls are not visible and the shortcuts do not work, either.

I have disabled flash, restarted chrome, my computer (MacBook Pro), un+reinstalled Chrome, un+reinstalled VSC, but nothing fixes the problem.

Strangely, a variety of videos on the site I've been learning from do not show the VSC controls (I assume they did in the past, but I have no way of confirming).

They are HTML5 enabled, as shown when I inspect the html. When I click the link of the embedded video, it opens full frame and the controls return. This is my work around for the time being.

UPDATE: I turned on "Remember playback speed," and the speeds for videos that work without a problem do carry over to videos that do not show the controls (and are not affected by the hotkeys).

Any suggestions would be most appreciated. Thank you so much for an otherwise well-designed and valuable product!

Tom

**Comment by igrigorik** [comment]
Thanks for reporting this! Do you have a (public) link where I could reproduce this? 

Their demo page seems to work AOK for me: https://wistia.com/product/demos.

**Comment by igrigorik** [comment]
Tom, can you try the latest version from master? I have a hunch that 221d107 may fix your issue as well. To do so: clone the repo and then [install unpacked extension](https://www.google.com/search?q=install+unpacked+extension+chrome).

**Comment by igrigorik** [comment]
Closing, as I believe this should be resolved. Please reopen if otherwise.

**Comment by Tom003** [comment]
Hi Ilya,

Thank you so much for attending to this issue. It is fixed!

I am sorry for the delay. I couldn't send you a link because the lessons
are all private, paid content.

Thank you again for fixing it and for making such an amazing product.

Sincerely,
Tom
