### ISSUE TITLE
Two speed control on Coursera

### ISSUE THREAD

**Issue by 1c7** [igrigorik/videospeed#139]
![image](https://cloud.githubusercontent.com/assets/1804755/17957049/016a4d56-6ac1-11e6-85c4-1ea472720d1a.png)
https://www.coursera.org/learn/build-a-computer/lecture/iyL0J/unit-1-7-project-1-overview
It is not a big problem. But I would still like to let you know.

Thank you for making this great program!
really helpful. save me a lot of time!
:smile:

**Comment by igrigorik** [comment]
Are you running the latest version of the plugin? I believe this was already fixed.

**Comment by 1c7** [comment]
@igrigorik I don't know, Let me check it.  I would come back and tell you result.

**Comment by 1c7** [comment]
@igrigorik 
![image](https://cloud.githubusercontent.com/assets/1804755/17957643/e69f29ec-6ac5-11e6-9604-1d79ece5d903.png)

I think it is the latest version? I have no idea. I don't see any button that say "update"
![image](https://cloud.githubusercontent.com/assets/1804755/17957651/f4566780-6ac5-11e6-8d62-7c7f20672f58.png)

**Comment by igrigorik** [comment]
Hah, interesting.. You're right, it came back. I think we "fixed it" in https://github.com/igrigorik/videospeed/commit/707c0c3f16e11a867cc09f5a5478fb792d5c30ab but https://github.com/igrigorik/videospeed/commit/221d1072469758771b9199ec25613285c3b3b5db then restored this behavior. Will need to dig in to see what's going on there...

**Comment by marshallaf** [comment]
It's something weird with `Element.remove()`, but I couldn't figure out what.

[Here](https://github.com/igrigorik/videospeed/blob/9f4bfaa510ad0b1fa0812e9030aa74be4794016f/inject.js#L226-L231) in `checkForVideo` it stores the controller div to `ctrl` and then tries to remove it a couple lines later with `ctrl.remove()`. But for whatever reason it doesn't work. I checked a bunch of things:

- `ctrl` exists
- the if statement gets executed
- `typeof ctrl.remove` returns function

I also tried removing it with `ctrl.parentNode.removeChild(ctrl)` and that didn't work either.

However, in https://github.com/igrigorik/videospeed/commit/707c0c3f16e11a867cc09f5a5478fb792d5c30ab it doesn't store it, instead it's 
``document.querySelector(`div[data-vscid="${id}"]`).remove()``.
And that works! 

So I'm at a complete loss. I guess you could switch back to the old way, but that removes the null check.

**Comment by marshallaf** [comment]
Actually nevermind. Over the course of the page load, the video element is added and removed. For some reason, these aren't the same number of times (additions - removals = 2), so we end up with two controllers that persist.

As to my last comment - turns out `ctrl.remove()` was working, but the controller that it removed was right on top of another one, so it looked like nothing was happening.

**Comment by igrigorik** [comment]
Resolved via https://github.com/igrigorik/videospeed/pull/142.

**Comment by 1c7** [comment]
thank you!

**Comment by brandonjp** [comment]
FYI - I'm seeing this issue on hoopladigital.com.  Using the latest version (0.5.4) installed yesterday from the Chrome Extensions website.
![Screenshot 2019-03-25 10 13 40](https://user-images.githubusercontent.com/199599/54932417-c837f380-4ee8-11e9-80fe-a0c1f0c388f1.png)
