### ISSUE TITLE
imgur.com locking up.

### ISSUE THREAD

**Issue by NeilM0** [igrigorik/videospeed#145]
I've recently had a lockup situation in Chrome when browsing imgur.com.  The tab stops responding, I can't close it and have to wait for the Kill/Wait dialog to pop up.

When I add imgur.com to the blacklist I don't see that tab locking up anymore.  Incogneto mode doesn't have the issue either.

**Comment by igrigorik** [comment]
Which version of the plugin are you running? We have imgur on our default blacklist [1] in latest release, which makes me suspect that you might be stuck on an earlier version.

[1] https://github.com/igrigorik/videospeed/blob/master/inject.js#L19

**Comment by NeilM0** [comment]
I'm using Video Speed Controller 0.4.2.  Is that the latest?

**Comment by igrigorik** [comment]
Indeed, it is. I guess you may have migrated your list from an earlier version that didn't have imgur.

**Comment by igrigorik** [comment]
https://github.com/igrigorik/videospeed/commit/db314ef5205a91ae16efd6af11f62ece67c4bb39 should help, closing. Please reopen if this is still a problem.
