### ISSUE TITLE
Permissions question...

### ISSUE THREAD

**Issue by subssubs** [igrigorik/videospeed#146]
"Read and change all the data on the websites you visit" is a bit scary- do you really need all those permissions?
I want to install it, but that seems a bit broad, eh?
thx!

**Comment by igrigorik** [comment]
We need to inject a content script into the page, which (practically speaking) has those implications.. it can read and modify content of those pages; we use that to inject the video controller. Unfortunately there is no other way. That said, please feel free to audit the code: https://github.com/igrigorik/videospeed/blob/master/inject.js
