### ISSUE TITLE
Volume control along with speed.  #enhancement

### ISSUE THREAD

**Issue by sldx** [igrigorik/videospeed#148]
Quite addicted to this extension, use it on most non-music videos I watch, especially tutorials.

There is one issue that is a bit annoying. I noticed the sound volume tends to drop as the speed increases, and I have to adjust the volume as I change speed. 
At lower increments (1.2-1.4) is not really noticeble, but towards 2.0 you have to adjust volume too. 

It would be nice to have the script do that automatically, maybe with a configurable multiplier or curve.

**Comment by igrigorik** [comment]
Hmm, I don't believe playback speed should affect anything to do with sound volume.. If it does, that may be an implementation bug in the browser. That said, I've never observed this effect myself.

**Comment by sldx** [comment]
I don't think the playing-speed affects the volume **directly**, as in it changes the volume. I believe it's more a side-effect of higher playing speeds (2x, 3x), fewer samples to pick from, something along those lines. 

I tried it on multiple computers, and the effect is quite visible from 2x onwards. You could try one example: start a video at a louder volume than you'd normally listen to. Than go to 3x or 4x. After a short adjusting time, jump to 1x speed. I think you'll notice the difference.

**Comment by igrigorik** [comment]
*shrug*.. :-)

I've never noticed this myself; perhaps it's also a function of your speakers and the type of videos you watch. Given that this is the first time I've heard this request, I'm going to mark this as "wontfix".. at least of for now, until/unless we hear more voices chiming in with same feedback.

That said, appreciate the feedback, please keep it coming!
