### ISSUE TITLE
Netflix intermittently locks up tab in chrome

### ISSUE THREAD

**Issue by RedKrieg** [igrigorik/videospeed#149]
Sometimes when loading netflix in chrome, I get a blank grey screen and the tab becomes sluggish.  If I add netflix.com to the exclusions for this plugin, it loads and I can start playing.  I can then remove it from exclusions and hit refresh to use the plugin as normal.  Is this a known issue?  Is there anything I can do other than manually adding and removing the blacklist?  This just started last week, I used the plugin for months with no issues.

Ubuntu 16.04.1 LTS
Google Chrome Version 53.0.2785.143 (64-bit)

**Comment by igrigorik** [comment]
Similar reports from the Chrome store feedback channel...

> The extension was causing Netflix to hang recently (when trying to play anything or when trying to load "My List"). Disabling the extension solves the issue ...

> Causes netflix to freeze up when searching for show and it also freezes when open a show

> Before September 24 2016, it worked on netflix. Now if I start netflix it wont start the show. So I have to disable the extension then start netflix and the episode and then I have to enable the extension and refresh the page for it to work.

**Comment by queuebit** [comment]
I was experiencing this too, but hadn't traced it down to the extension.

In the last two days things seem to be working again. /shrug

**Comment by RedKrieg** [comment]
This seems to be resolved for me right now.  No longer having to do anything special to get netflix working (same chrome version).

**Comment by igrigorik** [comment]
Hmm.. perhaps Netflix was testing/had a bug in their player. I'll keep this open for a bit longer to see if we hear other reports.

**Comment by mattopps** [comment]
I've been having the same issue with Netflix for a bit over a week now. clicking on a video or attempting to search freezes the page.

**Comment by babyxdeja** [comment]
seeing same issue, I removed the extension and Netflix was fine.. added extension and it freezes when trying to search and play videos

**Comment by igrigorik** [comment]
Should be resolved via https://github.com/igrigorik/videospeed/commit/db314ef5205a91ae16efd6af11f62ece67c4bb39.

I'll ship this in next release. First though, need to fix another draggable bug.. grr! :)
