### ISSUE TITLE
Can you upgrade the controller so that I can play HTML5 at 5 percent increases per increment

### ISSUE THREAD

**Issue by LukeDaniel** [igrigorik/videospeed#150]
Some of the videos on Youtube play slow.
For some a ten percent increase or 1.10 on your software works.
On Led Zeppelin ll (two), a 5 percent increase is required to get to 1.15.
Can you modify your software so that we can do increments of 5 percent
so that we can do 0.90. 0.95, 1.0, 1.05, 1.10, 1.15, 1.20, 1.25, etc.

Thanks in advance for reading this and maybe improving your already great
Chrome Browser Extension.

**Comment by igrigorik** [comment]
You can configure this already in plugin settings:

![image](https://cloud.githubusercontent.com/assets/10652/19222438/4feb0f96-8e0d-11e6-8816-c8ed4fddf922.png)


Change "change step" to a lower value.
