### ISSUE TITLE
Live streams keep pausing

### ISSUE THREAD

**Issue by domelliott** [igrigorik/videospeed#152]
When you have speed turned up for a live stream (specifically I experienced this on YouTube), the extension speeds up the stream in small batches, causing the stream to pause briefly every few seconds which the content catches up. It's an awkward way to listen to live streams (with constant pauses). It would be great if the extension automatically stayed on 1.00x if it could detect it's on a live stream.

**Comment by igrigorik** [comment]
> It would be great if the extension automatically stayed on 1.00x if it could detect it's on a live stream.

The downside to that is... I'm aware of a number of people (including myself) who intentionally pause live-streams and then speed through them in chunks at accelerated pace. Which is to say, an auto-detect for live streams that defaults to 1.0x is not an unconditionally better experience.

**Comment by domelliott** [comment]
Fair enough! I don't know how many people prefer either way. One idea would
be to have an opt-in setting saying:
[  ] I like to watch livestreams live

**Comment by igrigorik** [comment]
> [ ] I like to watch livestreams live

Well, you can always reset the speed (shortcut: r) to go back to 1.0 for that particular stream. 

Closing as wontfix for now / unless we hear similar requests in the future. Thanks for your feedback!
