### ISSUE TITLE
The extension is causing Netflix to go into a memory leak

### ISSUE THREAD

**Issue by Shalaiyn** [igrigorik/videospeed#153]
Opening a video on Netflix with the extension enabled causes Netflix to start a memory leak. Simply disabling it causes Netflix to work again, but I've become quite used to watching at 1.5x so it's a not great solution.

Searching on Netflix causes the same problem as soon as you type anything into the search bar.

**Comment by lucasengel** [comment]
Many other sites behave the same way. I was able to replicate the issue on TeamWork and Mashable too.

**Comment by igrigorik** [comment]
Thanks for the report guys.. hoping to get to it / investigate it this week. That is, unless someone else beats me to it.. :)

**Comment by babyxdeja** [comment]
seeing same thing on Netflix

**Comment by igrigorik** [comment]
Dupe of https://github.com/igrigorik/videospeed/issues/149, please track that.
