### ISSUE TITLE
Videos and GIFs won't play at all

### ISSUE THREAD

**Issue by y2k-shubham** [igrigorik/videospeed#154]
Since last 2 days, all videos and GIFs (on all websites) have completely stopped playing with the extension enabled, and would play only after disabling the extension. I'm using Chrome Version 54.0.2840.99 m (64-bit) on Windows 8.1

**Comment by igrigorik** [comment]
Yikes. Can you elaborate on "stopped playing"? As in, the video doesn't load at all? Any other symptoms or console errors?

**Comment by y2k-shubham** [comment]
Yeah the video doesn't load at all. At first I thought my ethernet was slow or proxy server was blocking the content, but when videos on every site refused to play, I tried disabling the extension and that worked.

**Comment by igrigorik** [comment]
I can't seem to reproduce this. Running 54.0.2840.98 (64-bit) on OSX and everything is working a-ok. Can you try disabling other extensions and see if the problem persists? I'm wondering if there is some cross-extension bug that's wrecking havoc..

**Comment by igrigorik** [comment]
Please reopen if this is still a problem after the new release goes out today.
