### ISSUE TITLE
re:#136 No longer functions on mediasite for lecture videos 

### ISSUE THREAD

**Issue by renaidkim** [igrigorik/videospeed#155]
The same problem described in #136 is happening again. Worked fine until yesterday. Controller works fine on Youtube but not on mediasite. Not sure what's happening and I am not familiar enough with git to downgrade the extension. Other HTML5 video speed controller extensions are working fine on mediasite, so I don't think mediasite suddenly went to using flash instead of HTML5. Please fix this problem!

**Comment by renaidkim** [comment]
Figured out how to downgrade the extension.
0.4.3 or 0.4.2 won't work on mediasite although it works on YouTube.
0.2.6 works on both sites.

**Comment by igrigorik** [comment]
@renaidkim is there a public URL that I can test this behavior on? Unfortunately, without one, I'm unlikely to make any progress..

**Comment by renaidkim** [comment]
After some google search, I found this url. https://mediasite.video.ufl.edu/Mediasite/Play/30eabfa8d46f45c1a94d1fb5cdb446861d?catalog=58a2c26a-048c-42de-8950-c7f68c1e7540

Looks to me like the same platform that my school uses.

**Comment by theresathuong** [comment]
Hi Renaidkim, can you show me how I can download the version that works?? Thanks!

**Comment by johnoharper** [comment]
Thanks manually adding the 0.2.6 extension worked for me also.

**Comment by igrigorik** [comment]
@renaidkim thanks for the URL, that helped a lot! Pushed a fix, any chance you'd be willing to try it on other mediasite videos and confirm that it's working? If that looks good, I can push 0.4.4.

**Comment by johnoharper** [comment]
@igrigorik the latest commit is successfully working with PluralSight now.

**Comment by renaidkim** [comment]
@igrigorik The fix works for me also. Thank you very much.

**Comment by igrigorik** [comment]
0.4.4 is rolling out now.
