### ISSUE TITLE
Add option to be 'hidden' by default

### ISSUE THREAD

**Issue by firstodd** [igrigorik/videospeed#156]
Great and useful addition to Chrome - but the little "1.00" is always on top of every video online now aside from blacklisting that site? The extra step of having to hit "v" to hide your overlay, every time a user watches a video, is unacceptable. Please add an option to permanently hide the overlay, or better yet, it only shows temporarily when you press a button to change speed, like any other UI that autohides.

**Comment by pateras** [comment]
Came here to ask for this. Please add this feature.

Thanks for this amazing extension! I use it every day.

**Comment by fent** [comment]
One idea on how to do this, is to hide it unless the user is actively moving their mouse over the video. Kinda like how on some video players, the controls only show up when the mouse moves.

**Comment by igrigorik** [comment]
Landed new option to have the controller be hidden by default. You can try it out by installing the unpacked extension.. I'll push this out in the next release.

**Comment by zigzag312** [comment]
Thank you!
