### ISSUE TITLE
Chrome Tab freezes when there is no audio

### ISSUE THREAD

**Issue by salesvictor** [igrigorik/videospeed#157]
When running a video with a speed greater than 1.0x (doesn't seem to freeze for speeds below that), all the tab freezes when there is no audio in the video and unfreezes back to a time in the video with audio after some time. While the current tab is frozen it is possible to acess and manage other tabs.

I have seen it happenning also in Coursera, besides Youtube. But I think it happens regardless of the site.

**Comment by igrigorik** [comment]
Do you have a link to a demo video? I'm skeptical that this is due to the extension.. but would like to verify. Does the problem go away when you disable the extension?
