### ISSUE TITLE
video controls issue on periscope.tv

### ISSUE THREAD

**Issue by evodoc** [igrigorik/videospeed#159]
While it doesn't really matter for the live stream, it also happens when watching the VODs too. There are several insances of control panels. One in the middle of video which seem to work though the speed indicator remains on 1.00 regardless of actual speed. And there seem to be 2 other speed indicators in top left corner, one showing the actual speed and one also stuck on 1.00.
Here is a VOD (don't ask me what it's about I've just randomly found one):
https://www.periscope.tv/thealexandrik/1OdKrNkajPVKX

![untitled](https://cloud.githubusercontent.com/assets/11561641/21568449/0161806a-ceb5-11e6-8913-8c739b085c67.png)

**Comment by canarslan12** [comment]
inject.js line 50
if(this.parent (or parent's parent) has class vsc-initialized) return; 
might fix it.

**Comment by igrigorik** [comment]
Seems to be A-OK now, guessing they updated their player.

**Comment by evodoc** [comment]
The only thing I see being different that there is no panel in the middle anymore. But there still are several ones on each other top left, and it doesn't expand to the buttons when hovered, only the speed is shown.

**Comment by igrigorik** [comment]
Multiple controllers is a bug in the video-js implementation on Periscope. Unfortunately not much we can do about that on this end.. without resorting to some really ugly hacks that are likely to break other players :(
