### ISSUE TITLE
video control panel disappears

### ISSUE THREAD

**Issue by evodoc** [igrigorik/videospeed#160]
Not sure if it's a bug or a feature request, but let me describe what it happens and what I suggest to happen instead:
- I open a youtube video which has 1.00 speed by default.
- I keep pressing the increase button.
- By the time I reach ~1.75, the control panel hides while I'm still clicking, which means I pause the video by accident.
So what I suggest is to wait like 1-2 seconds after last user interaction before hiding the panel.

**Comment by igrigorik** [comment]
Thanks for reporting this! Should be fixed in master.

**Comment by evodoc** [comment]
Is this supposed to be fixed in 0.4.4? It still happens.

**Comment by igrigorik** [comment]
The change is in development build (you can try it by installing an 'unpacked extension'), but we haven't released it to stable yet.

**Comment by evodoc** [comment]
@igrigorik this started happening again lately (0.4.6 + chrome)
