### ISSUE TITLE
[feature request] can you add a button to mirror videos?

### ISSUE THREAD

**Issue by gkovacs** [igrigorik/videospeed#163]
In particular, horizontal mirroring. This feature would be very useful for learning from dance videos on youtube (I'm guessing other extensions probably exist that provide the feature since it is trivial to implement but it would be nice to have it in this one).

The mirroring can be implemented by simply applying a tranform CSS rule to the video tag:

```
transform: scaleX(-1);
```

If it is too much effort for you to implement and you are interested in including the feature, I could probably make a pull request (I'd only have time for it a few months from now though I'm rather busy at the moment).

**Comment by igrigorik** [comment]
Huh, that's a really cool and interesting suggestion! Never occurred to me that the transform would be helpful to see the action from own perspective, and yet makes perfect sense.

That said, I don't think this fits into speed controller. As the name implies, our focus is on speed controls, and I think it would make more sense to have this functionality as a separate extension. I'd encourage you to make and publish this as a standalone ext.

Cheers.
