### ISSUE TITLE
bug: wrong playback speed is displayed

### ISSUE THREAD

**Issue by evodoc** [igrigorik/videospeed#164]
To reproduce:
- open a youtube video
- change speed
- click on the youtuber's name to go to his/her channel
- click "back" in the browser to go back to the initial video

Result: the video will be played at 1.00 but the plugin's panel will show the changed speed

P.S. or is it supposed to be the other way around, as in keeping the changed speed maybe? In any case the displayed speed and the actual speed is different.

**Comment by igrigorik** [comment]
Hmm, I can't seem to reproduce this. Are you using latest Chrome + version of the plugin?

**Comment by evodoc** [comment]
I am, as far as I know:
plugin 0.4.4
chrome 55.0.2883.87 m (64-bit)

**Comment by igrigorik** [comment]
Please try the latest version 0.4.5. If the problem persists, please reopen.
