### ISSUE TITLE
youtube vids wont play - spinning wheels - errors:  "if video doesn't play, restart device" 

### ISSUE THREAD

**Issue by wolfmagic7** [igrigorik/videospeed#166]
sent to google, but after disabling every extension i isolated which extension was culprit and further examination while writing this up before clicking submit revealed that speed = 0 was culprit.  but youtube/chrome was giving errors stating:  "if video doesn't play, restart device" with spinning wheels.

issue description:
suddenly cant play youtube vids in chrome except in incognito window, no extension conflicts reported, cleared cache/cookies, restarted chrome often, disabled 'auto play' in youtube and in 'magic actions' and disabled 'magic actions' and restarted, even rebooted windows and still no change.  i guess i'll disable extensions until i discover something, but is there anything else i'm missing?  

solution:
'videospeed controller' was the extension in play - toggling it on/off enables me to play or not play youtube videos.  further examination reveals issue is speed = 0.0 so i recommend the extension informs user in some way when speed is 0.0 to prevent them 5 days of troubleshooting, switching browsers, etc.

**Comment by igrigorik** [comment]
Thanks a lot for tracking this down and reporting it!

Fix will go out in the next release.

**Comment by canarslan12** [comment]
what is your "Remember Playback Speed" settings? did you try closing this option?
