### ISSUE TITLE
Allow regexes in blacklist

### ISSUE THREAD

**Issue by hftf** [igrigorik/videospeed#167]
Twitch live streams are usually found at `https://www.twitch.tv/foo`, while VODs (replays of previously broadcast streams) are usually found at `https://www.twitch.tv/foo/v/id`. While it is common for me to want to speed up VODs, I never intentionally speed up or speed down live streams, yet it happens frequently when I accidentally hit a shortcut key.

If there is no way to detect whether a video is a live stream (#152) and create an option to disable speed controls if so, then I’d like to have the ability to blacklist the first URL type and whitelist the second one. Would it be possible for the blacklist to allow either plain strings or regexes (delimited by `/…/` I suppose)?

**Comment by igrigorik** [comment]
Aside: you can buffer the live stream (hit pause) and then watch it on
high-speed once you've built up some reasonable chunk -- works great, and
saves a lot of time!

That aside, we do support regexes, you can take a look at the code here:
https://github.com/igrigorik/videospeed/blob/master/inject.js#L145-L162

**Comment by hftf** [comment]
If I understand that code correctly (which I looked at before filing the issue and almost cited myself), all special characters are escaped by the call to `escapeStringRegExp` in L158 (so that a blacklist line of `www.foo.com` becomes `/www\.foo\.com/` for example).

**Comment by igrigorik** [comment]
Yes, you're right we escape all the special characters. 

> I’d like to have the ability to blacklist the first URL type and whitelist the second one. Would it be possible for the blacklist to allow either plain strings or regexes (delimited by /…/ I suppose)

Let's assume we make that work. How would you accomplish the whitelist/blacklist for the twitch example above?

**Comment by hftf** [comment]
I would add `www.twitch.tv/[^/]+$` to the blacklist.

If delimiters like `/…/` are used, then it would be entered in the blacklist as the line `/www.twitch.tv\/[^\/]+$/`, with the user responsible for escaping special characters when needed.

**Comment by igrigorik** [comment]
Gotcha, sounds good. Are you willing to take a run at a PR?

**Comment by hftf** [comment]
Sure (but it won't be right away).

Let me know if you have more thoughts. For example, separate textareas for strings and regexes could be an option, instead of mixing strings and `/…/`-delimited regexes in the same textarea.

**Comment by igrigorik** [comment]
Nah, the // syntax seems reasonable and simple enough to implement.

**Comment by canarslan12** [comment]
inject.js line 162
```
	  regex = /www.twitch.tv\/[^/]+$/g; //has to be created with match = match.replace(some_code)
		while ((m = regex.exec("https://www.twitch.tv/foo")) !== null) {
			if (m.index === regex.lastIndex) {
				regex.lastIndex++;
			}
			m.forEach((match, groupIndex) => {
				blacklisted = true;
console.log(`Found match, group ${groupIndex}: ${match}`);

				return;
			});
		}
```

**Comment by deef0000dragon1** [comment]
Is there an update on this?

**Comment by hftf** [comment]
I did not end up working on a PR as stated in my earlier comment.

**Comment by ChadBailey** [comment]
Fixed in PR https://github.com/igrigorik/videospeed/pull/546
