### ISSUE TITLE
Shortcut to a set speed.

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#169]
It would be nice if there was a new shortcut for a custom speed.

I watch YT at 2.5x most of the time but often listen to music or whatnot and that requires default speed.
My speed step is 0.25x so going between 1x and 2.5x can be a bit annoying. So if, with a new shortcut, I could go straight from 1x to 2.5x it would make things alot more convenient.

Thanks for all the great work on this addon.

**Comment by igrigorik** [comment]
@Eisys ptal at the proposal in https://github.com/igrigorik/videospeed/pull/168#issuecomment-274972268.

**Comment by Eisys** [comment]
Ooo nice.

I tried out siadat's 'reset key toggle' commit and it works great. A much better way of adding this functionality than with a whole new shortcut and with very little new code. :)

**Comment by siadat** [comment]
Thanks!! :D 

To criticize my own idea, a potential downside of using R key is that there could be some users who press R multiple times to make sure the speed is reset. Or some might hold down the R key for a couple of seconds. I don't know if such users exist at all, but this kind of usage is no longer supported.

**Comment by Eisys** [comment]
Hehe, I do actually do that sometimes. Spam the reset key, that is. 

But I'm sure it's not too difficult to get out of this habit and just pay attention to the overlay to see what speed one is at.

**Comment by Eisys** [comment]
So after using this new feature for a few days, I've noticed that when I reset the speed to 1x, finish the video, close the tab and open a new video in a new tab, it won't switch between speeds anymore. Stays at 1x. As if it doesn't remember what the faster speed was anymore.

I have 'Remember Playback Speed' enabled so I guess it remembers that I last used 1x and goes to that on a new video. And then this update 'switches' between default 1x and the speed it remembers me last using, which is again 1x.

So perhaps a seperate shortcut isn't quite out of the question. Or maybe this is just a bug that could be fixed.

**Comment by siadat** [comment]
Thanks @Eisys for your feedback!

This should be easy to implement. We could store lastPlaybackRate in chrome.storage.sync,  similar to the way tc.settings.speed is stored and retrieved.

@igrigorik Shall I send a PR?

**Comment by igrigorik** [comment]
FWIW, this is not a bug, it functions as intended: we implemented it only for the local video; the setting is not persisted across sessions. 

@siadat I was hoping we could get away without it, but.. I can see how this may look like a bug to some. Yes.
