### ISSUE TITLE
Thoughts / Issues / Concerns with adding a Pause action / key

### ISSUE THREAD

**Issue by queuebit** [igrigorik/videospeed#171]
I have been really enjoying some of the YouTube tricks I learned from [Hank Green's video](https://www.youtube.com/watch?v=XUNriZD1OvQ), and since I just `J`, `K`, and `L` all the time on YT, I was wondering what it would take to make these _universal_ with `videospeed`.

Rewind / Advance are there, but there isn't an action to Pause. I just wanted to check to see if this was a design decision or feature opportunity.

thx again for an extension that has saved months of my life.

**Comment by canarslan12** [comment]
this extension has no pause button because space button always pause video.
by the way, i want to see an hotkey system like:

9 = 16
8 = 4
7 = 2
6 = 1.50
5 = 1.25
"r = 1.00"
4 = 0.75
3 = 0.5
2 = 0.25
1 = 0.1

**Comment by igrigorik** [comment]
> this extension has no pause button because space button always pause video.

^ yep, most players default space/play button to pause. Generally speaking, I'm inclined to stay away from adding more and more shortcut keys as they inevitably end up conflicting with other functions on various websites.

Going to close this. Thanks for your feedback and suggestions!

**Comment by queuebit** [comment]
Thanks for your consideration.
