### ISSUE TITLE
Can't get it to work at all

### ISSUE THREAD

**Issue by HeyBen24** [igrigorik/videospeed#177]
Hey there,

I've tried to get your extention working on my Chrome.  I havea  MacbookPro 2012, it's operating on the latest OS, 10.12.3, and I have the most updated Chrome browser (Version 56.0.2924.87 (64-bit)).
My colleague also has a Mac, same browser, and his extension is working fine in his Chrome Browser.  I can see the controls under the video playback of the video.  

For me, all I have is a little red icon in the upper right of the browser's taskbar, next to the three dots.  It gives me Settings, Send Feedback and About options.

When I start a video/audio file, I push the shortcut keys to speed it up (Defaulted to "D") - but that only slides in a screen on the right for Details.

I've deleted Chrome, deleted the files from the Library in the Go menu (~/Library/Application Support/Google/Chrome), reinstalled it and still nothing.

Would love to use this extension...just need to figure out how.

Thanks.

**Comment by igrigorik** [comment]
Is this behavior across all videos? For example, if you go to youtube.com do you see the controller show up on those videos?

**Comment by HeyBen24** [comment]
Thank you for responding. 

So recently the controls do appear after a brief second being invisible while using Chrome on some links (twillio, for instance, as I need to zoom through 20+ min audio recordings). However, I I get a link to listen to an audio file in google drive, your plugin doesn't work. I'm happy to make a video showing this if you'd like. 

Ben

**Comment by igrigorik** [comment]
> However, I I get a link to listen to an audio file in google drive,

We don't support `<audio>`, so that's as expected.
