### ISSUE TITLE
Don't work at livestream.com

### ISSUE THREAD

**Issue by ferulisses** [igrigorik/videospeed#179]
Hi,

There is any configuration to work?

**Comment by igrigorik** [comment]
Do you have an example video that I can test? 

![image](https://cloud.githubusercontent.com/assets/10652/23341881/e8a4d41e-fc04-11e6-8284-032b4e2621f7.png)

^ if they (still) rely on Flash, then there isn't much we can do about it..

**Comment by igrigorik** [comment]
Looking up some demos, it appears to be working a-ok here:
https://livestream.com/tedxworkshop/livestreamdemo/videos/9916470

![image](https://cloud.githubusercontent.com/assets/10652/25315187/007a0014-2806-11e7-9ec2-60c756099e0b.png)

Closing.
