### ISSUE TITLE
Doesn't work on lynda.com?

### ISSUE THREAD

**Issue by wilmtang** [igrigorik/videospeed#180]
No control panel appears on lynda.com, not sure whether what's the problem.

Here is a sample video, [https://www.lynda.com/Programming-Languages-training-tutorials/1467-0.html](https://www.lynda.com/Programming-Languages-training-tutorials/1467-0.html)

**Comment by sainaen** [comment]
It was [disabled](https://github.com/igrigorik/videospeed/blob/master/manifest.json#L30) on lynda.com almost two years ago, because of a problem described in #47.

**Comment by sainaen** [comment]
Hm. I've just tried it on their demo videos, and there seems to be no problem in the Chrome v59 (current dev on Linux.) Maybe it could be enabled again.

**Comment by igrigorik** [comment]
You're right, seems to be AOK now. They must have updated logic on their end. I'll remove them from the blacklist.
