### ISSUE TITLE
Looper option

### ISSUE THREAD

**Issue by ANMB** [igrigorik/videospeed#181]
Good Evening,

Is it possible to add a looping option to the plug in?  Similar to:

https://www.alvinhkh.com/looperforyoutube/ ?

Thank you!

**Comment by igrigorik** [comment]
This seems like a significant departure from what the plugin provides, and given that there is already an existing plugin that seems to do a good job of it.. I think this is out of scope. 

Thanks for your feedback!

**Comment by ANMB** [comment]
Hmmm - yet the feature would be used for not only videos, that are found elsewhere besides youtube, but also for mp3s that can be played in one's browser.  I use the videospeed for foreign language learning, and sometimes there are soundclips that I need it for, not just for videos.  And it would be more efficient to have the option for either/or, instead of using different tools.
