### ISSUE TITLE
Youtube: Hotkeys for prev/next frame do not walk by one frame but by one second

### ISSUE THREAD

**Issue by porg** [igrigorik/videospeed#186]
## Bug desription

Since I had installed **videospeed** 0.4.5 to Google Chrome 56.0.2924.87 on macOS 10.12.3 the shortcut keys `,` (comma) for "go to previous frame" and `.` (dot) for "go to next frame" have changed their behavior in **Youtube** permanently! It does not jump by one frame but by one second.

I checked whether Youtube may changed the hotkey/playback behavior by design, but in Safari `,` and `.` still work as go to prev/next frame. In Chrome I cannot test certainly, as it is now affected by the bug, but as far as I recall, I used frame jumping only a few days ago before having installed videospeed, and it still worked as usual.

## Bug isolation

As I have no idea what caused the bug, and as I found no way to restore my previous Youtube behavior, I provide every information possible, which may be related to it.

1) I have slightly changed Settings. See screenshot.
* I do not have `.` or `,` assigned as hotkeys for videospeed.
* I have had once changed the `Rewind time` and `Advance time` to `5`, but had changed it back to `10` again. When I first noticed the frame-jump-bug, all those changes were already made.
<img width="550" alt="videospeed settings" src="https://cloud.githubusercontent.com/assets/737143/23831258/169fdb2e-071e-11e7-87e1-332789ebf98c.png">

2) The bug was destructive in nature, it has changed the behavior permanently:
* Even if videospeed is deactivated in the Extension panel.
* Even after a restart of Google Chrome with videospeed deactivated.
* Even after completely uninstalling videospeed.
* Even after a restart of Google Chrome without videospeed installed.
* Even after reinstalling videospeed. Videospeed's settings were back to their defaults. But Youtube still affected by the frame-jump-bug.

This indicates that the extension videospeed did manipulate the settings of its host Chrome destructively/unisolatedly.

An idea: If such a hack is needed, make sure to backup original host settings, and when the extension gets deactivated or uninstalled, ensure to run a routine which restores the default behavior of the host. I do not know whether Chrome's extension systems provide such hooking functionality, but I guess so.

**Comment by Eisys** [comment]
This is probably something on your end. Said shortcuts work perfectly fine for me, skipping frames.
Chrome Version 57.0.2987.98 (64-bit) and videospeed 0.4.5
I just tried on a fresh profile, only installed videospeed and no problems.

Try this: https://web.archive.org/web/20160915221807/https://support.google.com/chrome/answer/142059 This completely resets chrome. After, you can delete the new 'default' and rename the old back again.
Or add a new user in chrome.
Or try completely reinstalling chrome.

I have also heard of this problem from other people and youtube themselves changing the shortcuts was mentioned. So perhaps only a few are getting this change, if it exists.

**Comment by igrigorik** [comment]
> The bug was destructive in nature, it has changed the behavior permanently.. Even if videospeed is deactivated in the Extension panel.

That's not possible. If the extension is disabled, it can't modify behavior of any page. As such, it could be some other extension, or an update on YT side itself - e.g. you could be part of an experiment.
