### ISSUE TITLE
Vine Issue

### ISSUE THREAD

**Issue by raven-pride** [igrigorik/videospeed#19]
This extension prevents users from being able to un-mute embedded Vines, as shown here:

![image](https://cloud.githubusercontent.com/assets/10361402/5591343/cecc2642-911b-11e4-9f2a-45d0d893eafc.png)

**Comment by igrigorik** [comment]
Do you have a public example page?

**Comment by queuebit** [comment]
I haven't experienced it before, but here is [an example page](https://vine.co/v/OrJj39YlL57) that shows the issue.

**Comment by jordn** [comment]
It's particularly noticeable on twitter.com eg. https://twitter.com/Vine_Football/status/550614684575858688

You can click on the playback speed to dismiss the box, and then unmute, but that's not ideal.

**Comment by igrigorik** [comment]
In theory, that should do the trick.. Can you guys try [installing the unpacked extension](https://developer.chrome.com/extensions/getstarted#unpacked) and trying it on your end?

**Comment by jordn** [comment]
Yep, works for me :+1:
