### ISSUE TITLE
No sounds when >4x?

### ISSUE THREAD

**Issue by renaidkim** [igrigorik/videospeed#193]
I notice that I can't hear sound past 4x on any video - Is this intentional or a bug? I'd love to listen to some of the videos at >4x if possible. Thanks.

**Comment by queuebit** [comment]
It's a Chrome thing, not a `videospeed` thing.

**Comment by igrigorik** [comment]
Indeed, this is enforced by chrome: https://cs.chromium.org/chromium/src/media/filters/audio_renderer_algorithm.cc?l=51

Nothing we can do on this end.
