### ISSUE TITLE
Can you make this work on vid.me ?

### ISSUE THREAD

**Issue by xftroxgpx** [igrigorik/videospeed#195]
Hi. This currently doesn't work on vid.me (the new youtube xD), but works for example on twitter, instagram, youtube ...

Is it possible to make this work on vid.me ? and if so, would you code the changes?

Cheers.

**Comment by sainaen** [comment]
Well, I've checked and it works for me: controls panel shows up and I can change speed.

Could you please clarify what doesn't work for you and provide more details about your setup? Like what versions of Chrome and extension do you have, whether you are logged in on the site, etc. Also, maybe some other extension conflicts with this one?

**Comment by xftroxgpx** [comment]
Sorry, by "doesn't work" I meant: the control panel doesn't show up at all and I cannot change the speed via keys.
I'm on Arch Linux, 64 bits, `[testing]` repo.
Chromium is 59.0.3046.0 (Developer Build) (64-bit)

But to be sure it's not my other extensions (uMatrix, uBlock, etc), I have now tried to get a chromium binary for linux via https://github.com/xftroxgpx/chromium-latest-linux `./update.sh` and ran `./go` and installed `videospeed` extension only. Youtube works and vid.me shows the videospeed control panel but the video is black and not playing any audio either, but I assume this is because of this chromium, because on my (built) chromium the video/audio work, and presumably then my other extensions(?) are the reason why the videospeed control panel doesn't show up on my built chromium.

Here are two screens (for the two chromiums) for comparison:
![screenshot_2017-03-30_12-56-23](https://cloud.githubusercontent.com/assets/26243389/24501175/af3808a6-1548-11e7-857d-e2bc05d4132f.png)



![screenshot_2017-03-30_12-58-28](https://cloud.githubusercontent.com/assets/26243389/24501222/dc78a262-1548-11e7-956c-ec24e027f468.png)
(why would vid.me need to access youtube there? I did try to allow it temporarily, no effect though)

And a bigger screen to show the videospeed control panel isn't hiding on top of video:
![screenshot_2017-03-30_13-00-55](https://cloud.githubusercontent.com/assets/26243389/24501278/14b9ddee-1549-11e7-8534-15ddd4ad8ab3.png)


But, I think that since you report it working, it must be something on my side and I will try to figure out what. I think it's safe to close this, but I will spam you with updates of my progress on fixing this :D if that's okay.

**Comment by xftroxgpx** [comment]
Ok, I made it work for my build chromium - I was using a local modified version of videospeed which had a manifest.json limited only to 3 websites(youtube,twitter,instagram) and that's why it wasn't working on vid.me!! Really apologize for forgetting this.

So it already does work for vid.me
Thanks all! :)

**Comment by sainaen** [comment]
Oh, you! I just figured out how to install extensions in Chromium (I don't know if it's only Debian version is weird/broken that way) and was about to write that it works there too. :)
But I'm glad you figured it out!

**Comment by xftroxgpx** [comment]
Thanks @sainaen . I really appreciate it.

**Comment by igrigorik** [comment]
👍
