### ISSUE TITLE
Doesn't work on Adobe Sparks videos

### ISSUE THREAD

**Issue by alexratman** [igrigorik/videospeed#196]
Hi, This works fine on some sites but I can't get it to work on Adobe sparks
https://spark.adobe.com/video/OZTmER52JG5hb/?skip_view_count=true

**Comment by Eisys** [comment]
Works fine for me on Chrome.
You are probably getting the flash player. If you can, disable flash and try again.

**Comment by igrigorik** [comment]
@alexratman ditto, works A-OK here. Please try these instructions: https://github.com/igrigorik/videospeed#faq. If that doesn't work, try creating a clean Chrome profile and install the extension there, it could be clashing with some other extension.

If that doesn't work, feel free to reopen.
