### ISSUE TITLE
Vídeos não estão mais executando

### ISSUE THREAD

**Issue by danytbt** [igrigorik/videospeed#197]
os vídeos do youtube e outros servidores simplesmente não estão mais executando se deixar o Video speed com a opção "Remember Playback Speed" ativada!!
Isso ocorre sempre quando sai do navegador e depois de um tempo inicio novamente uma nova navegação, além disso, quando se está reproduzindo um vídeo e pausa, ás vezes ocorre da reprodução simplesmente travar!

**Comment by igrigorik** [comment]
Odd, I can't reproduce the "remember playback speed" behavior on this end. Please try this:

- make sure you're running latest version of Chrome -- update it and restart all instances
- create a new Chrome profile and install the extension there
- try loading videos

My hunch is that you may have other extensions that are conflicting, or your Chrome is out of date. If the problem persists, please feel free to reopen.
