### ISSUE TITLE
Incorrect speed increasing

### ISSUE THREAD

**Issue by zenwarr** [igrigorik/videospeed#198]
After decreasing playback rate to minimal (0.06) it is impossible to return back to round values. My inner perfectionist is saddened by it.

Steps to reproduce:
1. Hit "slower" button until minimal (0.06) playback rate is reached
2. Try to set 1.0 rate again by hitting "faster" button multiple times.

Observed behaviour:
Playback rate takes the following values: 0.16, ... , 0.86, 0.96, 1.06, ...

Expected behaviour:
Playback rate takes the following values: 0.1, ... , 0.8, 0.9, 1.0, ...

**Comment by igrigorik** [comment]
Doh, you're right -- that's annoying. We should fix that.

As a workaround: you can hit "R" to reset to 1.0.
