### ISSUE TITLE
Additional Shortcuts

### ISSUE THREAD

**Issue by ThinkMaize** [igrigorik/videospeed#20]
Great work! This chrome extension is simple yet very helpful. If possible, it would be really convenient to be able to assign a keyboard shortcut to play/pause and to skip forward by a defined interval.

Awesome work, Thanks!

**Comment by igrigorik** [comment]
Hmm, if you have focus on the video player, the spacebar key should act as "pause / play" toggle already.

**Comment by ThinkMaize** [comment]
Hi ,

I just stumbled across this and don't think I ever responded.

You are correct. The reason for my request was for situations where the
play/pause button is not in focus. On Youtube, for example, if I click on
the video then space bar works for play/pause BUT if I click somewhere else
on the webpage (say to scroll through the comments), the speed up/speed
down/skip back buttons still work (ie your extention), but spacebar simply
scrolls down the page, and the video keeps playing.

A universal hotkey would be really nice so that I could play/pause
regardless of whether the video or something else on the page is in focus.

Thanks,
Alex
