### ISSUE TITLE
Isn't working in latest Chrome

### ISSUE THREAD

**Issue by bizcoach** [igrigorik/videospeed#201]
Version 57.0.2987.133 (64-bit). I can no longer speed up the videos. Google has also removed the ability to get into the plugins folder so disabling flash doesn't work either. The videos are on wistia.

**Comment by igrigorik** [comment]
Their demo videos appear to work A-OK on this end with latest Chrome: https://wistia.com/webinars/recorded_webinar/5%20Ways%20to%20Use%20Video%20Creatively%20Across%20Your%20Organization < does that work for you? If not, please try uninstalling the plugin, restart chrome, and install again and/or create a new profile and install it there.

**Comment by Eisys** [comment]
The demo videos work fine for me. Chrome Version 58.0.3029.54 beta (64-bit)

And disabling flash has moved to a new location: http://i.imgur.com/O83FSiU.png

**Comment by igrigorik** [comment]
Closing, please reopen if the problem persists.
