### ISSUE TITLE
Controls minimise after changing speed by one or two clicks.

### ISSUE THREAD

**Issue by eternalcakes** [igrigorik/videospeed#205]
On several video streaming platforms, especially on youtube the controls will minimise and display only the speed after clicking once or twice. It retains the speed set and can be expanded as normal. However, after clicking to speed up again, it will minimise again. This makes it difficult to get up to a high speed quickly, because you have to expand, speed up, (it minimises itself), expand, speed up (minimised)... etc. 

Sometimes it's better when the video is paused, but sometimes pausing the video makes no difference. 

Chrome  58.0.3029.81. Was also happening on 57.0.2987.133.

**Comment by igrigorik** [comment]
Merging with https://github.com/igrigorik/videospeed/issues/172 -- thanks for your feedback!

p.s. please try using the shortcuts! :)
