### ISSUE TITLE
Feature request: Add option to set default playback speed

### ISSUE THREAD

**Issue by chrissound** [igrigorik/videospeed#206]
Awesome plugin! Thanks

**Comment by xftroxgpx** [comment]
Do you mean, set the speed that key `R` resets to? which is 1.00 currently but not settable in options.

**Comment by igrigorik** [comment]
- `R` resets to 1.0x
- You can enable "remember speed" in settings to persist your last playback speed.
- We recently added "fast speed" default in https://github.com/igrigorik/videospeed/commit/b3db296c0a44632da0762fe08fb8e268976fb2e6 - this will go out with next release.

**Comment by chrissound** [comment]
Thanks 'remember speed' sounds like what I can use instead.

**Comment by canarslan12** [comment]
not explained in read.me and chrome page
