### ISSUE TITLE
Doesn't work with netflix

### ISSUE THREAD

**Issue by PhoenixRx7** [igrigorik/videospeed#208]
As above, chrome extension. As soon as a shortcut is pressed it gives the "whoops" screen.

**Comment by PhoenixRx7** [comment]
My bad, the shortcuts don't work, the menu pop-out system does.

**Comment by mrbusche** [comment]
fwiw I have no issues using this with netflix Version 58.0.3029.81 (64-bit)

**Comment by igrigorik** [comment]
Ditto. Please try updating your chrome + plugin. If the problem persists with latest version, feel free to reopen.
