### ISSUE TITLE
Request : Auto hide speed bar that show on video

### ISSUE THREAD

**Issue by HackKingSoft** [igrigorik/videospeed#21]
Hi! I love this chrome extension very very much. :D

But speed bar that show on video is bothersome, it will be great if you can make it auto hide.

Thank you so much for this awesome extension!

**Comment by igrigorik** [comment]
@HackKingSoft we do have the autohide logic in place for YouTube, I assume you're referring to other video sites?

**Comment by HackKingSoft** [comment]
Oh I see it only hide in fullscreen mode? I would prefer autohide in non-fullscreen mode too. :)

**Comment by igrigorik** [comment]
@HackKingSoft youtube video? If the video is on focus (e.g. you're hovering), you'll see the title + speed on controls on YouTube -- the behavior mimics YT defaults.

**Comment by igrigorik** [comment]
(closing, feel free to reopen if necessary)
