### ISSUE TITLE
Can't click the speed controller on new Facebook video lightbox design

### ISSUE THREAD

**Issue by ngyikp** [igrigorik/videospeed#210]
**Steps to reproduce:**
1. Go to https://www.facebook.com/search/videos/?q=facebook&filters_rp_author=125459124158601
2. Click on any video
3. Try to click the speed controller, you may need to resize your browser window to be smaller to reveal the problem

**Diagnosis:**

There is a `._4g9v` gradient overlay `<div>` overlapping the speed controller

<img width="1171" alt="screen shot 2017-05-05 at 12 24 55 am" src="https://cloud.githubusercontent.com/assets/6135313/25714107/8cd229a2-3129-11e7-843b-ba856063692d.png">

Cheap solution would be applying `pointer-events:none` to that gradient overlay and re-enabling it for links and fullscreen button

**Comment by igrigorik** [comment]
Hmm, that link doesn't lead me to any videos. 

Trying on https://www.facebook.com/pg/facebook/videos/. I see the lightbox popup and I can click on the controller just fine. Do they have another player?

**Comment by ngyikp** [comment]
Yeah, they have two player designs, you are probably referring to the first one I think:

![screen shot 2017-05-07 at 12 58 47 am](https://cloud.githubusercontent.com/assets/6135313/25774398/6bc2dbd8-32c0-11e7-8159-28c2c3fc1933.jpg)

<img width="1073" alt="screen shot 2017-05-07 at 12 50 59 am" src="https://cloud.githubusercontent.com/assets/6135313/25774315/6c8b9a56-32bf-11e7-879a-0ba6e0debc06.png">

Perhaps try https://www.facebook.com/lists/395166260525759 ?

**Comment by igrigorik** [comment]
Ah, yep, now I see it. It looks like the difference is based on whether you open the video from the news feed vs got the post/video page directly. Either way, this is a close cousin of https://github.com/igrigorik/videospeed/issues/134 -- we see similar issue for Amazon video. 

I've tried to stay away from special-casing sites with custom rules, but I don't see any other way here. If we go down this path, we could try to custom target where the controller is injected (e.g. above the overlay). Something to experiment with..

**Comment by ngyikp** [comment]
Brainstorm: Inject the controller at the `<body>` tag directly (e.g. `html > body > #controller-123`), and only show and reposition the controller when you mouse over the video, and eliminates the need for the draggable

**Comment by ngyikp** [comment]
I tried this idea: https://github.com/igrigorik/videospeed/compare/master...ngyikp:controller-on-body-tag

But the mouseenter/leave idea doesn't work because the overlays are blocking the mouse :(

**Comment by igrigorik** [comment]
@ngyikp that would also break down on pages with multiple videos (and controllers), right? I haven't dug deep enough into FB code, but in case of Amazon the issue could be resolved by injecting the controller above the overlay.

**Comment by canarslan12** [comment]
I found a global solution;
set `z-index: auto;` to parent of `vsc-controller`

**Comment by igrigorik** [comment]
@canarslan12 interesting! How were you testing this? Injecting this rule via JS? Do you have a branch we can test?

**Comment by canarslan12** [comment]
after loading finished and jquery added to main game, type this to console:
`$(".vsc-controller").parent().css('z-index', "1");`
