### ISSUE TITLE
Not always showing increased speed when using 'Preferred Speed' hotkey

### ISSUE THREAD

**Issue by baz357** [igrigorik/videospeed#214]
Hi,

I've always used the d and s keys to increase/decrease speed. Recently I started to use the 'Preferred Speed' hotkey to directly jump to the 1.60 speed I mostly use, and I found that while it always increases the speed, sometimes it shows the speed as still being 1.00. When I then increase or decrease the speed, it correctly shows the changed value.

Not a big issue and I didn't find a way to reproduce it, just wanted to let you know. Thanks for this lovely extension!

**Comment by canarslan12** [comment]
It might be related with not ready(unset) videos. Can you test it?

**Comment by baz357** [comment]
Yes, you are right - it *is* related. I can sometimes reproduce it by using the 'Preferred Speed' hotkey right after the video loads, if I wait a few seconds it displays the speed correctly.

**Comment by canarslan12** [comment]
I think problem is here. Let's ask why @igrigorik add this code. Is it safe to remove?
'
        if (target.readyState === 0) {
          return;
        }
'

**Comment by canarslan12** [comment]
I checked file history and contributor for that line was @oggy #e75f4f0
he was saying that "Fixes speed setting when jumping between YouTube videos." but there is no problem about it when removing this lines currently

**Comment by igrigorik** [comment]
Closed via #214.
