### ISSUE TITLE
Video controller overlaps Google Photos controls

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/videospeed#215]
Reported by @fredsa: 

![image](https://cloud.githubusercontent.com/assets/10652/26258502/c31d4b44-3c79-11e7-8329-4408fab0a42c.png)

We have custom code to change position for YouTube, need to do the same here..

**Comment by SeanSilke** [comment]
Controls also seams positioned in odd place in fullscreen mode.
![Uploading Screenshot at Jun 01 16-17-23.png…]()
