### ISSUE TITLE
Reset speed use preferred speed at first

### ISSUE THREAD

**Issue by canarslan12** [igrigorik/videospeed#216]
> would be cool.
> I don't like starting videos with high playback rate but I would like to get previous speed that I have with pressing R key once.
> fx: video1 in youtube; pressed d 10 times to reach 4.00 closed it
> video2 opened and pressed r makes speed 4.00

edit: reset speed might use preferred video speed at first, it will be better.

**Comment by igrigorik** [comment]
Isn't that what "remember speed" already accomplishes?

**Comment by canarslan12** [comment]
But reset button is not working at first and I always clicking it.

**Comment by igrigorik** [comment]
As in, you expect reset key to switch to preferred speed? That's not the intent.. or I don't follow.

**Comment by canarslan12** [comment]
I checked code and did it with only changing 1 line. Pulling after some test

**Comment by igrigorik** [comment]
Resolved via #216.
