### ISSUE TITLE
Control visibility / color / opacity of button

### ISSUE THREAD

**Issue by Wisdawn** [igrigorik/videospeed#22]
Hi. Thank you very much for this excellent Chrome extension.

The very first time I tried to use the extension, I could neither use the shortcuts (pressing them had no effect), nor see the button at all. I thought something was wrong, and refreshed the page, but still nothing. I was going to uninstall the extension in disappointment. But something made me watch another video before uninstalling (just for the heck of it), and lo and behold, I do notice the button—but barely—hiding at the top left corner of the video! And it was a lucky shot, because that specific video just happened to have two thick black bars or borders at the right and left.

According to this experience, I strongly recommend some sort of slider or extra button that helps the user control the transparency / opacity of the button after they first notice it. Or even better, you can even update the extension so that the button shows up with an obvious color and no transparency / opacity, but as soon as the user hovers the mouse pointer over it, the button takes on a subtle color and gets becomes 50% or so transparent. Then the user can make it more visible again should they wish to do so.

**Comment by igrigorik** [comment]
@Wisdawn thanks for the feedback!
