### ISSUE TITLE
doesn't work with crunchyroll

### ISSUE THREAD

**Issue by raeleneg** [igrigorik/videospeed#223]
my anime </3

**Comment by SeanSilke** [comment]
@raeleneg Hi. 
 On crunchyroll video is plaid through  Flash Player. This plugin don't support it.
Only HTML5 video is supported.

**Comment by igrigorik** [comment]
Indeed. Flash only.. sadly. Once they switch to HTML5, everything should just work. In the meantime, nothing we can do on this end.
