### ISSUE TITLE
Add button to request  "Allow access to file URLs"

### ISSUE THREAD

**Issue by SeanSilke** [igrigorik/videospeed#225]
Now the is part in description how to enable playback of local media.
The user need manually add additional permissions.
It seems possible to add button to request this permission.

Is it good idea to add this feature?

**Comment by igrigorik** [comment]
Is there a new permission for this?

**Comment by SeanSilke** [comment]
Took a good look at available permissions, and yes there is no such permission.
Hopefully i will find another way to improve this extension.

**Comment by igrigorik** [comment]
👍
