### ISSUE TITLE
"Invalid Url" on S key.  

### ISSUE THREAD

**Issue by zfreeds** [igrigorik/videospeed#226]
Sometimes pressing the "S" key to slow down the video will open a dialog saying "Invalid Url (".  This problem will continue to occur until the page is reloaded.

**Comment by igrigorik** [comment]
Is this happening on a particular site?

**Comment by igrigorik** [comment]
Closing as I can't reproduce, please reopen if you have a particular example we can debug.

**Comment by zfreeds** [comment]
@igrigorik .  I'm sorry for the very late reply.  My github notifications seem to be broken.  I would say this happens usually on Youtube but that could just be because most videos I watch are on Youtube.  I still cannot give proper steps to reproduce as it happens randomly.  If I ever figure out the steps, I shall let you know

**Comment by Steve-357** [comment]
This is happening to me on YouTube, on a variety of videos and channels.  Windows 10 Pro, 64-bit, latest release of Chrome.  I do use Diigo, and the "capture" button for Diigo appears close enough to the speed control that I can't adjust the speed from there.
