### ISSUE TITLE
Allow MouseScroll to change speed #enhancement

### ISSUE THREAD

**Issue by siddhantrimal** [igrigorik/videospeed#228]
Please allow a toggle-able option to allow mouse-scroll key to control video speed. Clicking in the middle should pause the video by setting speed to 0.00 . Please set this aside as an additional toggleable option so as to not bother current users wh may not want to use it.

**Comment by igrigorik** [comment]
We reverted (and removed) the mouse-scroll functionality -- see https://github.com/igrigorik/videospeed/pull/188#issuecomment-299344012. The update will go out in the next release.. the cost + complexity was not worth the extra options in this case.
