### ISSUE TITLE
Playback speed is not restored between YouTube playlist videos

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/videospeed#23]
> The current playback speed is not restored but set to 1.00 between YouTube playlist videos, although the "Remember Playback Speed" setting is checked. This happens although the current and previous videos are HTML5. Version is 0.2.2

I've noticed the same issue on a few videos.. need to investigate.

**Comment by brauliobo** [comment]
I still have this issue with playlists created through queueing videos. Also, if the restore option is enabled, the speed is set to 1.00 after pause and play actions.
