### ISSUE TITLE
content_scripts "all_frames": true  is bad in one case (causes double inputs)

### ISSUE THREAD

**Issue by xftroxgpx** [igrigorik/videospeed#230]
Just a heads up if anyone is experiencing double inputs (eg. when increasing video speed via key `d` it increases from 1.00 to 1.20 even though step is 0.1):

When in youtube edit mode the extension scripts run twice due to manifest.json 's
```json
"content_scripts": [{
      "all_frames": true,
```

setting `"all_frames": false,` seems to work in all cases (edit or play) but who knows why it was set to true, perhaps for good reason(?).

Tested this with latest commit https://github.com/igrigorik/videospeed/commit/7ea778d3ec08d2fc890447d25f2b0af550336602 (not my fork!)

screenshot to get an idea what 'edit mode' means:
![screenshot_2017-06-29_19-15-24](https://user-images.githubusercontent.com/26243389/27701307-c63b5b48-5d00-11e7-92c7-046cd9292375.png)

**Comment by igrigorik** [comment]
> all_frames: Optional. Controls whether the content script runs in all frames of the matching page, or only the top frame

We need to enable this to enable controller functionality in external embeds -- e.g. YouTube, Vimeo, etc, all typically embed videos inside of injected iframes.

That said, I think the actual issue here is that we instantiate two controllers within the same frame.

**Comment by xftroxgpx** [comment]
> That said, I think the actual issue here is that we instantiate two controllers within the same frame.

I am under the impression that "we" == "chromium" because the actual scripts (eg. inject.js) are "executed" twice. If you put `console.log("inject.js Math.random()=",Math.random());` as first line in `inject.js` for example, you see it.

**Comment by xftroxgpx** [comment]
Here's the difference between normal video play and edit video play, in terms of the arg passed to `initializeWhenReady`:

normal video play:
![screenshot_2017-07-02_12-32-17](https://user-images.githubusercontent.com/26243389/27769115-26dbf7cc-5f23-11e7-9217-467c3462277c.png)

edit-mode video play:
![screenshot_2017-07-02_12-32-37](https://user-images.githubusercontent.com/26243389/27769118-32ad7062-5f23-11e7-8383-9fb51f9464ef.png)


Both have an initial call of `initializeWhenReady` with the whole `document` (I'm ignoring that). It's the second call that's the difference.

**Comment by xftroxgpx** [comment]
```javascript
tc.videoController.prototype.initializeControls = function() {
      var document = this.document;
      console.log("tc.videoController.prototype.initializeControls, doc=",document);      
```

that func. gets called with the same document twice:
![screenshot_2017-07-02_12-51-57](https://user-images.githubusercontent.com/26243389/27769221-a70b8dc0-5f25-11e7-8961-1103191ec45e.png)

confirming [what you said](https://github.com/igrigorik/videospeed/issues/230#issuecomment-312477055)

**Comment by xftroxgpx** [comment]
quick and dirty workaround, tested to work with all 3 cases

```patch
diff --git a/inject.js b/inject.js
index 8e1a2ab..bbb5aaa 100644
--- a/inject.js
+++ b/inject.js
@@ -50,6 +50,10 @@ chrome.extension.sendMessage({}, function(response) {
 
   function defineVideoController() {
     tc.videoController = function(target, parent) {
+      if (target.classList.contains('vsc-initialized')) {
+        return;
+      }
+
       this.video = target;
       this.parent = target.parentElement || parent;
       this.document = target.ownerDocument;
@@ -191,6 +195,11 @@ chrome.extension.sendMessage({}, function(response) {
   }
 
   function initializeNow(document) {
+      if (document.body.classList.contains('bleh-initialized')) {
+        return;
+      }
+      document.body.classList.add('bleh-initialized');
+
       if (document === window.document) {
         defineVideoController();
       } else {
```

**Comment by igrigorik** [comment]
@xftroxgpx why did you add the `bleh-` check? 

PTAL at https://github.com/igrigorik/videospeed/pull/235. That fixed the double initialization (i.e. I don't see two overlapping controllers), but curiously enough, shortcut input still jumps by 2x the amount! Haven't figured that one out yet.. =/

**Comment by xftroxgpx** [comment]
Well, without it you get the `keydown` event registered twice... and everything else after that.
Oh and I didn't know how else to prevent that initializeNow from happening twice for the same `document`.

**Comment by xftroxgpx** [comment]
Looks like the `videoController` check is not needed if I use the `initializeNow` check. That is, that `if` in #235 is not reached.

**Comment by xftroxgpx** [comment]
```patch
diff --git a/inject.js b/inject.js
index 8e1a2ab..aac7c7d 100644
--- a/inject.js
+++ b/inject.js
@@ -50,6 +50,12 @@ chrome.extension.sendMessage({}, function(response) {
 
   function defineVideoController() {
     tc.videoController = function(target, parent) {
+      //if (target.classList.contains('vsc-initialized')) {
+      if (target.dataset['vscid']) {
+        console.log("!! already vc=",target);
+        return;
+      }
+
       this.video = target;
       this.parent = target.parentElement || parent;
       this.document = target.ownerDocument;
@@ -191,6 +197,14 @@ chrome.extension.sendMessage({}, function(response) {
   }
 
   function initializeNow(document) {
+      if (document.body.classList.contains('bleh-initialized')) {
+        console.log("!! Avoiding initializeNow, doc=", document);
+        return;
+      }else{
+        console.log("!! InitializeNow, doc=", document);
+      }
+      document.body.classList.add('bleh-initialized');
+
       if (document === window.document) {
         defineVideoController();
       } else {
@@ -244,9 +258,9 @@ chrome.extension.sendMessage({}, function(response) {
       function checkForVideo(node, parent, added) {
         if (node.nodeName === 'VIDEO') {
           if (added) {
-            if (!node.dataset['vscid']) {
+            //if (!node.dataset['vscid']) {
               new tc.videoController(node, parent);
-            }
+            //}
           } else {
             if (node.classList.contains('vsc-initialized')) {
               let id = node.dataset['vscid'];
```

![screenshot_2017-07-03_09-50-59](https://user-images.githubusercontent.com/26243389/27783102-2388a806-5fd5-11e7-8ac0-1adbe5b8f632.png)

**Comment by igrigorik** [comment]
> Well, without it you get the keydown event registered twice... and everything else after that.

Ah, right.. of course. Ok, your last patch looks reasonable (well, modulo variable naming.. :)). Do you want to make a PR and we can iterate there?

**Comment by xftroxgpx** [comment]
I'd much rather that you make the necessary changes that you deem, if it's all the same to you. I don't care about getting any (naming)credit(s) :) (ie. commit author and what not)
Just fix this the way you want to, I figure it's better/faster :)

**Comment by igrigorik** [comment]
@xftroxgpx I believe this should be resolved in master. Can you take it out for a spin and confirm?

**Comment by xftroxgpx** [comment]
Confirmed working as expected(tested normal play and edit-mode videos)! Cheers! Much appreciated!

**Comment by hbhakhra** [comment]
I often see an error in my console that "inject.js:207 Uncaught TypeError: Cannot read property 'body' of null" on this line " if (document.body.classList.contains('vsc-initialized')) {". Do you know if that is a known problem?

**Comment by igrigorik** [comment]
@hbhakhra can you share an example URL where you see this?
