### ISSUE TITLE
Scrolling while accidentally hovered over the video speed display changes the speed

### ISSUE THREAD

**Issue by arikroc** [igrigorik/videospeed#231]
I think it would be better to disable scroll to change speed

I've never done this intentionally, only ever as an accident

I'll be looking at a video, scroll down, and then next thing I know the speed is set at 0.06 because I happened to scroll while hovered over the speed display

**Comment by sainaen** [comment]
This was already removed and will be gone in the next release. See discussion on #188, starting from [this comment.](https://github.com/igrigorik/videospeed/pull/188#issuecomment-299344012)

**Comment by arikroc** [comment]
Ah thanks
