### ISSUE TITLE
bug(?)/feature request: can't enable panel after closing

### ISSUE THREAD

**Issue by evodoc** [igrigorik/videospeed#232]
So there is a hotkey ('V' by default) you can toggle the panel with, but if you close the panel by clicking 'X', you can't enable it anymore. Is there something you can do about this?

**Comment by igrigorik** [comment]
As is, they're completely different features.. One simply hides the controller by overriding its style, whereas the other removes it completely by unregistering any/all listeners, etc.

**Comment by evodoc** [comment]
But is there any reason to implement it this way?

**Comment by igrigorik** [comment]
Which way would you propose?

**Comment by evodoc** [comment]
That 'V' would restore the panel no matter the way it was closed.
