### ISSUE TITLE
Speed resets on facebook

### ISSUE THREAD

**Issue by vogler** [igrigorik/videospeed#240]
When there are multiple videos, changing speed applies to all of them, but when loading new videos it sometimes just resets to 1.0x (despite having 'Remember Playback Speed' enabled).
I wasn't able to reproduce exactly what happens - sometimes some videos in between also get a speed of 0.0x (or last speed - 1).

**Comment by igrigorik** [comment]
I have a strong hunch that this is related to https://github.com/igrigorik/videospeed/issues/233 -- let's merge the threads there. We also have a patch https://github.com/igrigorik/videospeed/pull/237 that should, in theory, fix it.. if you're willing to give it a try.
