### ISSUE TITLE
Conflicts with Imagus Chrome plugin on Facebook

### ISSUE THREAD

**Issue by JRichmond27** [igrigorik/videospeed#241]
On facebook.com, Video Speed Controller causes the [Imagus popup to be displayed under some of the FB page elements](https://www.reddit.com/r/imagus/comments/6mcvre/imagus_images_popping_up_behind_thumbnails_on). (http://imgur.com/a/rxW7m) The issue is related to [line 155 of inject.js](https://github.com/igrigorik/videospeed/blob/master/inject.js#L155), which changes the Imagus popup to get `z-index: auto`.

The only current workaround is to blacklist facebook.com in the Video Speed Controller settings.

**Comment by igrigorik** [comment]
Thanks for reporting this. The next question is how to fix this.. without reverting the other fixes. =|

**Comment by JRichmond27** [comment]
Good question. I don't really use Video Speed on Facebook, so I wasn't aware of the overlay problems that the previous fix took care of. It'd be a pretty simple fix if Imagus provided an ID or class on their popup div.

The Imagus div is located outside of the closing body tag. Maybe you can target only elements within the body?
