### ISSUE TITLE
Volume reduces when scrolling up

### ISSUE THREAD

**Issue by Xerus2000** [igrigorik/videospeed#242]
When I scroll up fast the volume often reduces. I guess that stems from the fact that I have a volume step of 8 thus the volume get's reduced upon reaching 104%.

**Comment by igrigorik** [comment]
The plugin does not control or affect volume at all, I think this may be some other functionality on the site, or perhaps another plugin? Closing, as this is a noop for this plugin.

**Comment by Xerus2000** [comment]
derp, wrote feedback for the wrong plugin

**Comment by igrigorik** [comment]
:)

no worries!
