### ISSUE TITLE
Audio speed >4x & future of playback speed

### ISSUE THREAD

**Issue by FASTVIEWER** [igrigorik/videospeed#245]
Hey man, the app's changed my life - love you for it. Just wondering, is there any way to change Chrome settings so they allow audio to be sustained above x4 speed (as indicated here https://cs.chromium.org/chromium/src/media/filters/audio_renderer_algorithm.cc?l=51)? I'm trying to see if I can do the same thing with apps like VLC too so any advice about html5 video playback speed would be appreciated.

The ability to control the rate we watch/listen to media is also something I see as pretty revolutionary in terms of being able to process cultural and educational material. Can you forsee playback speed manipulation ever achieving mass popularity and technology allowing video/audio to be changed to any desired speed (>16x etc) in the future?

Thanks!

**Comment by igrigorik** [comment]
Glad it's been useful!

FWIW, the limitation here is not the plugin but the underlying audio+video processing engine and algorithms. Is it technically possible to have faster playback? Yeah, probably. But, Chromium decided to cap their playback at 4x and there is nothing we can do from the plugin to override that.. In theory, you can change those defaults and build your own Chromium, but that's not for the faint of heart. :-)

If you feel strongly about this, I'd recommend taking this discussion to crbug.com and CC authors on that code to see if they'd be willing to increase the limits.

(Closing this, as there is nothing plugin actionable on our end)
