### ISSUE TITLE
Controls disappear when Youtube is fullscreen (Chrome)

### ISSUE THREAD

**Issue by jclark-dot-org** [igrigorik/videospeed#247]
This seems to be a very new issue; I did not experience it yesterday. I think Youtube has made some changes to their player/layout; something looks subtly different.  Reloading the page and restarting Chrome make no difference.

When viewing a Youtube video and NOT in fullscreen mode, the control widget appears as normal.  Upon entering fullscreen video mode, the control widget disappears.  Keyboard shortcuts remain active.

Chrome 59.0.3071.115 on Mac OS 10.11.6
Video Speed Controller 0.4.8

**Comment by BlackCapCoder** [comment]
I do not have this problem in Chromium 61.0.3141.7 on Arch Linux

**Comment by igrigorik** [comment]
Ditto, can't reproduce. Please update Chrome..  if you still see same behavior, please reopen.
