### ISSUE TITLE
Please change the message disabling Flash plugin in Chrome

### ISSUE THREAD

**Issue by rodfreitas** [igrigorik/videospeed#249]
where we see "in a new tab, navigate to chrome://plugins"
see "in a new tab, navigate to chrome://settings/content/flash"

it will help a lot people that want to make videospeed work in sites that runs flash.

**Comment by rodfreitas** [comment]
this message is in Settings of Videospeed

**Comment by SeanSilke** [comment]
Goode one.
 Also on chrome v59 the link  "chrome://plugins" is leading no where. So whole algorithm to disabling flash is misleading.
