### ISSUE TITLE
Error when using browser's form autofill

### ISSUE THREAD

**Issue by vovayatsyuk** [igrigorik/videospeed#250]
```
Uncaught TypeError: event.getModifierState is not a function
```

When using native autofill feature in Chrome, `keydown` event is raised but event object is missing `keyCode` property and `getModifierState` function.

What do you say about additional check for these parameters [on the top of event listener](https://github.com/igrigorik/videospeed/blob/master/inject.js#L222)?

p.s. Here you can test the issue: https://www.roboform.com/filling-test-all-fields

p.p.s My Chrome version is `Version 59.0.3071.115 (Official Build) (64-bit)`

**Comment by igrigorik** [comment]
@vovayatsyuk thanks for reporting this. An extra check sgtm. Up for making a PR? :)
