### ISSUE TITLE
Controls on vimeo embed are not accessible after rebuffer?

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/videospeed#255]
Example: http://eclassesbyravindra.com/mod/page/view.php?id=288

Works all good at first, but if you accelerate to the point where you cause a rebuffer, you can no longer trigger controller when hovering.

**Comment by canarslan12** [comment]
when I fix this issue with similar things like reverted `this.parent.style.zIndex = 'auto';`  facebook fix( https://github.com/igrigorik/videospeed/commit/daec249e3f90656e59b45d5e95b0350414d88132 ), one click on video makes video fullscreen (not pausing). We have to fix this z-index issue with another solution

**Comment by canarslan12** [comment]
I think we should fix this with something like adding panel to body but I don't know well about positioning
this cause only 'one control panel with multiple videos' and 'not changing position when video moved with js/css' 
inject.js#101
```
        top = Math.max(this.video.getBoundingClientRect().top, 0) + "px",//for positioning 
        left = Math.max(this.video.getBoundingClientRect().left, 0) + "px";
```
inject.js#168
```
          // this.parent.insertBefore(fragment, this.parent.firstChild); not video's siblings, append to body
          document.body.append(fragment);
```

**Comment by igrigorik** [comment]
Exposing controls in the menu (in addition to the speed text) might be the right long-term solution here..
