### ISSUE TITLE
Speed keeps dropping to 0.00

### ISSUE THREAD

**Issue by Benu-Athanasia** [igrigorik/videospeed#258]
I've noticed this on two laptops; I'll be watching Youtube or an FB video and the speed will go from 1.00 to 0.00. Both times, nothing was on the keyboard.

**Comment by canarslan12** [comment]
I can't reproduce this.
Any other extensions you installed, that could be conflicting?

**Comment by igrigorik** [comment]
Ditto, can't reproduce. Is the video rebuffering when it happens?

**Comment by igrigorik** [comment]
Closing, please feel free to reopen if you can provide more details / steps on how to reproduce.
