### ISSUE TITLE
Sorry, I'm a total Noob

### ISSUE THREAD

**Issue by Samjabr** [igrigorik/videospeed#259]
I wasn't sure where else to ask... Is there a way to make a $ contribution to the developer? I'm not rich, or anything silly like that, but this extension has given me so much time. I appreciate that.

Thanks.

Samjabr@gmail.com

**Comment by igrigorik** [comment]
@Samjabr a good review on Chrome store and a thank you.. the currency of open-source. :-)

Thank you, glad it's been useful!
