### ISSUE TITLE
Netflix issue code M7375

### ISSUE THREAD

**Issue by Rawsted** [igrigorik/videospeed#260]
Issue code M7375 appears when i press 
Z for rewind
or
C for Advance

tryed to put some other key bindings but that didn´t work either.

**Comment by igrigorik** [comment]
This is a bug on Netflix side, related discussions:

- https://github.com/igrigorik/videospeed/issues/84
- https://stackoverflow.com/questions/27927950/controlling-netflix-html5-playback-with-tampermonkey-javascript

Unfortunately not much we can do address this on our end.. closing. :(

**Comment by thefantas** [comment]
The addon 'Netflix Dual subtitle for learning languages', manages to make it work. It would be a matter of reviewing how they do it (it works very well on netflix).

**Comment by stephenbrady** [comment]
It looks like this Stackoverflow comment provides a clue about how to resolve: https://stackoverflow.com/a/65488170

Happy to submit a PR if you'll review it.

**Comment by igrigorik** [comment]
@stephenbrady that's a great find! Yes, happy to review if you're willing to pull it together.
