### ISSUE TITLE
Save speed across videos

### ISSUE THREAD

**Issue by fabioespinosa** [igrigorik/videospeed#261]
Awesome work with this extension 👍 

It would be even more awesome if you could save the current speed for next videos. I often find myself doing a course online and having to speed up again in the next video.

Thanks! 💯

**Comment by igrigorik** [comment]
That's a thing already :) Go to your plugin options and check "remember speed" -- that should do it.

**Comment by fabioespinosa** [comment]
Just found it! Thanks a lot!! your extension saves quite a lot of human time, what a noble cause 👍
