### ISSUE TITLE
Keep buttons visible even when youtube playback interface disappears

### ISSUE THREAD

**Issue by jjgh** [igrigorik/videospeed#262]
Hi, can you implement an option for not making the buttons disappear when the youtube playback interface disappears (after x seconds of mouse/keyboard idle time) ?

**Comment by igrigorik** [comment]
Good news, that's a thing already! :) Hit "v" when on YT video page, and it'll "force" the controller to remain visible. You can customize the shortcut in plugin options.

**Comment by jjgh** [comment]
Perfect, thanks! :)
