### ISSUE TITLE
Netflix videos loosing audio/video sync

### ISSUE THREAD

**Issue by obprado** [igrigorik/videospeed#266]
When watching a video on Netflix for 10-20 minutes at speed 0.80x the video and the audio start getting out of sync. Happens both in Firefox & Chrome. Fixes after reloading the page (F5)

**Comment by igrigorik** [comment]
Yikes. This is a bug in media engines in both browsers. Can you please file bug on crbug.com and one against Mozilla?

Closing this one, as this is not controlled or influenced by the extension.
