### ISSUE TITLE
Console.error when SVG in the page.

### ISSUE THREAD

**Issue by TiagoFuelber** [igrigorik/videospeed#269]
I was working on a website an noticed this error that appears on console, maybe because my page has an ```<object>``` element with and SVG.

![image](https://user-images.githubusercontent.com/22480988/30989989-077e7a06-a476-11e7-8b49-a880195dad3f.png)

It was Chrome. I don't know what information I should give further. Feel free to ask me for further specific info about the isse.

Chrome  61.0.3163.100
Windows 10

Thanks

**Comment by igrigorik** [comment]
@TiagoFuelber do you have an example page where we could reproduce this?

**Comment by TiagoFuelber** [comment]
Yes, this link. http://portoferreira.sp.gov.br/secretarias
