### ISSUE TITLE
Custom playback speed not saved for embedded videos

### ISSUE THREAD

**Issue by Wisdawn** [igrigorik/videospeed#27]
For example, on Khan Academy website, I have to keep speeding up the video manually with every new page, which can get tedious with short videos and long courses with many of them; plus keyboard shortcuts not working on such pages makes things even more repetitive as one is forced to use the mouse. 

It would help a little if the + any - signs are always visible—with the speed—and clickable.

Thank you.

**Comment by igrigorik** [comment]
Thanks for reporting this! I think above commit should address this.

**Comment by Wisdawn** [comment]
The videos on Khan Academy now automatically follow the previously set speed. Thank you for sorting this out!
