### ISSUE TITLE
consider switching to the mpv/VLC keybindings as default

### ISSUE THREAD

**Issue by wolftune** [igrigorik/videospeed#273]
specifically, LEFT-arrow and RIGHT-arrow for rewind/fast-forward, and [ and ] for slow-down/speed-up.

See https://mpv.io/manual/stable/

These are more logical besides being universal.

**Comment by raduflp** [comment]
you can make the same argument from the opposite perspective. 
Personally I changed the VLC keybindings to match the ones for videospeed as I find it more convenient to keep my right hand always on the mouse and adjust the speed with the left hand.

**Comment by wolftune** [comment]
@raduflp  Yeah, but anyone who always keeps a hand on the mouse is going to be in the minority to consider key-bindings. Key bindings are for keyboard users first. A large portion of mouse users will use the mouse for the speed control too. So you're likely the odd one: a dedicated right-handed mouse user who still cares about key bindings.

**Comment by igrigorik** [comment]
Thanks for the suggestion. Changing defaults at this point would cause a lot of confusion and angst for existing users, and given that there is no obvious reason for why VLC defaults would be a slam dunk win, I'm inclined to keep things as is.
