### ISSUE TITLE
Plex Auto Play Kills extension on Second+ video

### ISSUE THREAD

**Issue by miniquandt** [igrigorik/videospeed#276]
I have my own home plex server, and while im watching some of my videos, I I am watching a TV Series, After it switches from Episode 1 to Episode 2... etc, the Video Speed can not be changed. It just disappears. Some times It keeps the same speed, other times It reverts back to normal speed. 

If I restart the website then it usually comes back but alot of the times I have to restart the server because it gets confused(which is not because of your ext).

**Comment by fent** [comment]
There was a recent PR for this #270

**Comment by igrigorik** [comment]
@miniquandt can you please try installing the unpacked extension from git, and confirm if that fixes your problem?

**Comment by igrigorik** [comment]
Closing, please reopen if the problem is still there.

**Comment by miniquandt** [comment]
Question, I tried uninstalling and reinstalling (from the chrome extension site) is there a site to install from git?
