### ISSUE TITLE
Extension prevents video from playing in Google Chrome

### ISSUE THREAD

**Issue by TimKamppinen** [igrigorik/videospeed#277]
All of a sudden youtube videos and videos on other sites won't play. Disabled extension, everything works. 

Chrome is Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by igrigorik** [comment]
Yikes. Everything seems to be aok here -- just tested across bunch of sites. Did you install any other extensions recently? Could be an interop problem..

**Comment by Jlemien** [comment]
I've got the same issue. This extension was working fine until a few days ago. I discovered that videos wouldn't play. I tested disabling different extensions, and when I disabled video speed controller the videos in Chrome started working fine. I haven't added any new extensions recently. 

I'm running Version 61.0.3163.100 (Official Build) (64-bit) on Windows 10.

**Comment by igrigorik** [comment]
Thanks for the report!

Can you confirm that this behavior persists across browser restart? If so, any chance you can consult your Chrome console for any logs/exceptions that may be relevant? If you do, please check the "top" page and the extension context (in console click on dropdown that defaults to "top" and select video speed)

**Comment by Jlemien** [comment]
Confirmed: It persists across browser restart.

Here is what the Chrome console showed me: [www.youtube.com-1507423146081.log](https://github.com/igrigorik/videospeed/files/1366531/www.youtube.com-1507423146081.log)

**Comment by canarslan12** [comment]
Do you use "save speed rate" option?

Joseph <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (8 Eki 2017 03:40):


Confirmed: It persists across browser restart.

Here is what the Chrome console showed me: www.youtube.com-1507423146081.log<https://github.com/igrigorik/videospeed/files/1366531/www.youtube.com-1507423146081.log>

**Comment by Jlemien** [comment]
I normally have **Remember Playback Speed** activated. I just deactivated it, and now videos play. Is there some kind of bug related to the **Remember Playback Speed** ability?

**Comment by igrigorik** [comment]
/me facepalm

We had a (gotcha) bug earlier where if you decrease speed to 0.0 then.. surprise, the video doesn't play but it's hard to identify that. Wonder if we're hitting that here, again.

**Comment by canarslan12** [comment]
What's your preferred speed? Is it 0.00?

Ilya Grigorik <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (8 Eki 2017 07:17):


/me facepalm

We had a (gotcha) bug earlier where if you decrease speed to 0.0 then.. surprise, the video doesn't play but it's hard to identify that. Wonder if we're hitting that here, again.

**Comment by Jlemien** [comment]
Haha, my preferred speed definitely isn't 0.00. :)  I normally have the speed running somewhere between 1.20 and 2.00. As far as I am aware, I have never set the speed to 0.00.

**Comment by canarslan12** [comment]
by "Preferred Speed" I mean setting. there is a setting called `Preferred Speed (x)`

**Comment by igrigorik** [comment]
@Jlemien to confirm, was the issue here that persisted speed was 0.00?

**Comment by igrigorik** [comment]
Closing, I believe https://github.com/igrigorik/videospeed/pull/324/files should address this.
