### ISSUE TITLE
 Controller is not top-most

### ISSUE THREAD

**Issue by Synetech** [igrigorik/videospeed#278]
It would be better if instead of having the controller be inside the `html5-video-container`, have it be its sibling (figure 2). That way, the controller can be placed on top of YouTube's normal interface, and thus be less obtrusive (not in the video itself), as seen in the attached screenshot (figure 1). I'm new to Firefox extensions, but I believe it should be as simple as changing line `195` of `inject.js` from

> this.parent.insertBefore(fragment, this.parent.firstChild);

to

> this.parent.insertBefore(fragment, this.parent.parent.firstChild);

(Also, it would be great if you could make it prevent videos from auto-playing as well.)

<br />

**figure 1**
![screenshot-2017-09-15--21-37-30 - 02_08 _ 06_22 - scishow the quantum internet of the future i-w3d_nr4_e - youtube](https://user-images.githubusercontent.com/5210197/30508182-d2965d2a-9a5e-11e7-8c29-e49e5f39fb8e.png)

**figure 2**
![screenshot-2017-09-15--21-38-10 - developer tools - 01_40 _ 06_22 - scishow the quantum internet of the future i-w3d_nr4_e - youtube - https___www youtube com_embed_videoseries_list plee4zqavzhiri6tiivelfdig36wghdnqe](https://user-images.githubusercontent.com/5210197/30508181-d2739a74-9a5e-11e7-91ef-38898c74e474.png)

**Comment by igrigorik** [comment]
@Synetech thanks for the feedback!

> It would be better if instead of having the controller be inside the html5-video-container, have it be its sibling (figure 2). That way, the controller can be placed on top of YouTube's normal interface, and thus be less obtrusive (not in the video itself)..

I've experimented with this before and unfortunately that creates own set of problems: some embeds become really wonky, and controller positioning becomes really complicated (today we rely on relative positioning against the container). Also, don't forget that VSC is not limited to YouTube.. so we have to go with the safe path to provide good experience across a large number of players.

> it would be great if you could make it prevent videos from auto-playing as well

That's not something we can easily control, and there are cases where autoplay is the desired behavior — I don't think we want or need to mess with that, especially given the fact that browsers [already have policy changes](https://arstechnica.com/tech-policy/2017/09/google-chrome-block-auto-play-video/) underway to cover this.
