### ISSUE TITLE
Habilitar SOM

### ISSUE THREAD

**Issue by MARCIOLIB** [igrigorik/videospeed#279]
Por favor habilite o som para velocidade acima de 4.00

**Comment by igrigorik** [comment]
Unfortunately that's not enforced by the plugin, Chrome disables sound above 4x — that's a platform feature/limitation.

**Comment by canarslan12** [comment]
```
var video = document.getElementsByTagName("video")[0]
function advance() {
	video.currentTime+=0.10
}
var myVar = setInterval(advance, 250);
```
this code can give +0.40 speed to video but if we decrease interval time to 100, it breaks normal playing functions. if we can setInterval with 100 miliseconds `currentTime+=0.01*(speedRate-4.0)` we can do this
