### ISSUE TITLE
Does not work with Facebook videos

### ISSUE THREAD

**Issue by Wisdawn** [igrigorik/videospeed#28]
Again, thank you very much for the best Chrome extension for playback speed today in the market!

It would be great if you get the extension to work on Facebook videos. Here is an example:
https://www.facebook.com/video.php?v=839663199400851

**Comment by igrigorik** [comment]
@Wisdawn unfortunately FB appears to use Flash.. and we can't control playback video for Flash. Once FB switches to HTML5 video, the extension should automatically start working..

**Comment by Wisdawn** [comment]
Thank you for clarifying.

**Comment by jordn** [comment]
Facebook's use of flash annoyed me too so I made a Chrome extension to convert them to HTML5 videos so they can be sped up: https://github.com/jordn/facebook-html5video

NB: It's _very_ crude at this point and doesn't play nice with all videos. Pull Requests and Issues welcome.

**Comment by Wisdawn** [comment]
Thank you, Jordan. I look forwards to your extension being improved to a level you can be happy with! We do need to save time getting through some of the videos around, especially in a place like Facebook!
