### ISSUE TITLE
Extension does not work with http://www.hotstar.com/

### ISSUE THREAD

**Issue by hallidude** [igrigorik/videospeed#281]
This is an awesome extension and I use it on vimeo, netflix and a bunch of other sites. Does not seem to work on hotstar. What am I missing?

**Comment by igrigorik** [comment]
![image](https://user-images.githubusercontent.com/10652/31562760-8266a8aa-b011-11e7-91d6-19ef5a7ef63a.png)

They're still using flash on desktop. If you access it with mobile user agent, they do serve HTML5 player and controller works as expected. In short, nothing we can do here.. they need to switch to HTML5.

**Comment by hallidude** [comment]
Got it. Thanks!
