### ISSUE TITLE
Request: port to Safari?

### ISSUE THREAD

**Issue by charlottetan** [igrigorik/videospeed#282]
Thanks for considering!

**Comment by miniquandt** [comment]
If you try to speed up a video on Safari, it sounds really bad. Go and try it on YouTube. honestly I dont know if it would be worth it.

**Comment by igrigorik** [comment]
Unfortunately Safari doesn't support all the extension/platform APIs we need to support videospeed.

Maybe, one day.. :-) Thanks for your suggestion!

**Comment by boettges** [comment]
Please excuse to chime in after almost 3 years, but with Safari on macOS 11 gaining support for WebExtensions does it increase chances of a port? Thanks a lot in advance.
https://developer.apple.com/documentation/safariservices/safari_web_extensions
