### ISSUE TITLE
Error on WordPress.Tv

### ISSUE THREAD

**Issue by web2033** [igrigorik/videospeed#283]
Hi!
Videos from wordpress.tv are not working. Example:
https://wordpress.tv/2017/10/08/josh-pollock-discovering-the-wordpress-rest-api/

Console:
![2017-10-16_114815](https://user-images.githubusercontent.com/11320080/31603162-f863ac12-b267-11e7-8203-802b0e615c5c.png)

**Comment by igrigorik** [comment]
Dupe of https://github.com/igrigorik/videospeed/issues/194, closing. Unfortunately, not an easy fix..
