### ISSUE TITLE
Allow to save a default for specific sites

### ISSUE THREAD

**Issue by garyking** [igrigorik/videospeed#287]
Please allow us to set a default speed for specific sites, so for instance, on YouTube, I'd like to default all videos to 1.50x.

**Comment by canarslan12** [comment]
You can use remember last speed setting for that purpose

**Comment by garyking** [comment]
@canarslan12 Yes but that is a global setting, so if I want YouTube videos at 150%, but videos on other sites at 100%, then it won't work.

**Comment by igrigorik** [comment]
Thanks for your suggestion. No current plans to support this, but we'll add it to our wishlist. :-)

**Comment by igrigorik** [comment]
@actuallymentor not sure. My concern is that this will make the configuration very complicated for most users and my (strong) preference is to keep things simple, as it's already above most people's heads. That said, what do you have in mind?

**Comment by actuallymentor** [comment]
@igrigorik A settings section where one could make a simple list of urls patterns with speed preferences. For example:

```
# Please use this box to set custom default video speeds for certain urls
youtube.com 1.2
video.something.com 1.5
```

**Comment by garyking** [comment]
Or you could create a global setting that says "Use site-specific settings? Yes/No", and if Yes, then remember per-site speed settings, just like Chrome remembers per-site zoom settings? Then no list of sites is even necessary.

**Comment by actuallymentor** [comment]
> that would effectively create a full history log of every site the user visits, which I'd like to avoid if possible

Agreed.

Hence a list for power users would be desirable. It won't be in the way of 'regular' users but allows those who want to to customise it.

**Comment by helton** [comment]
@igrigorik 
Since this feature is important to me, I forked the project and I tried to implement it .
I use different video speeds in different sites as well and I also use different speeds in different YouTube channels.
[These are the changes](https://github.com/helton/videospeed/commit/74e6615765dd251413b964d93ad31bcc9988d1e4) I made to control the speed for each site and YouTube channels.
I still need to test it more (and probably refactor it a bit), but it's working fine with the cases I use daily.

**Comment by igrigorik** [comment]
@helton nice work. Code wise, that looks pretty good. Any thoughts on how to address https://github.com/igrigorik/videospeed/issues/287#issuecomment-385278768? It's not clear to me that there is a solution.. unless there is a way to listen for history-clear event, or some such.

**Comment by igrigorik** [comment]
@helton ah, nice find! The unfortunate part there is that we'd have to request permissions for history access, whereas all we actually need is just the removal notice. That said, that's still better than retaining history indefinitely.. Let me know what you discover.
