### ISSUE TITLE
Keyboard shortcut for fastest speed with audio

### ISSUE THREAD

**Issue by garyking** [igrigorik/videospeed#289]
Please add a keyboard shortcut, like "H", that will set the speed to 4.0x, which seems to be the fastest speed that still has audio in browsers (at least Firefox). 

There are some times when I want to speed through a video because I'm looking for something, and jumping forwards by 10 seconds might miss something.

**Comment by igrigorik** [comment]
Thanks for the suggestion. No current plans for a dedicated key for this right now — the more we add, the more the likelihood we clash with other plugins. That said, I'm planning/hoping to add scriptable keys in the future, which will allow you to customize your own behavior. Stay tuned.
