### ISSUE TITLE
Allow shortcuts to be unbound

### ISSUE THREAD

**Issue by jameszie44** [igrigorik/videospeed#291]
![screenshot 2017-11-12 at 6 04 13 pm](https://user-images.githubusercontent.com/25558848/32696740-4a7b8296-c7d4-11e7-9ae7-3dbde4b45886.png)
Hi, I've been using your extension recently and I'm really impressed! I have one suggestion to be able to set key bindings to null using the esc key.

It is a really good app and I would recommend it to anyone who watches anime!

**Comment by igrigorik** [comment]
Thanks for the suggestion. To clarify, you want this because you want to unbind the key and have it be a no-op?

**Comment by igrigorik** [comment]
Opened new bug to track this, let's continue there: https://github.com/igrigorik/videospeed/issues/347
