### ISSUE TITLE
Fullscreen YouTube is closed in Firefox once VSC loads

### ISSUE THREAD

**Issue by garyking** [igrigorik/videospeed#293]
In Firefox (possibly Chrome too):

1. Open a YouTube video
2. Launch the video in fullscreen before the rest of the page and VSC loads
3. Once VSC loads, the video exits from fullscreen.

Is it possible to NOT exit from fullscreen when VSC loads, if I'm already in fullscreen?

**Comment by igrigorik** [comment]
Can't reproduce this on Chrome; I don't maintain firefox port.
