### ISSUE TITLE
Preferred speed shortcut toggles on/off 

### ISSUE THREAD

**Issue by baz357** [igrigorik/videospeed#294]
When you press the "Preferred speed" shortcut once, that speed is set. When it is pressed again, it is being reset to 1.00.

I'd prefer that to change back to the previous behavior, where pressing it *only* caused the preferred speed to be set. Why? So I can have a script use that shortcut multiple times (don't ask ;-)) and still only ever ending up with the preferred speed.

After all, there's a "Reset speed" shortcut.

**Comment by igrigorik** [comment]
Thanks for the suggestion. If you're scripting this behavior, I'd suggest you interact with the video control directly: video.playbackSpeed = x; should do the trick.
