### ISSUE TITLE
Issue/Request Audio cuts out beyond 4x speed

### ISSUE THREAD

**Issue by ImmortalTimothy** [igrigorik/videospeed#297]
Hello, I really enjoy this Extension and use it for every single video I watch on the PC. I mostly use it to watch YouTube videos at 4x speed, however I can not go over 4x speed because at 4.10x speed and beyond the audio cuts out. I can understand most of my subscriptions at 4x speed and would like to know if it is possible to make it so the audio does not cut out after 4x speed so that I can hear what the videos are saying at greater speeds?

**Comment by igrigorik** [comment]
Unfortunately not, because the audio cutoff limit is enforced by the browser's media engine.

**Comment by canarslan12** [comment]
Can't we do this by forwarding video by 0.01 seconds? I tried it but it won't work and become slower than expected. Do you have any suggestions about it? (0.5 second forwarding was halfway working but not good)
