### ISSUE TITLE
extension does not work for me

### ISSUE THREAD

**Issue by samd123123** [igrigorik/videospeed#298]
does not work in the first video i tried

https://my.demio.com/recording/YHsnhMwN

you tell me why cos I dont enjoy getting something that then takes 2 hours to get nowhere

enough already - see if you can solve this - my chrome is updated and clean of all cookies etc

Sam

**Comment by igrigorik** [comment]
Unfortunately this is due to https://github.com/igrigorik/videospeed/issues/194.
