### ISSUE TITLE
onedrive video player

### ISSUE THREAD

**Issue by johnathan-zeng** [igrigorik/videospeed#299]
The video player does not work on videos embedded by onedrive.

**Comment by igrigorik** [comment]
Do you have a public URL that we can test against?

**Comment by johnathan-zeng** [comment]
I can upload a video if you would like!


Johnathan Zeng
University of Pennsylvania, B.S.E. 2016
zeng.johnathan@gmail.com | (440) 715.3870

**Comment by igrigorik** [comment]
Please. A public URL would be very helpful.

**Comment by ChadBailey** [comment]
No response in >2 years, closing this out. If you feel it needs to be revisited please reopen or open a new issue.
