### ISSUE TITLE
Audio mute limitation removed with Chrome 64 

### ISSUE THREAD

**Issue by canarslan12** [igrigorik/videospeed#300]
It's not an issue, I just want to share it for everyone here, you can download Chrome Beta to use it now. 

https://developers.google.com/web/updates/2017/12/chrome-63-64-media-updates
> Remove muting for extreme playbackRates
> Before Chrome 64, sound was muted when playbackRate was below 0.5 or above 4 as the quality degraded significantly. As Chrome has switched to a Waveform-Similarity-Overlap-Add (WSOLA) approach for quality degrading, sound doesn’t need to be muted anymore. It means you can play sound crazy slow and crazy fast now.

**Comment by Eisys** [comment]
Wow. Just tried it out. Cool.

**Comment by igrigorik** [comment]
Awesome! We'll remove the limitation once M64 is stable.
