### ISSUE TITLE
Shortcuts ramp to 16x with "Improved Content Fullscreen" experiment in Chrome

### ISSUE THREAD

**Issue by trevorhreed** [igrigorik/videospeed#301]
Whenever I try to speed up a video in fullscreen mode by pressing 'd' once, it quickly jumps to 16x speed.

**Comment by canarslan12** [comment]
Can you share a public URL for us to reproduce it?


Whenever I try to speed up a video in fullscreen mode by pressing 'd' once, it quickly jumps to 16x speed.

**Comment by trevorhreed** [comment]
After some investigation, I found that this extension was conflicting with an experimental Chrome feature listed in the `chrome://flags` tab under the heading `Improved Content Fullscreen`. Resetting this feature to default fixed the issue.

I don't know if this feature will eventually be enabled by default, but if you want to test it out, once that feature is enabled, the error occurs on every video platform I've tried (Netflix, YouTube, Hulu, etc.).

**Comment by igrigorik** [comment]
Thanks for tracking this down. Indeed, can confirm that there is an issue there.. need to dig deeper to understand what's going on there. 

chrome://flags/#enable-content-fullscreen

**Comment by canarslan12** [comment]
There is no Improved Content Fullscreen experiment in dev version, is it canceled experiment or only name changed?

**Comment by igrigorik** [comment]
I see it in Chrome Canary: chrome://flags/#enable-content-fullscreen

**Comment by igrigorik** [comment]
Closing: let's address this if/when this lands in Chrome.
