### ISSUE TITLE
Frame By Frame?

### ISSUE THREAD

**Issue by FrankMobo** [igrigorik/videospeed#302]
The is extension is super great! I use it to watch sports on youtube (racquetball to be specific) and the controls help me rewind or forward real easy, and especially to replay certain moves in slow mo.  One suggestion I have is to be able to see video frame by frame. Thank you!

**Comment by igrigorik** [comment]
Unfortunately the html5 player does not afford that level (frame by frame) of control. The best you can do here is change your +/- step and lower the playback speed to a very low value. Once https://github.com/igrigorik/videospeed/issues/300 lands, you'll also have more flexibility there.
