### ISSUE TITLE
Not working on TNT?

### ISSUE THREAD

**Issue by Benu-Athanasia** [igrigorik/videospeed#303]
Anyone else having the same problem? It doesn't work on TNT's website for watching TNT shows.

**Comment by canarslan12** [comment]
https://github.com/igrigorik/videospeed/issues/288#issuecomment-350574668

> I believe they're still stuck on flash; nothing we can do there. Hopefully they'll migrate to html5 video soon!

**Comment by igrigorik** [comment]
Indeed. Unfortunately nothing we can do about it on this end.. As soon as they migrate to HTML5, everything should start working.
