### ISSUE TITLE
Shift+S workaround for Vimeo needs documenting

### ISSUE THREAD

**Issue by aspiers** [igrigorik/videospeed#304]
Hi there, I'm new to this great extension, and swiftly discovered the clash described in #69.  However I couldn't see any workaround documented, so I had to go digging in the GitHub issues to find it.  I'll submit a PR to fix that.

**Comment by aspiers** [comment]
Hrm, I've just noticed that `X` seems to clash with a Vimeo Easter Egg (at least that's what I think it is?!) where pressing `X` offers a choice of different effects to apply to the video.  Does anyone else see that?  If so I guess we need to document `Shift+X` too.

**Comment by igrigorik** [comment]
Ha, nice find! `X` works here too — neat-o.
