### ISSUE TITLE
Shift+S/D workaround does not work with YouTube 360 degree videos

### ISSUE THREAD

**Issue by aspiers** [igrigorik/videospeed#306]
For spherical 360 degree videos, YouTube offers keyboard shortcuts `S` and `D` for panning down and right respectively.  Unlike with #69's workaround for `S` on Vimeo, `Shift+S` and `Shift+D` simultaneously pan and affect the playback speed.

**Comment by igrigorik** [comment]
That's a tricky one, not sure we can "fix" this.. short of changing default shortcuts, but that would be very painful for all existing users, and it would only create more conflicts with other edge cases. 

Any suggestions?

**Comment by aspiers** [comment]
Well I'm wondering why the Shift trick works for Vimeo but not YouTube - wonder if that's worth investigating?

Other than that I don't have suggestions I'm afraid :-)  Totally agree with you about changing the defaults.

**Comment by igrigorik** [comment]
It's logic on the YT side: they intercept both keys (e.g. for those that have caps lock enabled :)), whereas Vimeo does not. As such, I'm inclined to resolve this as a wontfix.

**Comment by aspiers** [comment]
Ah, good spot :-/  Maybe it's worth at least documenting before closing, though.

**Comment by igrigorik** [comment]
https://github.com/igrigorik/videospeed/commit/7079bbf718f4546d68258d4753cd513eb296db58, closing.
