### ISSUE TITLE
Don't work in https://pan.baidu.com

### ISSUE THREAD

**Issue by ML000** [igrigorik/videospeed#307]
https://pan.baidu.com
There is no control bar shown in the video from https://pan.baidu.com. 
The web is most popular cloud disk in China. 
Please fix it or give some instructions. Thanks.

<img width="1343" alt="2018-01-22 12 12 47" src="https://user-images.githubusercontent.com/26579199/35196147-10257392-ff09-11e7-92ad-9fdb7630c812.png">

**Comment by igrigorik** [comment]
Do you have a link to a public page with a video that I can test?

**Comment by igrigorik** [comment]
Can't find any videos to test. Closing, please reopen if you can share a link.
