### ISSUE TITLE
Cannot read property 'body' of null

### ISSUE THREAD

**Issue by wesbos** [igrigorik/videospeed#309]
Getting this error on Chrome Canary. Any idea why it would happen?

I can get it on wesbos.com and localhost as well as many other sites - but not every site. 

![](http://wes.io/pBoA/content)

**Comment by wesbos** [comment]
I can also confirm it happens in stable Chrome

**Comment by igrigorik** [comment]
Hey Wes. It looks like your site is powered by WordPress.. Are you using Videopress to play the videos? If so, there is an outstanding issue here: https://github.com/igrigorik/videospeed/issues/194

**Comment by wesbos** [comment]
Hey! Thanks for the reply. Both sites don’t have videos on them. Only one of them is Wordpress as well. Do you see the error when visiting my site?

**Comment by igrigorik** [comment]
Ah, doh, yes.. sorry misdiagnosed this. Looks like we have a null document getting passed into:

https://github.com/igrigorik/videospeed/blob/master/inject.js#L205-L210

**Comment by wesbos** [comment]
Very bizarre - do you think I could just return from that function if there is no document? It's working totally fine on all pages with videos

**Comment by igrigorik** [comment]
I believe this should be fixed in master. If you're willing, try the unpacked extension? :)

**Comment by wesbos** [comment]
That fixed it! Thank you :D

**Comment by berekuk** [comment]
@igrigorik, do you plan to release this fix to chrome web store any time soon? It doesn't break anything, but it's quite annoying when I'm trying to debug my own code.

**Comment by igrigorik** [comment]
@berekuk I'll push a new version live this week — thanks for the nudge. Need to triage a few new issues, but hopefully that won't take long.

**Comment by wesbos** [comment]
please do - I've had to keep disabling the extension when I'm working on my own code

**Comment by canarslan12** [comment]
I cannot reproduce this one @igrigorik
