### ISSUE TITLE
Off by 5%

### ISSUE THREAD

**Issue by ElijahLynn** [igrigorik/videospeed#31]
Every now and then the speed difference will be off by 5% vs 10%. This has only happened on YouTube videos so far. When I figure out how to reproduce I will post here. Until then just consider this a stub.

**Comment by igrigorik** [comment]
Huh, interesting.. never seen that. What is your increment step set to: 0.1 or 0.05? Wondering if there is a race somewhere in the initialization logic.

**Comment by ElijahLynn** [comment]
It is the default of 0.10. I am sure to reproduce it soon, I do press the buttons quite fast when I am trying to narrow in on a frame section for analysis.

**Comment by truth1ness** [comment]
Hi, my speed control is stuck at 5% intervals and I can't get it back to 10's and play it at normal speed. How do I reset this?

**Comment by ElijahLynn** [comment]
@truth1ness One thing you can do is go into the options and set the 'speed change step' to 0.05. Then refresh video and get it back to a .10 increment and/or 1x. Then go back to the settings and set it back to 0.1. 

If you are using YouTube you can just click the gear and set the speed to something other than 'normal' then set it back to 'normal'.

Thanks for your report. Hopefully we can fix this soon.

**Comment by igrigorik** [comment]
Closing, please reopen if/when this issue reappears.
