### ISSUE TITLE
videospeed puts every video on pause

### ISSUE THREAD

**Issue by stivens13** [igrigorik/videospeed#314]
When the plugin is active, every single video is paused and cannot playback. 

Macbook 2016 10.13.13, Chrome 64.0.3282.167.

**Comment by igrigorik** [comment]
Can you share an example URL? I can't reproduce this.

**Comment by stivens13** [comment]
@igrigorik It happened virtually to every video in Chrome. After I reinstalled it, playback is back to norm. Not sure what happened. Will updated if issue recovers.

**Comment by igrigorik** [comment]
Glad to hear it's "fixed". Feel free to reopen if it reoccurs.
