### ISSUE TITLE
Change default shortcut for "decrease speed" - incompatible with YouTube TV 

### ISSUE THREAD

**Issue by glaucocustodio** [igrigorik/videospeed#318]
http://youtube.com/tv has "S" as its default search shortcut, making it incompatible with the "decrease speed" shortcut.

What do you think about changing the default shortcut for "A" or any other?

**Comment by igrigorik** [comment]
Yikes. Thanks for flagging this. This is unfortunate.. Remapping the defaults will cause a lot of pain and "it's broken" messages; need to think carefully on how to proceed here.

**Comment by samescolas** [comment]
Hello, maybe I'm missing something obvious but since "A" isn't currently mapped to anything, couldn't you add a second keyCode for decreasing speed (line 252/settings object near top)?

**Comment by igrigorik** [comment]
@samescolas you can remap your default key in extension's options pane. The issue here isn't that we can't add additional shortcuts, it's that they inevitably clash with something else.

**Comment by igrigorik** [comment]
https://github.com/igrigorik/videospeed/commit/7079bbf718f4546d68258d4753cd513eb296db58. Closing with no action, but we can revisit in the future if there is more demand for this.
