### ISSUE TITLE
Skip to end of current 'video' (YouTube ad skipper)

### ISSUE THREAD

**Issue by samescolas** [igrigorik/videospeed#319]
Hey, I've been using your extension for a while now and it's awesome (THANK YOU). I use [my own fork](https://github.com/samescolas/videospeed) that has a builtin key for bypassing pesky YouTube ads. Are you against the idea of incorporating something like this?

**Comment by canarslan12** [comment]
Since this extension is responsible for managing video speed in better way, it's out of purpose

**Comment by igrigorik** [comment]
Agreed, that's a non-goal.
