### ISSUE TITLE
Allow option to show overlay while increasing/decreasing in fullscreen mode

### ISSUE THREAD

**Issue by ElijahLynn** [igrigorik/videospeed#32]
When I watch a YouTube at fullscreen, increasing/decreasing doesn't cause the overlay to appear. Instinctively I thought we should have it show but I can see the case where some may not want that. Would a PR to set this to show via an option be okay?

**Comment by igrigorik** [comment]
Which version of the extension are you using? Fullscreen mode does work for me: I see the controls, and controls are hidden whenever the other controls disappear (title bar, etc); you may need to move the mouse to see them show up.

As a general principle: the speed controls should be visible whenever the title + other controls are visible, and if those are hidden by the player, then we should do the same.

**Comment by ElijahLynn** [comment]
Yes, they do show when the mouse is moved in fullscreen, that works perfect. It is when the title and overlays fade out that these don't show any more either. Then a toggle doesn't bring the speed overlay back and I have to move the mouse to get it to show.

Thinking about it, for my particular use case, if #33 were implemented then I don't think I would need this much as I mainly use it to show me getting back to 1x.

**Comment by ElijahLynn** [comment]
Let's close this for now, I would rather not add bloat if #33 will do it for me. If someone else has a need for this they can always reopen.
