### ISSUE TITLE
Buttons unclickable on my canvas account, but not my classmate's

### ISSUE THREAD

**Issue by Kmb614** [igrigorik/videospeed#322]
Canvas does not have a video speed controller option, so we were recommended to download this extension. It works for everyone else's account, but will not function on my computer. However, it works on other sites, such as Blackboard. I contacted canvas but they said this is beyond their control and to contact the plug in people.

**Comment by igrigorik** [comment]
If it works for others, this sounds like an issue with your device not the extension. A few routes to investigate: check if any other extensions are active and could be conflicting, remove and reinstall the extension, reboot your device between uninstall + reinstall, try running the extension in a clean Chrome profile (e.g. Incognito).
