### ISSUE TITLE
motor trend on demand does not work.

### ISSUE THREAD

**Issue by stereophonic007** [igrigorik/videospeed#323]
Using Chrome. is this a bug or am i missing something?
https://www.motortrendondemand.com

**Comment by igrigorik** [comment]
Seems to be A-OK here.

![image](https://user-images.githubusercontent.com/10652/38177119-3108a24a-35b0-11e8-9715-24c8d8ebd423.png)

There may be a conflict with some other extensions on your machine? Check your console and/or try in incognito (with extension enabled there).
