### ISSUE TITLE
Controls no longer show or work on local videos (and some other sites) v0.5.1

### ISSUE THREAD

**Issue by mariusi7** [igrigorik/videospeed#326]
I guess there was an update since tomorow, but the controls don't show anymore on local videos for me. Settings are ok, "Allow access to file URLs" is ON, nothing changed from my part since yesterday when it still worked. Other users complain about certain websites (on the Chrome page).

**Comment by mariusi7** [comment]
Chrome version: 65.0.3325.181
 (unchanged since last week)
Oddly, I tried installing 1.5.0 in dev mode but it still doesn't work (?). I'll keep trying

**Comment by mariusi7** [comment]
Version 0.49, id cjfjblcfekkjldlnkccaafonahammakg, commit 194fcc107680f8d84ca75749c375c152f991eedd works.

**Comment by mariusi7** [comment]
@igrigorik Please have a look. Thx!

**Comment by mariusi7** [comment]
@canarslan12 So does it work for you (in latest Chrome version) for local files or not ?
It's not just me, I saw a couple of other users mentioning problems in the last 6h ( https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk/support?hl=en )

**Comment by canarslan12** [comment]
can you try this fixed version?

**Comment by mariusi7** [comment]
I confirm that your version with commit dd7d976e90af60e378aa68b712448837594b6193 works again for my local files in latest Chrome version.

**Comment by apurplecaboose** [comment]
the extension still does not work for me on local files for some reason...

**Comment by mariusi7** [comment]
@apurplecaboose did you install the unpacked extension from a downloaded file videospeed-dd7d976e90af60e378aa68b712448837594b6193.zip ? It shows at 0.5.0 (ID: foacgnafkoecldehmhofegjcldbkgjph)
You can also check by opening Developer Tools, tab Sources, subtab Content Scripts and line 194 needs to look like here: https://i.imgur.com/lERmyfr.png

**Comment by alon91** [comment]
Could you help with guidance on steps that we need to follow to download the fixed version? Haven't been able to figure it out on my own. Many thanks in advance!

**Comment by mariusi7** [comment]
@alon91 go to https://github.com/igrigorik/videospeed/tree/dd7d976e90af60e378aa68b712448837594b6193 , press Clone or Download, choose Download ZIP. DTo install either search on google for pics on how or: Unzip it, open Addons page in Chrome, disable the existing CSV addon, then enable Developer Mode, Load Unpacked and select the unzipped folder.

**Comment by igrigorik** [comment]
Another report (need to validate) from the Chrome store.. 

> The control bar for Mp4 local videos still showed up, but not for audio files. Still working about a week ago.

**Comment by igrigorik** [comment]
Testing locally, everything seems to be a-ok with latest (soon to be released) version. Closing.

**Comment by mariusi7** [comment]
Is this fix not included in 0.5.2 ? It still doesn't work for local videos.
