### ISSUE TITLE
Pin Option to keep visible

### ISSUE THREAD

**Issue by bculley** [igrigorik/videospeed#330]
Can we have a pin option to pin to the screen so it doesn't disappear with the other video controls?  When I watch long videos I like to skip and speed up boring parts, and I have to expand the control again to use the buttons.   I'd like an option to have the controls remain expanded.

**Comment by canarslan12** [comment]
why do not you use keyboard shortcuts?

**Comment by igrigorik** [comment]
@bculley good news, this already exists! Hit "v" key to toggle pin / hide the controller.
