### ISSUE TITLE
Not working on Streamplay

### ISSUE THREAD

**Issue by CruaverVoidDrake** [igrigorik/videospeed#338]
I have been using your plugin for quite sometime and I absolutely love it. Unfortunately it's no longer working on certain videos. Namely it is not showing on streamplay consistently.

**Comment by igrigorik** [comment]
Can you provide a couple of example URLs where it's not working?

**Comment by CruaverVoidDrake** [comment]
Yes I can from a video series I was just watching: 
http://www.ondarewatch.com/gotham/season/4/episode/19

Any working link from streamplay has a questionable chance of working. Sometimes it works, sometimes it doesn't. I would guess it's some sort of timing issue.

**Comment by igrigorik** [comment]
Hmm, it's hard for me to tell what's going on there because half my clicks and interactions are intercepted by adware / malware ads. Unfortunately I think this is a wontfix.
