### ISSUE TITLE
Console error showing up on all origins on Chrome 68

### ISSUE THREAD

**Issue by dsifford** [igrigorik/videospeed#339]
Hi there,

Just noticed this issue this evening, so this very well may also be occurring in earlier Chrome builds.

### The gist

On any page load, regardless of the origin, path, or whether or not the page has an HTML5 video element, the following error shows up in the console:

```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

### Details

When the filename of the above error message is clicked (on the righthand side of the console), the error always displays like this (example from stackoverflow.com):

![image](https://user-images.githubusercontent.com/5240018/40462862-db54e51c-5edf-11e8-9fea-f5773d8a3b5c.png)

I disabled all other extensions and confirmed that the issue stems from the videospeed extension.

#### Environment

Google Chrome | 68.0.3432.3 (Official Build) dev (64-bit)
-- | --
Revision | `5aacd4d4350de37f394edd3095576d2bc7daf56c-refs/branch-heads/3432@{#6}`
OS | Linux
JavaScript | V8 6.8.228
Flash | 30.0.0.94 /home/dsifford/.config/google-chrome-unstable/PepperFlash/30.0.0.94/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3432.3 Safari/537.36
Command Line | /opt/google/chrome-unstable/google-chrome-unstable --flag-switches-begin --enable-devtools-experiments --enable-fast-unload --enable-features=PictureInPicture --flag-switches-end

---

Sorry I couldn't be more helpful. Not familiar with extension APIs at all. Hope the above information helps!

**Comment by igrigorik** [comment]
Thanks for the detailed report! The complication here is that.. I can't seem to reproduce it. Hmm..

**Comment by dsifford** [comment]
Hm... well shoot!

I just tried again and made sure the only extension that was active was VSC and I'm able to reproduce it regularly.

Any other info that you might need to dial in on this more?

```
$ uname -a
Linux archlinux 4.16.10-1-ARCH #1 SMP PREEMPT Mon May 21 07:57:23 UTC 2018 x86_64 GNU/Linux
```

**Comment by igrigorik** [comment]
Can you reproduce the error on a stable or canary build? I don't think this error has anything to do with the extension itself.. We're not using any special here, videospeed is a fairly vanilla contentscript extension.

**Comment by dsifford** [comment]
I can install stable and try if that would be helpful for you. Canary isn't available for linux systems (as I'm sure you're already aware).

Were you able to try on a canary build? If you can't reproduce there, then perhaps in a few days the dev channel will have the issue resolved and we can call this a wash.

---

Here's a potentially ignorant question, so please forgive me in advance: 

Is there some particular reason why you're using `chrome.runtime.sendMessage` [here](https://github.com/igrigorik/videospeed/blob/1718872d98c97429d9543b8ef24ec4f405fca39b/inject.js#L1) instead of something else perhaps better suited for business logic implementation like [connect](https://developer.chrome.com/apps/runtime#method-connect)? It doesn't appear that you're actually using the message for any reason being that you're sending an empty object.

I think the error I'm getting specifically is because we're sending a message to chrome runtime without specifying a receiving end or becuase the receiving end of the extension isn't ready just yet.

**Comment by igrigorik** [comment]
Don't see the error on OSX Canary either. Give stable a try.. :-)

> I think the error I'm getting specifically is because we're sending a message to chrome runtime without specifying a receiving end or becuase the receiving end of the extension isn't ready just yet.

That could be. AFAIK, the current pattern is still fine and I'm not aware of any guidance to migrate away from it, but could be wrong.. Searching for this error doesn't yield much in terms of useful guidance so far. One old discussion I found is @ https://bugs.chromium.org/p/chromium/issues/detail?id=592478.

**Comment by dsifford** [comment]
@igrigorik This appears to have been fixed in `Chrome 68.0.3440.7 Rev: 9bbd2d0687bd83181f22ac13565501690ee5b4c7-refs/branch-heads/3440@{#16}`

Sorry for the noise! Must have been an issue with that specific dev version of chrome. Thanks for your kind help nevertheless :smile:

**Comment by igrigorik** [comment]
Yay! Glad to hear.

**Comment by dsifford** [comment]
It's back! :face_with_head_bandage: 

This time, there's a touch more info in the error that shows up on the doctype...

![image](https://user-images.githubusercontent.com/5240018/40797482-4c9fd06e-64d6-11e8-80ab-a555ae3e5a6d.png)

Doesn't appear that the other messages are at all related to this extension though.

One other difference: The extension still is working as far as I can tell. Last time the errors that it produced were fatal and caused the entire extension to brick..

Just throwing this out there. I'll continue to watch this for now to see if any other oddities show up.

**Comment by a-eid** [comment]
facing the same issue with the latest version of chrome canary Version 72.0.3619.0 (Official Build) canary (64-bit).

**Comment by QVMaster** [comment]
I found that related to IDM Integration Module extension on Chrome Version 71.0.3578.98 (Official Build) (64-bit) on windows 10.

**Comment by seanjams** [comment]
Facing the same error, just started happening today. I definitely didn't manually update chrome or this extension, just noticed it in my console all of the sudden when I rebooted this morning. When I disable the extension in the extension manager, the error disappears. When I enable it and refresh, it reappears. The error is shown for every origin.

Chrome Version: 71.0.3578.98 (Official Build) (64-bit)

Error Screenshot (no extra info like @dsifford 's post)
![screen shot 2019-01-10 at 2 47 49 pm](https://user-images.githubusercontent.com/24235811/51002345-da101a00-14e7-11e9-8f42-bd9decac83f8.png)

But...on the bright side...everything still works!

**Comment by dalovar** [comment]
Facing the same error since today, happens in all pages as well. I don't use videospeed, but I found that in my case it's related to the extension called Javascript Injector.

**Comment by abdulrahman-khankan** [comment]
@igrigorik it's back.

**Comment by tommai78101** [comment]
It has to do with `chrome.runtime.onMessage.addListener()` requiring all extensions to return `Promise` right now.

It may have to do with the "sendResponse" being removed from the W3C draft specifications back in 2018. But, this is the only known hint I have. I don't have any conclusive proof that this is the primary reason.

If I'm incorrect, please let me know, because I'm affected as a browser extension developer myself.

**Comment by stevehanson** [comment]
I just noticed this today on Chrome 72.

**Comment by atav32** [comment]
Anyone try messing with the [`externally_connectable`](https://developer.chrome.com/extensions/manifest/externally_connectable)? I'm not sure if it's an actually fix or if I'm coincidentally not seeing the error anymore.

**Comment by kevincai79** [comment]
Same issue. I found out my problem was caused by the extension hunter.io, the error message disappeared once I disabled that extension.

**Comment by LeoEspinoza12** [comment]
Same here. Fixed it by disabling extension. This should be fixed soon.

**Comment by stevehanson** [comment]
I just looked into this a little more and see that the [content script](https://github.com/igrigorik/videospeed/blob/master/inject.js) is wrapped with:

```javascript
chrome.runtime.sendMessage({}, function(response) {
  // code here
});
```

I also noticed that the Hunter.io extension that @kevincai79 mentioned also [does the same thing](https://github.com/hunter-io/browser-extension/blob/master/src/content_script/js/websites-source.coffee#L81). 

I don't see anywhere in the codebase where the message is being listened for (eg. `onMessage` or `onMessageExternal`), which I think is why we're seeing the console error "Could not establish connection. Receiving end does not exist".

I was able to clone this repo, load the extension unpacked into Chrome from chrome://extensions and just delete the sendMessage bit that wraps the rest of the code in `options.js`, and I don't see the error anymore. Not sure if that's a realistic approach since I'm not sure why it was there in the first place.

**Comment by vrgomes** [comment]
I'm also having this issue. Anyone has a solution or is a Chromium bug?

Greetings.

**Comment by ddehghan** [comment]
I have found a solution for our case. It was a timing issues of not having a listener for the connect api call. This was not an issue before 71 or 72. It is something new. 

https://stackoverflow.com/questions/54181734/chrome-extension-message-passing-unchecked-runtime-lasterror-could-not-establi/54686484#54686484

**Comment by alexilyaev** [comment]
@igrigorik @dsifford 
I think this issue should be re re-opened.  
Seeing this on any website once I've updated to chrome 72.

Disappears when disabling this extension.

**Comment by tommai78101** [comment]
@ddehghan 

Does that mean there are other API changes for Chrome 72? Or that is just the only one?

**Comment by igrigorik** [comment]
Thanks for tracking this down guys! Per @stevehanson's suggestion, pushed an update to remove the wrapper. You can try installing the latest version from source as unpacked extension, if you want to confirm and validate that the problem is fixed.

**Comment by ITJoePC** [comment]
"Unchecked runtime.lastError: The message port closed before a response was received."
"Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist."

Think it might be a firewall issue, since I'm running this from an intranet.  I could try this from an outside connection later.

Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by SimonIMG** [comment]
Confirming that I have this issue too. I see #429 states there is a fix coming soon. Will test out when the fix is released.

**Comment by vrgomes** [comment]
Hi, where is the code for the fix?

Greetings.

**Comment by FGrante** [comment]
I [updated](https://github.com/hunter-io/browser-extension/commit/d354ef7b6bc651f43f8490821cdb5c19f720de65) Hunter extension to no longer create this error. It should no longer appear with the version 1.17.0+ (but could be triggered by other extensions).

Thank you everyone for looking into it!

**Comment by kenseii** [comment]
> Same issue. I found out my problem was caused by the extension hunter.io, the error message disappeared once I disabled that extension.

In my case it was the udacity extension

**Comment by knoxcard** [comment]
You must disable all third party Chrome extensions, one of them if causing this error to appear.
