### ISSUE TITLE
Not working with the WSJ podcast

### ISSUE THREAD

**Issue by iconoclasthero** [igrigorik/videospeed#341]
The Video Speed Controller indicator comes up for the WSJ online podcast player but it does not actually do anything.  E.g. [this podcast from today.](https://www.wsj.com/podcasts/redstone-vs-moonves-battling-in-court-over-cbs/FBA5BA2C-3CCF-435B-A8DA-9B09A7E21F1E.html)

**Comment by canarslan12** [comment]
because it's not an video, it's audio.
#158

**Comment by igrigorik** [comment]
Yes, there is some extra work to be done to make it audio compatible. 

Closing, let's continue in #158.
