### ISSUE TITLE
Feature Request: Preferred Resolution

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#342]
This may be beyond the scope of this extension, but I believe setting a preferred resolution would be a fantastic addition.

### Reason

Typically video websites do an OK job at picking the highest resolution that can be streamed by your connection, but if I'm say using my chromebook that doesn't even quite have a 720p resolution sometimes that means it will be trying to playback at 4k which just makes no sense.  This causes the video to stutter due to the unnecessary extra load on the CPU as well as heat up of course. The same is also true for 60fps content, but I use https://github.com/erkserkserks/h264ify for that.

**Comment by igrigorik** [comment]
Unfortunately this is not something we can control from within the extension. [MSE API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) does enable providers to provide and stitch together various quality streams, but that's a low level API that we don't have access to; implementation of this logic is very player specific.

Thanks for the suggestion!
