### ISSUE TITLE
very frustrating-- works sometimes, then not, controls have been all messed up as well

### ISSUE THREAD

**Issue by emilyrose777** [igrigorik/videospeed#343]
Hello,

This feature worked PERFECTLY for about a year, then suddenly never turns on automatically.

Then, the controls were reset, so I changed them back to the shortcuts I wanted, and everything was completely messed up in that directives resulted in completely unrelated things.

HELP PLEASE!

**Comment by igrigorik** [comment]
Sounds like there may have been a bug with the extension update? The best thing I can recommend here is to go to "more tools > extensions", uninstall the extension, and then go reinstall it from the chrome store again.
