### ISSUE TITLE
On YouTube "S" key doesn't work as a shortcut

### ISSUE THREAD

**Issue by GustyEagle** [igrigorik/videospeed#344]
This may be related to https://github.com/igrigorik/videospeed/issues/318, though I don't know about youtube tv. 

![screen shot 2018-06-13 at 9 15 37 pm](https://user-images.githubusercontent.com/23506224/41391381-2d9ee942-6f4f-11e8-8f9a-00e7589f6767.png)

if screenshot doesn't work text :
 www.youtube.com says
Invalid URL! (

**Comment by igrigorik** [comment]
I can't reproduce this. Are you testing this on youtube.com/tv? Alternatively, perhaps you have other extensions running on the page that are conflicting?

**Comment by GustyEagle** [comment]
(un)fortunately it does not happen often, but on trying it with youtube.com/tv, they seem like the same issue

**Comment by Steve-357** [comment]
This is happening to me pretty regularly on YouTube (not YouTube tv), on a variety of videos and channels. Windows 10 Pro, 64-bit, latest release of Chrome. I do use Diigo, and the "capture" button for Diigo appears close enough to the speed control that I can't adjust the speed from there.  "R" shortcut is also not responsive.

**Comment by LiTO773** [comment]
I know this conversation is a bit old but I used to get the exact same message.

I found out that the problem was the Imagus extension, and it will stop if you change the S shortcut in Imagus to another key.

Hope this helps someone else that is having the same issue.

**Comment by shekharP1536** [comment]
> I know this conversation is a bit old but I used to get the exact same message.
> 
> I found out that the problem was the Imagus extension, and it will stop if you change the S shortcut in Imagus to another key.
> 
> Hope this helps someone else that is having the same issue.

Ohh I see i also use imagus extension Really worked
