### ISSUE TITLE
Allow user to define custom shortcuts

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/videospeed#347]
Currently we provide a predefined list of shortcuts, with each additional shortcut requiring an explicit code update as well as definition of a default key. This does not scale and causes shortcut conflicts. Instead of using a frozen list of actions, against which you can assign a hotkey..

Refactor / implement a mechanism where the user can add own shortcuts in the options panel:

- Click "add shortcut" presents:
  - Input box for the shortcut key
  - Dropdown of allowed actions — e.g. play, pause, seek, ratechange
    - Selecting some actions would inject another "value" box — e.g. value for ratechange.
- There should be a "x" / remove action option to remove assignments.

We can still ship a default set of shortcuts, matching what we have today, but this allows the user to then define as many shortcuts as they want with as many value variations as they want.

**Comment by canarslan12** [comment]
https://github.com/canarslan12/videospeed/tree/testing

I started to work on it and created tc.settings.keyBindings array which contains `whattodo(rewind etc.)-keyCode-value-force` as an arrays for each key bindings.
Code is unexplained and not-cleaned, I will keep working probably next week. If someone has any suggestions, I can add it before finishing it. 
force field is for trying to stop default function of button such as space pausing in twitch.

**Comment by igrigorik** [comment]
Resolved via #350.
