### ISSUE TITLE
Clicking the controller (to jump forward, increase speed, etc.) pauses/plays the video

### ISSUE THREAD

**Issue by justinwong098** [igrigorik/videospeed#348]
Whenever I use the on-screen controller to change the speed or jump forward/backward, my clicks perform the desired speed change/jump, but it also pauses/plays the video. This makes the controller impractical to use, compared to keyboard shortcuts.

**Comment by canarslan12** [comment]
can you share a public url to reproduce? because I don't have this issue.

**Comment by justinwong098** [comment]
https://onlinemeded.org/cardiology/valvular-disease

Perhaps it's because the above site uses JW Player?

**Comment by canarslan12** [comment]
Yes, it is because of JW Player but I think we can't fix it easily. Maybe JW Player can fix it, can you ask them?

**Comment by justinwong098** [comment]
JW Player is a company that develops video player software. I highly doubt they would change their code base just to accommodate a chrome extension. If the bug can't be fixed, then it's fine; the keyboard shortcuts still work.

Interestingly, when I click the current speed number, and drag the controller around, the video doesn't pause/play. But if I click the speed number and don't drag the controller around, the video does pause/play.
Similarly, if I try to click the speed up button, and drag my mouse slightly within the button, then I can get the speed change without pausing/playing the video. Clicking without dragging results in the pause/play bug again.

**Comment by igrigorik** [comment]
@justinwong098 thanks for reporting this. I agree with @canarslan12, this is not an issue we can resolve in this extension, this behavior is an artifact of how JWPlayer is implemented.
