### ISSUE TITLE
[Feature Requests] A few features I'd like to see implemented

### ISSUE THREAD

**Issue by enzog1** [igrigorik/videospeed#352]
Thank you for making this extension, it's been immensely useful!
I'd like to make some feature requests:
>-Add option to use Alt, Ctrl, Shift modifier key combinations as shortcut hotkeys: eg. pressing Shift + Z combo to increase speed
>-Add option to already start playing videos at preferred speed by default eg. load video at preferred speed without the need to press a shortcut key
>-Add functionality to pause videos with shortcut key

**Comment by igrigorik** [comment]
Latest release should address custom keys and pause functionality. :)
