### ISSUE TITLE
Annoying. always opens at 1.30x speed 

### ISSUE THREAD

**Issue by rls-vault** [igrigorik/videospeed#353]
Hi guys.
    I did love the app, but......
I have repeatedly set the default to preferred speed top be 1.0x , and saved it.
However every time a video starts the speed controls come up at 1.30x speed. and I have to change it down , every time.  And when I say every time I mean every time.   :-(
So far I have:
- un-installed the app, and reinstalled it.
- set and reset the default to 1.0x. 
- Stopped all my chrome browsers sessions and restarted them clean.

no joy, in fact much sadness and annoyance.

I hope to hear from you with a treatment soonish or I will have no choice but to permanently dump the app (which would be a pity)

Thanks for the great tool.    'Lets make Videospeed great again'
RL

**Comment by canarslan12** [comment]
I think you should just disable `Remember Playback Speed` setting
