### ISSUE TITLE
Hotkeys doesn't stick and interfers with some websites chat

### ISSUE THREAD

**Issue by Wolferey** [igrigorik/videospeed#355]
So I started noticing that every time I typed on certain websites with chat (giantbomb, youtube etc.) that it would register the hotkeys. I checked the settings and there is no way to disable hotkeys, so I figured I would just put them on the numpad so I don't accidentally hit them while chatting, but while it does say my hotkeys are numpad numbers in the settings, it doesn't seem to stick and it still registers the default ones. (Edit: Hotkeys not changing seems to be because it requires a page refresh, even when you have them saved?)

**Comment by igrigorik** [comment]
I believe this should be resolved with latest version. If this is still an issue, please reopen.
