### ISSUE TITLE
Doesn't Work on Food Network

### ISSUE THREAD

**Issue by Benu-Athanasia** [igrigorik/videospeed#356]
Anyone know how I can get this to work on the Food Network website?

**Comment by igrigorik** [comment]
Seems to be working a-OK on this end.. 

![image](https://user-images.githubusercontent.com/10652/42416216-6ef6e288-821d-11e8-9ed8-890f7dbc94cb.png)

Do you have an example URL where it doesn't work?

**Comment by Benu-Athanasia** [comment]
I can't get it to work on any episodes on the site. 
![untitled](https://user-images.githubusercontent.com/31640784/42422579-b0873452-82b6-11e8-9c12-5d56ac42dc20.png)

**Comment by igrigorik** [comment]
Hmm, interesting.. Yeah, appears like something's not right there. 

Example URL: http://watch.foodnetwork.com/show/nf/star-salvation-600s-masters-16x9-site-evergreen-masters/5122123/breakfast-sandwich-salvation/

Need to investigate why that's not being picked up.

**Comment by arielallon** [comment]
Could it be related to the video being in an iFrame?

<img width="1023" alt="screen shot 2018-10-10 at 9 50 26 pm" src="https://user-images.githubusercontent.com/1356396/46777823-959d9400-ccd6-11e8-97d8-60fe389154d7.png">
