### ISSUE TITLE
Make this an activeTab extension

### ISSUE THREAD

**Issue by kamalmarhubi** [igrigorik/videospeed#360]
Instead of requiring permissions for all sites, this could work really well as an [activeTab extension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#activeTab_permission). There would be a need to hit a hot key to enable the extension for the tab with video, after that it will work as it does now. This would get rid of any security or privacy concerns someone might have, and additionally improve performance by not injecting the script in every page.

(Originally filed against the Firefox version: https://github.com/codebicycle/videospeed/issues/32)

**Comment by kamalmarhubi** [comment]
If you think you'd make a release with that change, I'd be willing to take a crack at the implementation.

**Comment by igrigorik** [comment]
I'm inclined to keep things as is. 

 - I've not heard any strong pushback to current setup
 - The code is open source and anyone can audit if they have security concerns
 - This would be a big "breaking" UX change for current users

**Comment by kamalmarhubi** [comment]
Closing this out, thanks for your response.

**Comment by frankclaassens** [comment]
@kamalmarhubi see followup here: https://github.com/igrigorik/videospeed/issues/522
