### ISSUE TITLE
Speed adjustment on Lynda.com not working (time skip works)

### ISSUE THREAD

**Issue by ElijahLynn** [igrigorik/videospeed#367]
Pressing the hot key to speed up or down gives the console error:
> Unchecked runtime.lastError while running storage.set: This request exceeds the MAX_WRITE_OPERATIONS_PER_MINUTE quota.
    at tc.videoController.<anonymous> (<URL>)

Pressing the `+` or `-` of the overlay don't trigger anything, and nothing happens. Lynda.com video player does have it's own speed adjustment on the bottom right of their player.

![image](https://user-images.githubusercontent.com/1504756/43668525-6cf75966-974b-11e8-9cd1-4dae400cf81f.png)

semi-related: #180

**Comment by ElijahLynn** [comment]
The skip time buttons on the overlay do work, so it is partially working.

**Comment by igrigorik** [comment]
Same issue as https://github.com/igrigorik/videospeed/issues/391. :(
