### ISSUE TITLE
Business Collaboration Opportunity

### ISSUE THREAD

**Issue by noahschochet** [igrigorik/videospeed#369]
Hello,
I am a student entrepreneur from Princeton University. I have an idea for a potential business collaboration opportunity that I would like to discuss with the creators of this extension. I have been a loyal user of Videospeed controller for a while now, and I honestly love it! It is amazing. Please contact me at noahas@princeton.edu to discuss this idea further.

Regards,
Noah Schochet

**Comment by igrigorik** [comment]
Hi Noah. Thanks, glad you've found it useful!
No plans to turn the extension into a commercial product on this end. :)

**Comment by noahschochet** [comment]
Hello,
This is not a commercial product, but more of a helpful feature that your
users would find extremely helpful!
