### ISSUE TITLE
auto-hide in netflix?

### ISSUE THREAD

**Issue by bundy23** [igrigorik/videospeed#37]
Awesome extension. i was just wondering if there was any way to make it auto-hide while watching netflix as it's quite distracting sitting in the top corner all the time.

**Comment by igrigorik** [comment]
Should be possible, the challenge here is that I don't have a Netflix account to test with.. need to fix that first ;) In the meantime, a hidden feature: if you click on the speed indicator when its expanded (on the speed number), it'll hide it permanently until you refresh the page.

**Comment by bundy23** [comment]
That fixed it. Now it's a 10/10
