### ISSUE TITLE
Youtube speed resets every time while toggling Full Screen and back.

### ISSUE THREAD

**Issue by BerkayTamer** [igrigorik/videospeed#370]
Apparently, this speed-reset issue has been happening when toggling the theater mode but now this issue has recently started to happen when opening the Full Screen, as well as going back to the normal screen from the Full Screen. I go on Full Screen and back often which is why this has created some annoyance for me and I am sure I am not the only one getting annoyed by this.

Also, hopefully, this info will be helpful when it comes to fixing this issue:

 I believe this issue has started to happen after youtube added this **"Scroll for details"** function on Full-Screen videos where you get to scroll down and see the comments/related videos even on Full-Screen mode.

<img width="189" alt="scroll for details" src="https://user-images.githubusercontent.com/17339988/44675143-a5e70180-a9fd-11e8-9862-b2347a583a4e.png">

I guess I can get used to this but it would've been amazing to see this problem get fixed, hopefully, it has an easy fix. Btw, I am using Chrome on a Macbook Pro and didn't test the issue on other browsers/systems but I assume they would have the same outcome due to Youtube's recent change on Full-Screen mode. I should also say that **Video Speed Controller** is my most favorite browser extension ever and I am so grateful to its creator, saved me so much time!

**Comment by igrigorik** [comment]
Hmm, can't see to reproduce this on this end. Do you have an example URL that you can share?

**Comment by drewta** [comment]
Have the same issue with speed resetting to 1.0 when toggling between normal and theater mode on any video (e.g. https://www.youtube.com/watch?v=0pO7DWIfR6Y) using either hotkey (T) or manually clicking the button. Doesn't happen when toggling between normal and full screen. I also don't have the scroll for details function, so unsure if that's related. Using Chrome 68.0.3440.106 on a Windows 10 device.

**Comment by BerkayTamer** [comment]
Oh, I just realized it works on everywhere except when I open Youtube on incognito mode and while being signed into my Youtube account. The weird thing is that it does work when I am not signed into my account on incognito mode. 

So in every video that I tested, for example this one: https://www.youtube.com/watch?v=LnQukViKyGY 

When I am in incognito mode and signed into my Youtube account, the speed that I set resets while opening the video on Full Screen or going back from Full Screen to normal screen again. However, since this issue only happens on incognito mode while being signed into a Youtube account, I guess this is not a big issue overall. I mean it's a big issue for me since I use one account on normal Chrome while using my other youtube account on the incognito mode but I guess I can get used to this.

**Comment by igrigorik** [comment]
Wow, that's a "fun" one. Hard to say what's going wrong there.. Do you have any other extensions that are only active in incognito? I'm wondering if there's some interop issue here.. The fact that you're in incognito shouldn't change anything, other than the fact that it's a different profile.

**Comment by BerkayTamer** [comment]
You are definitely right **nikitabobko**, good call! After reading your comment, I've tested it out and realized that this issue only happens to me on videos where I see the "Scroll for details" message on the full-screen videos. 

This is also why I wanted to mention about the new "Scroll for details" feature as the potential source of the issue on my original comment because the very first time I've seen this "Scroll for details" feature is around the same time I've realized the resetting of the video speed issue. I wish I could disable this feature but I couldn't find anything about that on Google, unfortunately.

**Comment by nikitabobko** [comment]
Recently YouTube added one more new function which is miniplayer
![youtubr](https://user-images.githubusercontent.com/20517828/46571823-a96a9280-c984-11e8-93a2-365e607730bf.png)
And there is the same issue with this miniplayer: when you switch between miniplayer and normal player then playback speed resets.

Found temp solution which fixes playback speed resets: In extension settings tick "Remember Playback Speed".

**Comment by MerkaST** [comment]
Can confirm, I recently got the "Scroll for details in fullscreen mode" feature and since then, changing the view mode on YouTube (fullscreen, theatre mode, miniplayer) will reset the playback speed to 1. Interestingly, this also happens when having changed the speed with only the YouTube-provided menu.
It would appear that the extension detects the change in view mode as a change of video player, as the speed won't change if "Remember Playback Speed" is enabled and the issue also doesn't appear when the extension is disabled (ie. speed changes from the YT-provided menu will persist through mode changes in that case).

**Comment by canarslan12** [comment]
the problem is that video element changes and vsc act as it's new video. we should prevent that from happening. 
we can do this by replacing this with replace vscid in `if (ctrl)` condition.
`            let id = node.dataset['vscid'];
            let ctrl = document.querySelector(`div[data-vscid="${id}"]`)
            if (ctrl) {
              ctrl.remove();
            }
            node.classList.remove('vsc-initialized');
            delete node.dataset['vscid'];
`

**Comment by canarslan12** [comment]
it's culprit. this code work every time we press F. 
this code delete/remove current vsc and create new one. Rather than that we should replace dataset['vscid'] with new one, if there is any video without vscid.

**Comment by igrigorik** [comment]
That behavior was intentional, as otherwise you can end up with multiple controllers overlapping each other, hence the wipe the slate and re-register strategy.

Taking a step back.. presumably this should not be an issue if you have 'remember speed' enabled — correct?

**Comment by igrigorik** [comment]
Hmm, isn't that working as expected then? Per my earlier point, we need to unregister previous controllers to ensure we don't end up with multiple per video.

**Comment by garyking** [comment]
For users that choose to remember the speed, yeah, it's a workaround for YouTube.

It would be nice to have a specific workaround engineered for YouTube, though, since the website is so popular, and right now, video speed settings for users that don't choose to remember the speed are being reset when going in and out of full screen.

**Comment by Rajdeep97** [comment]
This issue only happens on YouTube, no where else. Can we please look into adding a specific fix just for YouTube?

**Comment by igrigorik** [comment]
I've been trying to explicitly avoid making too many site conditionals, as that makes the extension really hard to main over the long-term — hard to trace, brittle, etc. That said, if we can come up with a clean solution.. it _would_ be nice to ensure YT is working smoothly.

**Comment by deef0000dragon1** [comment]
Just going to add a "This happened to me as well",
It happened to me some time ago, but then fixed itself. Just today it started happening again. I have a feeling that this is something to do with the beta program.

**Comment by osiixy** [comment]
I have this issue also

**Comment by ChadBailey** [comment]
I can confirm this happens to me across multiple browsers, pc's, and operating systems, though that appears to be known already wanted to make it clear.

For what it's worth, the introduction of the new behavior seems to correlate with the introduction of being able to scroll down while in fullscreen mode.

**Comment by guilhermeip** [comment]
I solved this problem by disabling an extension called Video Speed Controlle

**Comment by dirtyid** [comment]
Hello this issue has returned a couple days ago.

**Comment by jonandeva** [comment]
I'm having the same problem again too.

сб, 27 апр. 2019 г. в 19:06, dirtyid <notifications@github.com>:

**Comment by jonandeva** [comment]
Actually, I've also been having a new problem the past few days. When I
click onto a new video, the Video Speed Controller still shows the speed I
was using on the previous video, but the actually speed is reset.

сб, 27 апр. 2019 г. в 19:06, dirtyid <notifications@github.com>:

**Comment by igrigorik** [comment]
Those are all the same issue folks. New update will go out today and should address it.

**Comment by JannetGen** [comment]
A useful thing to check is whether the issue only happens with certain video formats or players. If possible, testing the same page with a basic HTML5 <video> element can help narrow it down. Also worth checking the browser console for errors, since an extension can fail to hook into players that use custom playback implementations.
