### ISSUE TITLE
Does not work on some YouTube videos

### ISSUE THREAD

**Issue by bitlux** [igrigorik/videospeed#371]
When viewing some videos on YouTube, the VSC icon doesn't appear, and the hotkeys to adjust the playback speed don't work.

https://www.youtube.com/watch?v=lRXjP9ZbA2Q is one example.

**Comment by SeanSilke** [comment]
@bitlux Check extension with this video. All work for me. It will be convenient if you leaf some information about your system.

**Comment by bitlux** [comment]
OK, that video works for me in Chrome 68.0.3440.106 on Debian. It did not work on my Chromebook (will update the version when I get home).

**Comment by bitlux** [comment]
... and now it works for me with that video / computer combination. If it happens again I'll try restarting my browser first.
