### ISSUE TITLE
Nice but doesn't work on Twitter.

### ISSUE THREAD

**Issue by laxman07** [igrigorik/videospeed#373]
Is it possible to get support for Twitter videos as well?

**Comment by igrigorik** [comment]
We intentionally disable the extension on twitter.com by default, but you can change that in the settings by removing that line.

![image](https://user-images.githubusercontent.com/10652/45101793-2930e300-b0e1-11e8-911e-8fe981980eb9.png)

**Comment by laxman07** [comment]
Totally skipped this ;). Thanks for notifying.

**Comment by fearthecowboy** [comment]
Just curious... _Why_ blacklist twitter by default? Is there something that it doesn't work well with, or is it just that 99% of twitter videos are 'gifs' (aka short silent videos)

**Comment by yehat** [comment]
x is short cut to block user. So could be annoying to use?

However I use shift X and shift Z.. twitter ignores the shift but the plugin doesn't so works just fine. I removed twitter.com from the exception list.
