### ISSUE TITLE
Extension not working on CW's website

### ISSUE THREAD

**Issue by lindsayyyyy** [igrigorik/videospeed#382]
The extension doesn't work on the videos on cwtv.com. It works on their commercials but not on the main show content. The extension still shows up but it looks like there are two sets of controls overlapping each other. The screen shot attached shows what it looks like. I love your extension btw, it works on like 99% of the websites I visit, this is the first time it hasn't worked on one and I think it's because they updated their site. Thank you so much for your time and let me know if this is a problem that can be fixed! :) 
![screen shot 2018-10-15 at 10 19 30 pm](https://user-images.githubusercontent.com/44188044/46995502-e560ce80-d0cd-11e8-91a6-b570458022f3.jpg)

**Comment by dereg666** [comment]
same here 😢

**Comment by igrigorik** [comment]
Seems to be a-ok with the latest version -- please try with the new 0.5.3 release (rolling out shortly).

**Comment by theguildofthefairies** [comment]
Hi! I uninstalled and reinstalled the extension in hopes that the update would fix the issue with CWTV but it's still not working for me. Thanks for working so hard on this extension, it's really changed my life and how I watch everything!!

**Comment by lindsayyyyy** [comment]
Hi, I uninstalled and reinstalled it just like the previous commenter but it's still not working on the CW's website. Again, I love the extension and am super grateful but the update didn't fix the problem. Thanks :)
