### ISSUE TITLE
Migrate Element.createShadowRoot to Element.attachShadow

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/videospeed#384]
> [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
>
> tc.videoController.initializeControls @ inject.js:117

/cc https://github.com/igrigorik/videospeed/issues/335

@mudala would you be willing to upstream your patch for attachShadow?

**Comment by avidrissman** [comment]
Let me know when you push a CWS update so that I can verify the fix.

**Comment by igrigorik** [comment]
@avidrissman I want to land the two outstanding PRs before I ship it.. Fingers crossed, very soon.
