### ISSUE TITLE
Mouse events aren't working

### ISSUE THREAD

**Issue by sethtroisi** [igrigorik/videospeed#389]
I can use D and S to slow and speed up videos but the overlap isn't responding to clicks.
Using "Chrome 71.0.3578.53 beta (64-bit)"
I've restarted chrome, disabled & renabled the extension.

When I hover over the overlay I get different mouse pointers but I can't drag it and clicking does nothing.

**Comment by igrigorik** [comment]
Is this happening on a particular site, or on all sites for you?

**Comment by sethtroisi** [comment]
On all sites I tested: youtube, netflix, and native html5 sites

**Comment by canarslan12** [comment]
I can confirm that problem.

**Comment by sethtroisi** [comment]
It's weird because this seems to affect only 1 of my 4 computers.
My chrome updated and this seems to still affect my in 71.0.3578.62 beta

**Comment by ksbrar** [comment]
Also having this problem.
