### ISSUE TITLE
Does not work on LinkedIn Learning Videos

### ISSUE THREAD

**Issue by ghostsysoutnull** [igrigorik/videospeed#391]
Example: https://www.linkedin.com/learning/java-8-essential-training/principles-and-components-of-java

**Comment by igrigorik** [comment]
Unfortunately this is due to how their player is implemented. It listens to and enforces speed controls to be valid values set by the player only, which we cannot override. The good news is, however, is that their player has fairly good speed controls built in.

**Comment by ChadBailey** [comment]
Hello, I reached out to the Linkedin (previously, Lynda) support team and they honored my request to remove this restriction! You can now play Linkedin learning videos at speeds greater than 2x, thank you Linkedin for making this update!

**Comment by igrigorik** [comment]
Woohoo!!! Thank you!

**Comment by ghostsysoutnull** [comment]
Awesome!!

**Comment by sdasda7777** [comment]
> Hello, I reached out to the Linkedin (previously, Lynda) support team and they honored my request to remove this restriction! You can now play Linkedin learning videos at speeds greater than 2x, thank you Linkedin for making this update!

Hi, could you share more details on this? I can't seem to achieve playback larger than 2, and I'm not sure if perhaps something has changed, or I'm just trying the wrong way. When setting playbackSpeed from console, for me it just resets for playbackSpeed > 2.

**Comment by sdasda7777** [comment]
> Hello, I reached out to the Linkedin (previously, Lynda) support team and they honored my request to remove this restriction! You can now play Linkedin learning videos at speeds greater than 2x, thank you Linkedin for making this update!

@ChadBailey Hi, could you please share more details on this? I can't seem to achieve playback larger than 2, and I'm not sure if perhaps something has changed, or I'm just trying the wrong way. When setting playbackSpeed from console, for me it just resets for playbackSpeed > 2.

**Comment by ChadBailey** [comment]
Unfortunately, there is nothing that can be done about LinkedIn's decision to revert this behavior. I may attempt to open another ticket kindly requesting it, but you have the ability just the same as I do.

**Comment by sdasda7777** [comment]
@ChadBailey I see, thank you for bringing me up to speed. That is fine, you're right, I will do it myself.

**Comment by ChadBailey** [comment]
I have edited my response to give a bit more detail. I did check and it's happening for me too :(
