### ISSUE TITLE
Why does it sometimes get set to odd speeds that aren't a multiple of my speed increment?

### ISSUE THREAD

**Issue by truth1ness** [igrigorik/videospeed#393]
My speed increment is .5 and preferred speed is 1.75. But sometimes the extension opens a video set to some weird number like 1.20 or 1.80 which isn't a multiple of any of these. I don't understand how this is happening. There is no accidental keystroke sequence that would land on these numbers so why/how are these weird speeds being chosen randomly? Is it something I'm doing or some glitch? It's not a major issue because I can just reset but it's happened since I got the extension and always leaves me scratching my head.

**Comment by igrigorik** [comment]
Some players reset and force their own speed setting. My guess is that you have "remember speed" enabled, and that persists that players preference.. which is why and how it shows up later.

**Comment by truth1ness** [comment]
I'm confused. You are saying video sites are intentionally forcing my player to watch at weird numbers like 1.20 or 1.80? I've never seen a player not play at 1.00 by default and most have no speed controls. The only one with its own speed control I know of is Youtube whose player's speed control moves in .25 increments. But even with that there is no mathematical way it would accidentally result in 1.20 or 1.80 based their .25 increments. 

I do have Remember Speed enabled but I don't see how that is related. If I understand correctly Remember Speed just recalls the last speed used when I open a new video. That doesn't explain how the speed control could ever land on non-increment-multiple numbers like 1.20 or 1.80 in the first place. I can't even figure out how I would even do that intentionally. You cannot get to 1.20 or 1.80 with .5 and .25 increments. Even the jump between those two is .6, another weird increment that doesn't match any increment settings. It's such an odd thing. 

Here is a picture of my settings:

<img width="286" alt="screen shot 2018-12-03 at 3 59 43 pm" src="https://user-images.githubusercontent.com/6664464/49401212-848c6480-f714-11e8-9c6d-8171f68f06ff.png">

**Comment by igrigorik** [comment]
Some players take ownership of managing speed settings: they save their own pref and only allow you to increase in certain increments, and I've seen that clash and interact in funny ways with our controller. That said, that may or may not be the underlying issue here.. I can't say what the issue is with certainty, unless you can try to isolate times + cases where you see this happen.
