### ISSUE TITLE
App stopped working 

### ISSUE THREAD

**Issue by GEORGEJUNGCOCAINE** [igrigorik/videospeed#394]
All of a sudden it's stopped working for the first time

**Comment by evodoc** [comment]
Same, the hotkeys still work though, only the mouse clicks are not registered. Probably the recent Chrome update messed up something.

**Comment by poush** [comment]
Same here.

**Comment by princesden** [comment]
It stopped working after chrome update from v70 to 71.

**Comment by paulocesar-ufu** [comment]
Same here! Chrome 71

**Comment by canarslan12** [comment]
Is this just mouse events or all at once? If just mouse events duplicate of
#389

**Comment by paulocesar-ufu** [comment]
Only mouse events, its really duplicated of #389

**Comment by bethrobson** [comment]
Yep me too, Chrome 71. Still working on Firefox.

**Comment by bethrobson** [comment]
How do we find out when an update will be forthcoming?

**Comment by igrigorik** [comment]
Fix should be rolling out with 0.5.3. 

Kudos to @canarslan12 for fixing this one!
