### ISSUE TITLE
Video Speed Does not Work

### ISSUE THREAD

**Issue by clopar** [igrigorik/videospeed#398]
I use this app more than anything, and all of the sudden it stopped working. See video for what's going on - https://www.useloom.com/share/3f67ab0ec8794270b2464f332dfc925b

Any suggestions?

**Comment by v1adko** [comment]
Yep, same for me - huge issue.

**Comment by igrigorik** [comment]
Dupe of https://github.com/igrigorik/videospeed/issues/394. Closing, let's continue there.
