### ISSUE TITLE
Change speed/rewind while video is paused

### ISSUE THREAD

**Issue by truth1ness** [igrigorik/videospeed#40]
I'm not sure if it's always been like this or if I just noticed it. It seems that now the speed change and rewind don't work while the video is paused (shortcuts or with the mouse buttons).

**Comment by igrigorik** [comment]
Hmm, it's always had this behavior: https://github.com/igrigorik/videospeed/commit/2965ec345d714347b6a0cd4e763e5acb40d0192a#diff-e24e9eb38cffaafae22019e36f31a570R74

How/when do you adjust this when you're paused? The gotcha here is that there may be multiple videos.. so the paused check was to ensure that we apply the change to correct video.

**Comment by truth1ness** [comment]
Yea, I remember this working in the past but it seems to not work anymore. It happens on Youtube pages where there is only one video as well as pretty much any other video source. Have you confirmed that it is working for you? How: I pause a video and press the a/s/d keys and nothing happens. When: when I'm watching a video.

**Comment by igrigorik** [comment]
Yes, that's the intended behavior (see my previous link into the source that checks for pause state). The problem with "works on YT pages" is that there are many pages where you have more than one video, so targeting becomes a problem.
