### ISSUE TITLE
Disable website key binding when tapping text.

### ISSUE THREAD

**Issue by sharkistani3awtani** [igrigorik/videospeed#410]
Hello,
The new option of setting "Disable website key binding" is very good, but it prevent me from tapping text, I suggest to make an exception in text area.
Thanks.

**Comment by sharkistani3awtani** [comment]
It seems that the issue is from a site using a non ordinary text input.

**Comment by AlexanderMur** [comment]
https://leroymerlin.ru/ can you type in search bar if you use "Disable website key binding"? Seems like it has non-ordinary input is possible to fix such inputs?
