### ISSUE TITLE
playback stall on linux/gnome, audio unaffected

### ISSUE THREAD

**Issue by wimachtendink** [igrigorik/videospeed#412]
When watching Netflix or YouTube, visual playback stops but audio continues. (i haven't really tested any other sites)

I've only experienced this problem on Pop!_OS with Gnome, but I haven't really tested any other Linux distros or desktops.

I haven't done any testing as to how frequent this is, but it's every few minutes.

for now i'm just using Firefox and the Firefox port by CodeBicycle, but their port is not nearly as good so if anyone has any ideas how I might remedy this, i'd like to hear it.

Thank you.

**Comment by igrigorik** [comment]
Hmm, not sure.. could be an issue with FF media stack. Since this is a sister extension, closing.
