### ISSUE TITLE
Option to disable/enable keyboard shortcuts

### ISSUE THREAD

**Issue by cristisilaghi** [igrigorik/videospeed#414]
Is it possible to control video speed ONLY from the overlay? Perhaps an option to tick/untick in Settings?

Keyboard shorcuts may affect some websites and there could be users interested in controlling speed using only mouse.

**Comment by canarslan12** [comment]
You can just press ESC to unbind

**Comment by igrigorik** [comment]
What @canarslan12 said.. You can unbind all the keys if you don't want to use them. In the settings, click on the setting you want to unset and hit ESC to unbind.

**Comment by cristisilaghi** [comment]
Ok, I didn't know. Thank you very much for this!
