### ISSUE TITLE
Speed isn't remembered between different video players

### ISSUE THREAD

**Issue by TyranitarTar** [igrigorik/videospeed#415]
In the past few days video speed hasn't been carrying over from different video players

So say I'm watching several YouTube videos in a row, and speed carries over just fine but then I watch Plex on the web and speed will reset but then carryover just fine between Plex videos, but reset again when I go back to YouTube.

On some some more obscure and niche players speed won't carry over at all.

This is only started happening in the past week.

**Comment by igrigorik** [comment]
Can't reproduce, please reopen if you can isolate the sequence that triggers this.
