### ISSUE TITLE
Latest update breaks compatibility with Chrome 49

### ISSUE THREAD

**Issue by hifi3000** [igrigorik/videospeed#416]
After receiving the new version (0.5.3) of the extension, it no longer works on my Chrome (49.0.2623.112). It shows as installed, but the controller and keyboard commands aren't there for any HTML5 video. 

I'm limited by my Mac hardware to OS 10.7.5, so my Chrome doesn't update any further than v49. Is it possible to provide an older build of the extension for legacy Chrome users?

**Comment by igrigorik** [comment]
Yikes, M49. 

We don't publish old versions, but you can rollback some of the commits via git and install the extension as an [unpacked extension](https://developer.chrome.com/extensions/getstarted#unpacked).
