### ISSUE TITLE
feature request: Super fast play

### ISSUE THREAD

**Issue by hellonearthis** [igrigorik/videospeed#417]
I use two youtube speed extensions,  this one is the best but lacks the one cool feature I often use of another.  What it does it play the video at 16x speed while a hot key is pressed.  Great for blasting through ads or dull content.  It's a sad extension that I would like to dump as it watermark is constantly on and injects audio and other junk into all websites even when there is no video and the sound options off. Very sad..  

I've not looked at the code,  so don't know how easy this would be to implement.  
Does anyone know if this would be hard to do?

**Comment by igrigorik** [comment]
You can define a custom "reset" key in the settings that switches to high-speed and then back. Give that a try, perhaps it'll solve your use case?

**Comment by hellonearthis** [comment]
The reset defaults to a speed of 1 and adding a different value doesn't change it from 1.
The increase speed can be set to 16 and setting it's hotkey next to the reset works ok and the preferred  speed works well for general fast viewing.

As for adding a custom button,  i guess the increase speed could be duplicated and give it's on key. 
I might try that this weekend.
