### ISSUE TITLE
G key not mentioned in the documents.

### ISSUE THREAD

**Issue by hellonearthis** [igrigorik/videospeed#418]
The fast option is not mentioned in the git readme docs.  
It is in the programs options, so is intuitive.
Other docs to add would be to add a turbo key.

So I might have a go at writing that up this weekend.

**Comment by hellonearthis** [comment]
Not sure how to add a picture to the document as I don't think we want it in the repository (will the other images are not there, so will add it here and link to it.  Is there a better solution?
![settings](https://user-images.githubusercontent.com/121805/50726471-50242200-1172-11e9-902f-0e5958387617.jpg)

**Comment by igrigorik** [comment]
Closed via https://github.com/igrigorik/videospeed/pull/419.
