### ISSUE TITLE
Wisita

### ISSUE THREAD

**Issue by jenglish24** [igrigorik/videospeed#42]
Love your product! but its not working on Wistia Videos.

**Comment by igrigorik** [comment]
It should work fine as long as Wistia doesn't default to Flash video. Checking videos on their site in my browser.. I do get the controls. FWIW, you might want to try disabling flash: 

* Go to: chrome://plugins/
* Disable flash plugin
* Try viewing a Wistia video

**Comment by joshdance** [comment]
I can't get VideoSpeed to work with Wistia videos. I switched back and forth between HTML5 and Flash, the interface never showed up with HTML5.

**Comment by igrigorik** [comment]
Can you share a link that you're testing? I'm testing the video on the Wistia homepage and it's working for me.

**Comment by joshdance** [comment]
Just tested. Key is refresh. When you right click - switch to HTML5 it
flashes, looks like it refreshes but doesn't. But if you refresh the page,
the controls show up and they work.

Maybe just pop that in the doc?

Thanks!

On Thu, Aug 13, 2015 at 9:19 AM, Ilya Grigorik <notifications@github.com>
wrote:

> Can you share a link that you're testing? I'm testing the video on the
> Wistia homepage and it's working for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igrigorik/videospeed/issues/42#issuecomment-130727088>
> .
>



-- 
-J
____________________________________________________
Joshua Dance | Problem Solver | 425-301-9137 | [image: Twitter]
<http://www.twitter.com/joshdance> [image: YouTube]
<http://www.youtube.com/joshuajaydan>
joshdance.me/
helpcapeverde.org/

**Comment by joshdance** [comment]
Added the note to the readme and created a pull request. Feel free to accept or reject. https://github.com/igrigorik/videospeed/pull/57
