### ISSUE TITLE
About the new version of Google Chrome can not control the acceleration and other functions by clicking the floating window control with the mouse

### ISSUE THREAD

**Issue by changcheng168** [igrigorik/videospeed#420]
The latest version of Google Chrome can not use the mouse to click on the floating window control, only through the keyboard control function, I am using version 0.5.2, Google Chrome version number is 71.0.3578.98, I hope developers can fix it as soon as possible, support!

**Comment by igrigorik** [comment]
Cannot reproduce, if this is still a problem please reopen with example URL.
