### ISSUE TITLE
Youtube problem with fullscreen mode

### ISSUE THREAD

**Issue by retyui** [igrigorik/videospeed#424]
So.
When you open the video in fullscreen mode 
And then change video play speed
After that exit from fullscreen mode, you can see the video speed will be reset to `1.00`

It also works when in default mode change video play speed and then open fullscreen mode , you will see the same result `1.00`

### Video example:
![peek 2019-01-16 23-17](https://user-images.githubusercontent.com/4661784/51276171-072b6380-19e5-11e9-94f6-664e8a3d9b6b.gif)

**Comment by iSytrus** [comment]
It's old problem https://github.com/igrigorik/videospeed/issues/370
and unfortunately it is still not fixed yet.
