### ISSUE TITLE
Preferred speed changes to 0 on pause, requiring reset speed key press

### ISSUE THREAD

**Issue by eggbrow** [igrigorik/videospeed#428]
Have been using this now for 2 years. It's so useful that i could not cope without it. As of mid december i've been having an issue where (i'm fairly sure) it changes preferred speed to 0 after every time i pause. I then have to press r to reset that to 1. Anybody else getting this issue?
![image](https://user-images.githubusercontent.com/25536683/52122267-4dee9f80-261a-11e9-95b1-aed2291cf76c.png)

**Comment by eggbrow** [comment]
i am on
![image](https://user-images.githubusercontent.com/25536683/52122292-6d85c800-261a-11e9-97a1-429a23a1f35d.png)
windows 8.1 64bit

and extension settings are set to
![image](https://user-images.githubusercontent.com/25536683/52122312-7f676b00-261a-11e9-81c6-df9d4181d7a0.png)

**Comment by eggbrow** [comment]
I removed the additional pause shortcut (was for sites where the spacebar didnt pause by default or with player focused) and everything working properly. I'll leave this issue here in case anybody else has same problem.

**Comment by igrigorik** [comment]
Thanks for flagging this. This is a bug, we shouldn't reset the speed on pause; unpausing should reset back to original speed.

/cc @canarslan12

**Comment by igrigorik** [comment]
Should be resolved via #475.
