### ISSUE TITLE
getting an error msg and its this extension

### ISSUE THREAD

**Issue by BobWalsh** [igrigorik/videospeed#429]
In Chrome 72.0.36 Mac Stable I'm now seeing this js error in the chrome dev tools: Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

I tracked it down to this extension and no other.

To reproduce it, install/enable videospeed 0.5.3 in chrome. Look at the js console, see the error. Disable extension, the error is cleared.

**Comment by marksmithson** [comment]
Verified this is the case as well on Chrome 72.0.3626.96 OSX

**Comment by accetone** [comment]
Same with Chrome 72.0.3626.109, Windows 8.1

**Comment by igrigorik** [comment]
This should be addressed in master, but not yet released. 

See related discussion in: https://github.com/igrigorik/videospeed/issues/339

**Comment by fredsa** [comment]
@igrigorik Do you have timeline for when the fix will be published to Chrome Web Store?

Note, a number of users have also mentioned the `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.` error message on the [video-speed-controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) "support" tab.

**Comment by igrigorik** [comment]
0.5.4 should be rolling out as I write this :-)

Thanks all!
