### ISSUE TITLE
The overlay doesn't go away in fullscreen when using the new player.

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#43]
Title says it all. 
Using the new player(https://www.youtube.com/testtube), the speed indicator doesnt go away when in fullscreen.
Just a minor annoyance

**Comment by igrigorik** [comment]
Thanks for reporting it! Should be fixed in master. If you're willing, give it a shot.. you can install it as an unpacked extension.

**Comment by Eisys** [comment]
Yup, works perfectly now.
