### ISSUE TITLE
Speed automatically increases to 1.03 without prompting

### ISSUE THREAD

**Issue by bosque4444** [igrigorik/videospeed#430]
Without me doing anything (and with my preferred speed set to 1.00) my videos frequently bump up to 1.03 speed. How do I get this to stop?

**Comment by igrigorik** [comment]
Can you share an example URL where this happens?

**Comment by bosque4444** [comment]
It does this on Twitch.com extremely frequently.

**Comment by bosque4444** [comment]
Any updates?

**Comment by igrigorik** [comment]
Hmm, can't reproduce on twitch.com. Are you sure you're not hitting the shortcut key, or something similar? Please reopen if it's still an issue.

**Comment by bosque4444** [comment]
Yes I am not hitting anything and my settings are have been reset. Is there anything else we can do to troubleshoot this?
