### ISSUE TITLE
Video speed don't persists 

### ISSUE THREAD

**Issue by nrkkv** [igrigorik/videospeed#431]
Udemy we have a video speed range 0.5x - 2.0x].

When I set a speed out of this range (< 0.5x or > 2.0x) and go to the next video, it reset to 1.0x.

Other sites like Youtube persists that information.

**Comment by Priyamomer** [comment]
Please solve this issue i have to speed up again and again...

**Comment by nrkkv** [comment]
> Please solve this issue i have to speed up again and again...

hey, a paliative solution to this is go to settings of extension and configure 'preferred speed' + keybind + video speed u want. 
so everytime you start a video, just press one keyboard to turn video speed to your preference.

**Comment by igrigorik** [comment]
Unfortunately this is due to how Udemy player is implemented: they monitor for speed changes and reset the speed in their player (hence reset back to 0). The only solution here is what @nrkkv recommended.
