### ISSUE TITLE
Exempt Live Streams

### ISSUE THREAD

**Issue by Chiramisu** [igrigorik/videospeed#433]
## Proposal
This extension should default to a 1.0 playback speed for **live streams**, due to buffering issues, and disregard its own "Remember Playback Speed" setting.

### YouTube Case
I can't speak for other content providers, but I did verify that for YouTube at least this appears to be demarked by the presence of the `"live": "dvr"` tag, which you can find by right-clicking on the video / stream and selecting "Copy debug info."

## Acceptance Criteria:
With regard to supported sites...

1. Extension shall playback at 1.0 speed by default for live streaming content.
1. Extension shall respect the "Remember Playback Speed" for all VOD content, especially when switching between live streaming and VOD content.
1. Extension shall use the "Hide controller by default" option for live streaming content by default.

**Comment by igrigorik** [comment]
I've actually found the extension to be really useful for live streams, and hear similar feedback from others. The trick is to build a buffer from the livestream: open it, pause it, go do what you need to do, come back and catch up until you hit current time, repeat.

As such, I'm inclined to keep the current behavior as is. Especially in light of the fact that outside of youtube we don't have a reliable way to detect a livestream.
