### ISSUE TITLE
Extension not working on CW's Website 

### ISSUE THREAD

**Issue by PJJP13** [igrigorik/videospeed#439]
The extension worked for me on an episode of Arrow two days ago at 3 times speed. Yesterday I was unable to get the extension to work on the flash, arrow and another random show. The weird thing was that the ten second fast forward and rewind worked. The speed time would go up when I clicked on it. It would pause and unpause each time I clicked to raise the speed. The extension works everywhere else for me Hulu, Youtube, Netflix.
Thanks for this awesome extension!

**Comment by jacobcolbert** [comment]
The CW website uses a playback manager that is watching for any playbackRate changes and setting it back to 1.00. May be possible to override this but I think it is probably outside the scope of this extension.

**Comment by igrigorik** [comment]
There is a number of players that do this.. and that's a war we can't win.

Closing, wont-(can't really)-fix.
