### ISSUE TITLE
Icon visible but not operational on a site

### ISSUE THREAD

**Issue by Wisdawn** [igrigorik/videospeed#44]
Thank you for working on this awesome extension.

On the following page:
http://www.riversoftware.com/product/overview

I can see the extension's icon, showing a speed of 1.0, but I cannot control the speed and nothing pops up when I hover the mouse pointer over the extension's icon.

**Comment by igrigorik** [comment]
@Wisdawn hmm, seems to be a-ok on this end. Do you have any other extensions that could be causing this behavior?

**Comment by Wisdawn** [comment]
@igrigorik Thank you; it is indeed working just fine now. No idea what cause that problem that day.

**Comment by igrigorik** [comment]
Glad to hear. Closing, feel free to reopen if it comes back.
