### ISSUE TITLE
support picture-in-picture

### ISSUE THREAD

**Issue by vapier** [igrigorik/videospeed#441]
i know it doesn't exactly fit in with the scope of this extension, but how do you feel about adding support for toggling picture-in-picture ?  most sites don't support this, especially as it's not been implemented in other agents yet.  Chrome 70 shipped it though.

all you have to do is call the video element's `requestPictureInPicture()` method.

* [specification](https://wicg.github.io/picture-in-picture/)
* [firefox status](https://github.com/mozilla/standards-positions/issues/72)

**Comment by igrigorik** [comment]
Interesting idea. Paging @beaufortfrancois for thoughts and opinions :-)

**Comment by beaufortfrancois** [comment]
I agree with @vapier that it's not in the scope of the extension **but** I'd be happy to review a PR if needed.

In the mean time, we also have published [Picture-in-Picture Extension (by Google)
](https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg) for this specific use case.

**Comment by igrigorik** [comment]
Ah, perfect. If there is an official extension for this.. let's defer to that! Thanks!

**Comment by vapier** [comment]
i'm aware of the pip extension, but my suggestion for this was due to:
* the pip extension operates at the page level rather than per-video
* it's one fewer extension i need to install ;)
* one fewer extension that needs to crawl the dom looking for video tags to expose custom UI

so if people are amenable to it, i'd be happy to post a PR for this extension

**Comment by igrigorik** [comment]
> * the pip extension operates at the page level rather than per-video

Hmm, I guess I'm not familiar enough with the implementation but this sounds like a good feature request for the official extension?

> * it's one fewer extension i need to install ;)
> * one fewer extension that needs to crawl the dom looking for video tags to expose custom UI

I hear ya, but the ongoing cost of maintenance is a real burden. I would rather do one thing well, which is already keeping us plenty busy here, than multiple things poorly.
