### ISSUE TITLE
Netflix goes back to 1.0 speed after pausing for a while

### ISSUE THREAD

**Issue by GreatCatFood** [igrigorik/videospeed#442]
I set the speed I want, watch the show for a while, pause and walk away, come back later to find a circle with the play sign in the middle of the screen, I click the play sign, it goes back to 1.0 speed.

**Comment by AYiXi** [comment]
me，too，so sad

**Comment by igrigorik** [comment]
Thanks for reporting this. Let's continue this in #459, which is tracking this issue.
