### ISSUE TITLE
Feature Request: Automatic Jump cut mode

### ISSUE THREAD

**Issue by LRacoci** [igrigorik/videospeed#445]
It would be nice to have a mode where the extension detects silence (below a configurable threshold) and speed up (by a configurable amount) automatically in those parts

**Comment by LRacoci** [comment]
Sorry, I though this extension was able to actually manipulate the video. But this is way more difficult.

**Comment by madarez** [comment]
This is being addressed in #583 ! It'd be cool to see this feature available indeed!
