### ISSUE TITLE
YouTube unusable on every video

### ISSUE THREAD

**Issue by yadoyadoya** [igrigorik/videospeed#446]
No matter what video I open, it just doesn't read. It loads forever and shows the following message:
![image](https://user-images.githubusercontent.com/20118433/56091466-e5f1ea80-5ee1-11e9-8a93-474ced9e4ae6.png)

I had to uninstall this extension to use Youtube again.

**Comment by yadoyadoya** [comment]
Btw I'm using Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

on Windows 10

**Comment by igrigorik** [comment]
Glad you got it working!
