### ISSUE TITLE
extension not working on anvato player ott 

### ISSUE THREAD

**Issue by bandit789** [igrigorik/videospeed#448]
the control does not work. Mostly "1.00" is visible but not responsive. I've tried "custom block/click to remove element" to block all the items above but even then it does not respond. The shortcuts also doesn't work.

**Comment by igrigorik** [comment]
Do you have a public example URL you can share?

**Comment by bandit789** [comment]
unfortunately non of the streams are public. They are behind a free login wall.
As i read on the support site at least some of the streams will not be geo-locked.
(zip codes for belgium are 4 numbers for example 9000.)
https://vtm.be/vtmgo
it would be great to speed up the videos to 1.3

**Comment by jacobcolbert** [comment]
This is due to the content script not loading on the frame that is initially created as about:blank and dynamically loaded. Changing the manifest to match on about:blank fixes this problem.

Should all of these minor changes be in different pull requests? This is my first time contributing to a repo so not sure what best practices are.

**Comment by igrigorik** [comment]
@jacobcolbert yep, small PRs are both easier and faster to land. Thanks for digging into and investigating this one.

**Comment by bandit789** [comment]
is there a way to test this? I have override the manifest.json in the extension folder (with the odd name with numbers) where i found the appropriate icons for the extension. It is not working but maybe that is not the right way to do it?

**Comment by bandit789** [comment]
I found out how i could test it. It works with the keyboard shortcuts but hovering over the "1.00" does not trigger the usual buttons to control. It does change when using the shortcuts.
