### ISSUE TITLE
No way to hide/blacklist controls on Reddit

### ISSUE THREAD

**Issue by alystair** [igrigorik/videospeed#449]
I've tried blacklisting all reddit/v.reddit domains but the video controller appears in the middle of the video every time...

**Comment by jacobcolbert** [comment]
The controller always appears in the corner for me and blacklisting works too. Any ideas how I could recreate this problem?

**Comment by alystair** [comment]
It could potentially be a conflict with the extremely popular Reddit Enhancement Suite extension?

**Comment by alystair** [comment]
My guess is that media loads in some way that triggers the extension but breaks blacklist in some way...

**Comment by thewheat** [comment]
Another report of the controller appearing in the middle of the video here https://github.com/igrigorik/videospeed/issues/536

![image](https://user-images.githubusercontent.com/892961/66922119-051c3100-f059-11e9-933d-d963de34247b.png)


But with regards to blacklisting, `reddit.com` seems to blacklist the controller correctly for Reddit using [this link](https://www.reddit.com/r/funny/comments/dhfigp/irish_man_leaves_funny_recording_for_his_funeral/) provided in the other issue 
![image](https://user-images.githubusercontent.com/892961/66921667-419b5d00-f058-11e9-8b76-c47e367cb93e.png)
