### ISSUE TITLE
Is it possible to make the Shortcuts available in the offline video player?

### ISSUE THREAD

**Issue by n00ble** [igrigorik/videospeed#45]
Hello,

Thank you for the extension.
It would be great if the shortcuts are also available while playing videos offline. In addition to the "rewind 10 sec" shortcut, adding a "forward 10 sec" shortcut would be also nice. i.e. something similar to the shortcuts in "Potplayer".

Thank you again

Zaphod Beeblebrox
President of the Galaxy :P

**Comment by igrigorik** [comment]
@n00ble by offline you mean just opening a local video file with Chrome, right? For example, File > Open File, etc? If so, that should work as is.

**Comment by n00ble** [comment]
Thank you for the response. 
Can you please consider adding a "Fast Forward" shortcut too? i.e. a shortcut that will skip 10 sec forward.

For it to work off-line (local video as you said), one needs to check the option in extension settings page and then restart the browser:
chrome://extensions/
"Allow access to file URLs"
Restart chrome
It may also be helpful to add this info either on extension page or in some other way into the extension info.

BTW, it also works on Opera browser after adding the "Download Chrome Extension" that allows using Chrome extensions on Opera: 
https://addons.opera.com/en/extensions/details/download-chrome-extension-9/
It does not seem to work with VLC plug-in in Opera (for other than MP4 files, tested it with an mpg file). I could not make the VLC plug-in work in chrome.

Thanks again

**Comment by igrigorik** [comment]
Added instructions for enabling local playback in https://github.com/igrigorik/videospeed/commit/170a5f57614c12e3b21504a15cea6a8e9dcb1fb7. 

Re, fast forward: YT already provides a shortcut.. the right arrow key will skip 5s; left will skip back 5s :)
