### ISSUE TITLE
video sources skipping

### ISSUE THREAD

**Issue by xac1d** [igrigorik/videospeed#462]
sorry if support requests are not allowed here but i have video speed controller on multiple computers running chrome (all latest version, extensions are synced so ideally they are all running the same ones). 

1 out of 3 experiences stuttering when playing videos at 2x from various sources (audio continues to play throughout but video skips/stutters every few seconds). i have 1gbit/1gbit symmetrical internet, am hardwired and the computer having issues is actually the most powerful of the 3 spec-wise by a large margin. 

any ideas?

**Comment by jacobcolbert** [comment]
Has this always happened or is it a recent problem? Does it happen when vsc is disabled and you increase the speed with youtubes settings, e.g.? When you say various sources, do you mean it universally happens or is it ok on some sites/sometimes?
