### ISSUE TITLE
Video speeds on youtube

### ISSUE THREAD

**Issue by kchaubc** [igrigorik/videospeed#465]
Not sure if this is just on my computer but I've run into several issues using this extension in Youtube the past few days.

1) Pausing the video will change the speed settings. Ex: I will watch videos on 2x speed, but if I pause, the speed sometimes resets to 1x or 1.5x.

2) If I was watching through a playlist, when it automatically changed to the next video, my playback speed on the video before was remembered. Now, the next video starts at 1x speed every time.

**Comment by igrigorik** [comment]
Thanks for the report! Both of these should be addressed by #458 — in master but not yet released. I'm planning to push out an updated version this weekend.
