### ISSUE TITLE
videoController objects are never fully removed

### ISSUE THREAD

**Issue by jacobcolbert** [igrigorik/videospeed#468]
Any time a video is removed VSC removes the visible div from the DOM and removes the vscid from the video tag, but never unregisters listeners. This can be seen easily in youtube by refreshing any video. Over half the time the page will "delete" an ancestor of the video and immediately recreate it. Thus multiple controllers are created for the video (generally 2). If you change the speed you can see that the logging is doubled.

**Comment by mariusi7** [comment]
FYI (while testing 480) https://i.imgur.com/uXn9JZC.png
