### ISSUE TITLE
Clash with Lynda.com's HTML5 videos?

### ISSUE THREAD

**Issue by Wisdawn** [igrigorik/videospeed#47]
I believe that Video Speed Controller freezes Lynda.com pages when the HTML5 video format is picked and a user tries to play a video.

Perhaps you can see this happening on a page like this:
http://www.lynda.com/Storyline-tutorials/Articulate-Storyline-2-First-Look/192762-2.html

You may want to know that Lynda.com offers buttons to speed up HTML5 videos, but only up to 2x. Maybe this is the reason? 

The reason I believe that the extension clashes is that the pages and HTML5 videos worked fine  when I disabled the extension.

Obviously I can switch to the other video format, or disable the extension temporarily and use the site's built-in accelerator, but I just wanted to check first whether the problem has a solution, as I prefer to use the extension if possible, as it offers more customizable control over video speeds.

**Comment by igrigorik** [comment]
Thanks for reporting this! https://github.com/igrigorik/videospeed/commit/209cee807933ed5a12ca58a15ad07bc54961e171 should address the crash issue -- it looks like adding a class to the host element was causing Lynda's player to go into loop =/. 

That said, while it doesn't crash anymore, the VS controls don't work either.. their player overrides the controller values. Not sure how fixable that is.. without going deep into their code.

**Comment by Wisdawn** [comment]
Thank you for addressing this!

It does make things easier and smoother to not have to disable VSC when on Lynda.com. And even though I would've wanted to stick to VSC, it's not a big deal to use Lyda.com's controls for video speed instead.

Thanks again and best of luck with work on this and other projects. Much appreciated.

**Comment by Wisdawn** [comment]
Just wanted to report that I experienced a freeze / crash on this page:
http://www.lynda.com/Design-Design-Skills-tutorials/Foundations-Drawing/158841-2.html

Same thing; when I disabled VSC, the video worked.

**Comment by igrigorik** [comment]
Grr! Not sure what's going on here.. some odd interaction with Angular. 

For time being, disabled it on lynda.com: https://github.com/igrigorik/videospeed/commit/88198436e6a10717e844b36119a40db005f3adc0

**Comment by Wisdawn** [comment]
That should help without requiring the user to manually disable VSC every time they visit Lynda.com.

In the meantime, as a customer of their service, I'll send Lynda.com a request to check whether they can make their video-speed controls possible to disable from user settings or even the video settings. That's because I do prefer the level of control VSC offers, jumping in 0.1 speed intervals and moving faster than 2x, for example, rather than only being able to make 0.25 jumps and up to 2x max.

**Comment by igrigorik** [comment]
@Wisdawn ideally neither side would have to disable anything.. Instead, can you ask them to investigate why the tab freezes when VCS controls are injected? It would probably be a much easier fix from their side than from ours.

**Comment by Wisdawn** [comment]
Done. I had raised a ticket with my suggestion to Lynda.com, and now followed up with your suggestion using the same ticket reference.

**Comment by igrigorik** [comment]
awesome, thanks!

**Comment by Wisdawn** [comment]
They responded saying that they were not able to locate a problem like I have submitted. Did you already update the extension so it is disabled on Lynda.com?

**Comment by igrigorik** [comment]
No, I landed the update here in the repo, but I didn't release a new version on the Chrome Store.

**Comment by Wisdawn** [comment]
They treated it as a “suggestion”, and I guess I encouraged that by using that feature on the contact page. In any case, it's in the hands of their “Web Development Team” now. Maybe the techies won't be lazy and will have some sensibility to at least makes sure extensions like VSC don't crash the whole browser, even if the solution is to block the extension altogether somehow.

**Comment by Wisdawn** [comment]
Anyway, I just had a good idea and followed up with another message on the same thread with their customer support, part of which was: 

“So my point is: Even if you are not able to provide what I had wished for in my ‘suggestion’, it is in the best interest of Lynda.com that you do not allow a browser extension to crash the whole browser or tab when a user of said extension tries to play a video on Lynda.com, especially when this happens [only] on Lynda.com as far as the user's experience is concerned (of course techies would not that any site that uses the same code for video playback speed control would also crash the browser with that extension, but how many users will understand that when their experience says ‘it only happens on Lynda.com’?).”

**Comment by igrigorik** [comment]
@Wisdawn I'm also happy to update the extension to address the problem.. if they have any pointers for why or how its going wrong right now.

**Comment by Wisdawn** [comment]
@igrigorik Good to know!

**Comment by igrigorik** [comment]
Let me know if you hear back from them. In the meantime, closing.

**Comment by anthonyattard** [comment]
I'm having this same problem with teamtreehouse.com It doesn't crash the browser but I cannot adjust the speed of the video using VSC, only their built in control which is limited to 2x.

**Comment by igrigorik** [comment]
@anthonyattard that looks like a different issue.. I can't test the actual courseware, but looking at one of the trailers [1], the controller doesn't come up. I'm guessing they video is being injected dynamically and the controller fails to pick it up.. Need to investigate further and this should probably go into a separate bug.

https://teamtreehouse.com/library/how-to-make-a-website
