### ISSUE TITLE
Feature request: marker for specific start time

### ISSUE THREAD

**Issue by tyler1820** [igrigorik/videospeed#470]
I don't really program or anything, and I made a github account just for this feature request, so my apologies if I'm doing anything against etiquette here. 

So I usually use this extension to transcribe music off of YouTube, and adding a feature that would allow one to add a specific marker of time to jump back to a specific point in the video would be really useful.

For example if there were a section in a video at 0:36 seconds that I wanted to transcribe, I could set a marker with a hotkey and then press a different hotkey to automatically jump back to 0:36 in the video at the same speed that was already set. Hope this makes sense, and thanks for the extension!

**Comment by jacobcolbert** [comment]
I like this idea. I think video transcription is super great and should be made as easy as possible. There's a drop down in the settings area where we can add this without it getting in the way. I'll take a look at making it soon.

Thanks for the suggestion!
