### ISSUE TITLE
Incompatible with the latest version of Chrome

### ISSUE THREAD

**Issue by cameronj86** [igrigorik/videospeed#473]
After upgrading to the latest version of Chrome on my Chromebook (Chrome OS 74.0.3729.125) Youtube videos automatically stop playing after half a second or so and the 'loading' circle spins on the screen. YouTube works fine in Incognito so I disabled extensions one by one and determined that this was the culprit. 

Big fan and the extension has made me more productive so hopefully it can be resolved!

**Comment by igrigorik** [comment]
Hmm, thanks for the report. Testing on "Version 74.0.3729.157" and everything seems to be a-OK on this end. Are you running stable channel on Chromebook?

**Comment by jacobcolbert** [comment]
Good here as well on 74.0.3729.131

**Comment by cameronj86** [comment]
Sorry just realized my bug is actually related to ticket #474. It better explains the issue so I will comment there instead
