### ISSUE TITLE
Youtube bug (not tested other platforms)

### ISSUE THREAD

**Issue by sesevic** [igrigorik/videospeed#474]
I have the "remember playback speed checked" but this bug happens with that checked off as well. I usually watch everything at ~2x speed
Google Chrome is up to date
Version 74.0.3729.157 (Official Build) (64-bit)

When on YT and I hit K (youtube native for pause), and then K again - everything works fine.

However, when I hit 'space' it pauses, but reverts the speed to 0.00 and the video shows it's playing, but it's stopped. So I either have to hit R or G to have it play again.

PS.  In my settings my preferred speed is set to 2.0 but G always places it to 1.8 :((

**Comment by cameronj86** [comment]
I loaded #473 ticket and just realized I am experiencing the same issue but it is explained better here. I thought my YouTube videos were frozen, but after reading this ticket, I can confirm that Video Speed Controller is defaulting the speed to 0.00 which means the video won't start after hitting the play button. If I hit R, the video will begin playing as normal.

**Comment by jacobcolbert** [comment]
This is equivalent to #428 which I just took a look at.
Is there some reason we were implementing the VSC pause shortcut by setting the speed to 0 rather than using the built in video.pause()/ video.play()?

**Comment by igrigorik** [comment]
TBH, don't recall either. Your change in #475 makes a lot more sense to me as well.
