### ISSUE TITLE
NF has problems.

### ISSUE THREAD

**Issue by heiyutian** [igrigorik/videospeed#477]
netflix cannot rewind advance, Otherwise, there will be playback errors.

**Comment by heiyutian** [comment]
I used to test the extension below,  Can rewind advance five seconds.  But by videospeed.  It is impossible to achieve any rewind advance including 5 seconds or other time.

https://chrome.google.com/webstore/detail/netflix-quick-rewind/homohgaodkhbdckjbhpmcccafpgfjjbp

**Comment by jacobcolbert** [comment]
That's interesting. I always thought that fixing this was a hopeless hostility of the Netflix player. But if you say they have it working I'll take a look at how they implement it and see if it makes sense to do similar.

**Comment by jacobcolbert** [comment]
Ok. I found a way to do this. But it is netflix specific and will probably be broken some time in the future when netflix changes the way they do things. I'll make a fork and a PR to reference here for completeness sake. But be aware that @igrigorik will almost certainly (rightly) reject it, as ideologically it is certainly a bad thing to include.

But I do see a pragmatic argument for it that makes it worth creating. Netflix is the second most popular video site--adding some site specific code does not seem unreasonable. Personally I can say that frustration with the errors on Netflix stopped me from using the hotkeys altogether, decreasing the utility of the extension on all sites. Lastly the fact that it is likely to break at some point in the future is somewhat mooted by the fact that it is already broken. It seems that this implementation has been stable for at least the past year. So the timescale for changes could be quite long and not just a constant game of reverse engineering their latest player.

**Comment by igrigorik** [comment]
@jacobcolbert resolving.. but curious what your fix was.
