### ISSUE TITLE
Options Panel having no effect

### ISSUE THREAD

**Issue by DalJeanis** [igrigorik/videospeed#48]
I believe the May 17 update broke the options / settings functionality.  They're being saved, but not used.

I found this issue while testing addition of an "Advance" (skip forward) option button, and had to back up and verify I hadn't broken it myself.

**Comment by igrigorik** [comment]
Hmm, seems to be a-ok here.. just verified. As a sanity check, did you "save" the updated setting and reload the tab where you were testing the shortcuts?

**Comment by DalJeanis** [comment]
If you have to reload the tab to take effect, then it's working as defined.  (Worried myself for nothing when I found that during testing.)
