### ISSUE TITLE
Next episode plays without video (HBOGO)

### ISSUE THREAD

**Issue by mariusi7** [igrigorik/videospeed#480]
With the extension enabled (0.5.6), latest Chrome, when moving to next episode, the video is always black, audio plays fine (but no VS controller anymore)
Happens in all scenarios:
- if pressing Next icon
- if leaving the player to go to next episode automatically
- if pressing Play on the button that appears in last seconds
Even if playback speed is 1.0, it's still affected.
To recover from this state, only CTRL+F5 helps or reopening the page.

Tried on Firefox with the fork (v0.5.1) and it works fine (all cases).
Tried with VS off in Chrome: works fine.

It might be player specific (HBO GO), which I know it's hard for you to reproduce, but creating the ticket, maybe others have the problem too.

**Comment by jacobcolbert** [comment]
I can't reproduce. I use HBO GO a lot and always works fine for me. Has this always happened or a new problem? What do you mean by the first 2 options? I don't have a Next icon other than the box that appears in the last few seconds. A screenshot might help me understand. Also can you open up the console (Ctrl-shift-J or Ctrl-option-J) and see if there are any errors logged when this happens?

**Comment by mariusi7** [comment]
By Next icon, it's either '>|' https://i.imgur.com/9MADRb3.png or the Next button that shows in the last seconds. 
It didn't happen until about 2 months ago.
Yes, there's an uncaught error in the inject.js script: https://i.imgur.com/OmwxFx2.png
@igrigorik

**Comment by mariusi7** [comment]
Also funny is I added that case in issue 199 because it would not play at all at that time, but it seems things have improved since (it works without it too)? The localizion is Romania.
Anyway, with the latest source code from master, I just can't reproduce this bug, it just works (with or without the 'case').

**Comment by mariusi7** [comment]
I cloned https://github.com/igrigorik/videospeed/tree/2310423c949e84720f15a320e96cece1a575c551 (where the line is 219 like in v0.5.6) and commented the hbogo 'case'.  But it doesn't help, the next episode still doesn't play, different error now: https://i.imgur.com/8ckC7SR.png

**Comment by mariusi7** [comment]
Can't reproduce in master
