### ISSUE TITLE
Repeated playback freeze in Netflix on some videos

### ISSUE THREAD

**Issue by mariusi7** [igrigorik/videospeed#481]
After a few minutes of playing a video (2.0-2.5x), the video stutters, eventually freezes completely (on last frame, no audio). The only way to recover is to jump forward in the video, but after few seconds it breaks again and so on.
Doesn't happen if leaving the player at 1.0.
Doesn't happen for all videos, only some (but many).

For example Planet Earth, episode 1. It stopped now at 8:16, then at 11:58.. 
Changed the speed to 1.0 and left it to play the entire episode: all fine.

It worked fine in 2018 and before, I have the issue since around Feb 2019.
It also affects a Chromebook with ChromeOS and this extension (tried back in April).

I did see some other users mentioning similar issues in the last months and it was caused by the WidewineCdm plugin, see e.g. https://forums.geforce.com/default/topic/1048828/netflix-and-amazon-stuttering/?offset=285#5967923
But all fixes related to Widewine didn't help me; and probably can't explain why it works fine at 1.0 or with VSC off.

**Comment by mariusi7** [comment]
No error in the console when it happens: https://i.imgur.com/r875bdp.jpg

**Comment by mariusi7** [comment]
Nothing logged with all levels set (incl Verbose), nothing for specific js contexts including vsc.

**Comment by mariusi7** [comment]
I can't reproduce in master, but I'll watch some more things today and see for sure..

**Comment by mariusi7** [comment]
> I can't reproduce in master, but I'll watch some more things today and see for sure..
Still happening with latest sources (was in a middle of the 2nd episode of The Chef Show)

**Comment by mariusi7** [comment]
Any idea? Can't use video speed at all on a Chromebook, it just freezes after a few seconds. Now workaround here like switching to Firefox..

**Comment by jacobcolbert** [comment]
Sorry, but I've got nothing. I've never had anything like this unless going past what's buffered which I assume you've ruled out. With no errors or anything not really sure how to proceed.

Is this still working on the master? I'm not actually sure what version is live right now so I guess if you can diff them maybe we can investigate the root of the issue?

**Comment by jacobcolbert** [comment]
Another idea I guess is to try doing it manually with vsc turned off and see if you still have the issue. 
i.e. go to console and find the video tag and change its playback rate
 var video = document.querySelectorAll('video')[0];
video.playbackRate = 2;

**Comment by mariusi7** [comment]
> Another idea I guess is to try doing it manually with vsc turned off and see if you still have the issue.
> i.e. go to console and find the video tag and change its playback rate
> var video = document.querySelectorAll('video')[0];
> video.playbackRate = 2;
Thx, forgot to check this. Did it now, and video does freeze, most times in the first minutes of the video. The buffer scroller is at a sufficient time forward, but maybe it's misleading. Because after a few seconds of being frozen completely, the audio recovers and keeps going fine, with the last video frame still stuck; then eventually the video also recovers. This is on a Chromebook with vsc0.5.6. On a PC with 0.5.6 or master version, it remains frozen (I can do more tests on PC  only next week)
![Screenshot 2019-06-16 at 07 38 07](https://user-images.githubusercontent.com/27129454/59559242-91ffa100-900b-11e9-8bda-aa1ff27af650.png)

**Comment by jacobcolbert** [comment]
Did this ever resolve itself? In any case if simply changing the playback rate via javascript causes the issue I think there is little hope of solving it in the extension as that is the core functionality of VSC.

**Comment by pedantique** [comment]
I'm having this same issue on a Chromebit with VSC 0.6.1. The issue does not seem to appear on the same videos on OS X.

Did anybody fine a solution?
