### ISSUE TITLE
I have a suggestion.

### ISSUE THREAD

**Issue by cnctiny** [igrigorik/videospeed#483]
I want to set the function with the arrow button, but it is not possible. Can't you make that possible?

**Comment by igrigorik** [comment]
In theory, yes. However, I think you'll find that this will conflict with a lot of default behaviors (e.g. skip ahead) on most video players, which we can't prevent or override.

**Comment by cnctiny** [comment]
Thank you for quick response. But I hope the function is possible. I think it's a matter of choice. Please.

**Comment by jacobcolbert** [comment]
Encouraging unpredictable behavior seems like a recipe for sadness.
