### ISSUE TITLE
Doesn't Work on bilibili H5 video player

### ISSUE THREAD

**Issue by edok10** [igrigorik/videospeed#485]
Unable to control speed on www.bilibili.com

**Comment by jacobcolbert** [comment]
Working for me. Can you provide a link to a video that doesn't work for you? Does the video controller appear? Are you sure it is not using flash? (You can right click on the video to tell usually) Do any errors appear in the console (Ctrl-Shift-J)?

**Comment by edok10** [comment]
Sometimes work sometimes doesn't, and I can't find the reason.
But now, there is no problem for the time being.
