### ISSUE TITLE
Unable to use in adobe flash player videos

### ISSUE THREAD

**Issue by jareena2912** [igrigorik/videospeed#488]
I am unable to use video speed controller in Adobe Flash Player videos.

**Comment by jareena2912** [comment]
Hi 
I am unable to use video speed controller in Adobe Flash Player videos.
Please help.
Thanks,
Jareena

**Comment by jacobcolbert** [comment]
This extension only works for html5 videos. If you follow the instructions on the homepage you can force some videos to be html5 by disabling flash player. Otherwise there is nothing we can do to help.
