### ISSUE TITLE
feature request: per site playback speed

### ISSUE THREAD

**Issue by jojoman02** [igrigorik/videospeed#490]
I watch videos at 1.4-1.8 speed. this breaks when watching live channels like youtube live and other websites. I switch between 1.0 and 1.4 speed and often on live content I've noticed it's very difficult to change the speed (hotkeys don't work sometimes and mouseover is challenging). a per site/page storage of playback speed would be great.

**Comment by jacobcolbert** [comment]
This should be very easy to do. I thought about doing it when making it track the source of videos for other reasons. I think it would be unexpected behavior to have as a default, but could be an option. But i'm always worried about option bloat. I'll defer to you here @igrigorik 
![makeitanoption](https://user-images.githubusercontent.com/4524407/60309808-c03f8380-991d-11e9-889e-d828258df90d.jpg)

**Comment by igrigorik** [comment]
My biggest concern is not the implementation, but the fact that this would effectively introduce another history log of sites that the user has visited, which is something I have strong aversion to.

See related discussion in https://github.com/igrigorik/videospeed/issues/287 — let's continue there.
