### ISSUE TITLE
"Reset speed not being remembered" is back for me.

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#491]
Repeat? of #413 

I go to a video, set my speed to 1.75 for example. Some time in the video reset it to 1x with the reset button. Then open a new video in a new tab. On the new video I hit reset again, expecting it to go to 1.75x. No, instead it goes to 2.5, as set by my "preferred speed".

Basically the same as [a previous comment of mine](https://github.com/igrigorik/videospeed/issues/401#issuecomment-448686090)

Chrome Version 76.0.3809.46 (Official Build) beta (64-bit)

EDIT: The extension also keeps getting corrupted for me. It has happened 3-4 times now, roughly once a week. I notice the controller missing, go to extensions and chrome tells me the extension may have corrupted.

**Comment by igrigorik** [comment]
I believe this was due to Chrome issues, which should be resolved now. If it's still a problem, lmk.
