### ISSUE TITLE
Rewind/Advance are not working/when rewinding video, it rewinds to the beginning

### ISSUE THREAD

**Issue by trp488** [igrigorik/videospeed#493]
Thx

**Comment by jacobcolbert** [comment]
They work fine for me. Can you give any more details on how to replicate it? Screen shot of your settings page? Is this on every website or just some?

**Comment by trp488** [comment]
Working now, Thx









Thomas R. Pugh
48 Edgehill Rd.
Little Rock, Ar 72207
501-920-4520 iPhone
