### ISSUE TITLE
Doesn't work with Youtube on ChromeOS

### ISSUE THREAD

**Issue by crunchykiwi** [igrigorik/videospeed#498]

**Comment by naturallymitchell** [comment]
it works for me

which versions of everything are you using?
when did it start?

can you upgrade?

**Comment by crunchykiwi** [comment]
Chrome: 75.0.3770.144. Looks up to date.
Videospeed: 0.5.7. Looks up to date.

I don't think it's ever worked on this Chromebook since I got it a few
months ago (Chromebook pixel 2).

**Comment by naturallymitchell** [comment]
Oh, oops.  I got confused somehow.  I have the same OS and extension versions as you, and it's also not working.  I thought it stopped working from some config error I made about 2-3 weeks ago, but looks like we'll need to trace back which change broke it.

Do you have any more ideas?

**Comment by crunchykiwi** [comment]
Not really, sorry :T.

**Comment by crunchykiwi** [comment]
Oh, actually, I noticed that it seems to work when I first start the
chromebook, but when I let it sleep overnight it seems to stop working.

**Comment by ice1080** [comment]
Not sure if this is related or not, but mine keeps getting disabled in Chrome. I have to go back to the extension page and it then tells me that the extension has been disabled and asks if I want to re-enable it.

Chrome version 76.0.3809.100
OS Version Ubuntu 18.04.3 LTS

I have also seen this in the same chrome version within Mac OS Mojave V10.14.6

**Comment by jvschiavo** [comment]
It works great for me on my ChromeOS and always have. Samsung Chromebook 2.
Maybe your guys problem could be https://github.com/igrigorik/videospeed/issues/492

**Comment by crunchykiwi** [comment]
Oh! It could also be that I'm usually logged in with more than one profile,
the second of which does not have VSC installed. I've only logged into the
VSC one and for 24 hours there hasn't been an issue.

**Comment by crunchykiwi** [comment]
This is still a problem for me.

**Comment by jacobcolbert** [comment]
Can you tell me more about the problem? What does not work mean? Is it only youtube?

**Comment by crunchykiwi** [comment]
The UI doesn't appear and the keyboard shortcuts don't do anything.
I don't visit a lot of video sites, but Netflix still works even when
Youtube stops working.

**Comment by jacobcolbert** [comment]
When it happens next can you open the console (ctrl-shift-J) and see if any errors are reported. Otherwise I've got no ideas how to debug.

**Comment by crunchykiwi** [comment]
Only warnings :|. The only one that isn't obviously irrelevant is:
VM233 watch:56 <link rel=preload> must have a valid `as` value

**Comment by vapier** [comment]
hmm, what if you create a new tab to the same URL ?  i found some of my long running tabs (like pinned ones) would stop working.  reloading in the tab itself didn't help, but creating a new tab and navigating to the same URL made it work again.

i saw this same behavior with another extension that injects custom css/js.  it started failing on the long running tab, even if i reloaded it.  but creating a new tab allowed the injection again.  in that case, the JS console for the extension showed that it was Chrome itself denying things (saying the extension didn't have permission to access the site).  i didn't save the exact error message, but i'll try and grab it next time around.

**Comment by crunchykiwi** [comment]
That's ironic -- the problem went away for me just a few days ago. Less
than a week maybe?

**Comment by vapier** [comment]
just happened again with pinned tabs that got discarded/reloaded.

from my extension i'm seeing `Unchecked runtime.lastError: This page cannot be scripted due to an ExtensionsSettings policy.`.

the videospeed extension doesn't have a bg page to inspect (since it injects everything via the manifest).  the page's JS console itself doesn't show anything interesting.

creating new tabs isn't helping anymore :/.

Chrome Version 80.0.3987.0 (Official Build) dev (64-bit)

**Comment by vapier** [comment]
restarting Chrome allowed it again.  i've filed this upstream as a bug for Chrome.
https://crbug.com/1036393

**Comment by ChadBailey** [comment]
Can anyone say if this has been resolved?

**Comment by igrigorik** [comment]
I believe this should be resolved now, please reopen if still an issue.
