### ISSUE TITLE
Overlay position in video

### ISSUE THREAD

**Issue by TheSuitIsNotBlack** [igrigorik/videospeed#50]
Is there a way to re-position the speed overlay? In my opinion i'ts in an inconvenient place right now in the top left, and often covers up some of the content (most notably when it's on top of text in the video). It seems like a much less busy area would be the upper right, or even the bottom right. Is this possible?

**Comment by igrigorik** [comment]
Not today. I did a brief investigation into making it draggable, such that you can position it anywhere, but that didn't pan out too well.. It was broken on many sites and I abandoned that. That said, that's probably more a comment about my implementation. 

FWIW, I don't think changing the position would from left to right would meaningfully change anything: there are edge cases anywhere you put it, so you can't win either way; exposing more manual overrides is also not great. As such, I'm inclined to mark this as "wontfix".

**Comment by TheSuitIsNotBlack** [comment]
Fair enough. It's just been my experience that there's rarely much going on in the upper right, but that may depend upon the types of videos I watch. It's mainly an issue when the video has text, since it's a standard to start text from left to right in the upper left.

**Comment by Wisdawn** [comment]
I remember in the past suggesting the ability to control the opacity or transparency of the extension via a slider, which may help in such an issue, and also allow new users to quickly spot where the extension is. An alternative implementation is to also make the extension very obvious, almost in the way when first installed, then right after the user hovers the mouse pointer over it then moves the cursor away, the extension fades into a minimal transparency, to make way for the videos being watched and rely on the fact that the user already knows where it is now, so the extension doesn't need to be too obvious anyway. From there on, it would fade with mouse-hover off, and gain opacity with mouse-hover on.

**Comment by igrigorik** [comment]
@TheSuitIsNotBlack interesting, I'm used to subtitles in bottom-center. Or, are you referring to slides and such? FWIW, for YT note that we do hide the controls once focus is removed from the video itself.

**Comment by TheSuitIsNotBlack** [comment]
No, I don't use subtitles. I'm referring to actual text used in the videos. I've been taking some programming courses on youtube lately, and they always have the text content beginning right where the overlay is.

**Comment by igrigorik** [comment]
@TheSuitIsNotBlack fwiw, note that if you move focus away from the video the title bar _and_ the video controls should automatically disappear.

**Comment by igrigorik** [comment]
@TheSuitIsNotBlack fwiw, note that if you move focus away from the video the title bar _and_ the video controls should automatically disappear.

**Comment by TheSuitIsNotBlack** [comment]
Oh really? That doesn't seem to be the case on my end. Are you saying if I click outside of the video it should go away?

**Comment by igrigorik** [comment]
@TheSuitIsNotBlack yes, or if you don't move your mouse.. when the title bar disappears (youtube functionality), so should the controls.

**Comment by Wisdawn** [comment]
This is how it looks like on my end:
![capture](https://cloud.githubusercontent.com/assets/11066751/8438098/6b281eb8-1f6c-11e5-93fb-5e8829fcb653.png)

So the controls significantly fade out, but they don't exactly “disappear” completely when on a light background. I assume that TheSuitIsNotBlack watches videos with a light background [and] text in that corner.

**Comment by Wisdawn** [comment]
I haven't had a problem [yet], at least not like TheSuitIsNotBlack's problem. At the same time, I'm not sure that making the controls completely disappear on-mouse-out would be the ideal solution; invisible controls or an app are effectively non-existing controls or a non-existent app in the eyes and mind of a new user, for example.

**Comment by Wisdawn** [comment]
@igrigorik Maybe an option in settings that allows the user to make the controls / extension [completely] invisible on-mouse-out? This way, only users who really need that option or the invisibility can have it, without affecting the functionality and visibility of the extension for other users, especially new ones.

**Comment by igrigorik** [comment]
@Wisdawn ah, right sorry.. If you go into fullscreen you'll see the controls disappear with the titlebar after some period of inactivity. FWIW, I'm not keen on exposing yet more toggles in settings -- this is an easy but all too often abused way out.

**Comment by truth1ness** [comment]
Ugh, this is is really annoying me. In many embedded youtube videos they disable keyboard controls and I can't access the overlay because the video title covers up the overlay on mouseover. Being a few pixels lower or allowing the user to pick a corner would be helpful. Perhaps there is a way to make the overlay sit on top of the title? Somehow the video title is taking precedence over the overlay on embedded videos. 

This page is an example of where I can't manipulate the speed controls either way: http://www.cbc.ca/news/trending/weatherman-liam-dutton-pronounces-llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch-perfectly-1.3221414

**Comment by igrigorik** [comment]
@truth1ness should be resolved via e405a5cdbb3582d926461cd97d1b76e45a2ae197, I'll push out 0.2.6  this weekend with this fix.

Re, draggable: I've tried implementing this and the complexity + compatibility with all the various players is a nightmare.. The simpler we keep things the more reliably the extension will work. Closing this as a wontfix.
