### ISSUE TITLE
No controls when viewing video directly

### ISSUE THREAD

**Issue by xavier2dc** [igrigorik/videospeed#506]
Hi, I noticed recently that when visiting videos with a direct URL, i.e., the URL shown in the address bar is some https://.../video.mp4, the controls no longer show up even when triggered.
However, the shortcuts to increase/decrease the speed are still working.

When debugging, I noticed that this condition is true:https://github.com/igrigorik/videospeed/blob/5641369385cf4175e308c8e188c9bb70226a12da/inject.js#L206
which inserts the `vsc-nosource` class and effectively hides the controls.
I'm not sure why this.video.src is == "" while the video is effectively playing, but so that breaks the controls.

Despite this code being introduced 4 months ago, I have seen the controls on videos watched directly in the last few months, so it's possibly a browser change.

**Comment by mjjones90** [comment]
I also started having this issue with local files within the last few weeks and commented elsewhere about it. For now, I'm just removing "vsc-nosource" from the code using the Inspect tool. It's a bit annoying to have to do it for each video, though.
