### ISSUE TITLE
Controller disappeared

### ISSUE THREAD

**Issue by 1160300208** [igrigorik/videospeed#507]
### Problem
When I watched videos on https://www.icourse163.org (https://www.icourse163.org/learn/HIT-1002531008#/learn/content?type=detail&id=1005200290&cid=1006621576), the controller icon disappeared although other functions were able to use.
### Statistics
[info]check autoplay support
[info]check autoplay complete:true
[info]onIdle
[info]load moivedata
[info]create video node complete
[info]current item:{"quality":1,"qualityName":"标清","urls":["https://jdvodrvfb210d.vod.126.net/mooc-video/nos/mp4/2018/01/23/1008379058_a48ec25a1a82436db07dfc7ea8ec6c23_sd.mp4?ak=7909bff134372bffca53cdc2c17adc27a4c38c6336120510aea1ae1790819de886a195042a8a51b71a1965523246c65a7c6f158e2d4e673a89503445c7121cfa3059f726dc7bb86b92adbc3d5b34b132f5af3ac0a55d46c581643b9e21e82f9fa9f9f7a47c7d084cef6fcf98b39bf4de"],"fileType":"mp4","encrypt":false}
[info]onPlay
[info]_onvideoPlaying
[info]_onvideoWaiting
[info]onNewMovie, url:https://jdvodrvfb210d.vod.126.net/mooc-video/nos/mp4/2018/01/23/1008379058_a48ec25a1a82436db07dfc7ea8ec6c23_sd.mp4?ak=7909bff134372bffca53cdc2c17adc27a4c38c6336120510aea1ae1790819de886a195042a8a51b71a1965523246c65a7c6f158e2d4e673a89503445c7121cfa3059f726dc7bb86b92adbc3d5b34b132f5af3ac0a55d46c581643b9e21e82f9fa9f9f7a47c7d084cef6fcf98b39bf4de, quality:1
[info]get video meta, duration:2715
[info]_seek
[info]html5 video do autoseek
[info]onPlay
[info]_onvideoSeeking
[info]canplay
[info]_onvideoPlaying
[info]try to play success
[info]try to play success
[info]try to play success
[info]canplaythrough
[info]onPause
[info]_onvideoPause
[info]webkitRequestFullScreen

**Comment by mjjones90** [comment]
It's an issue with "vsc-nosource" somewhere in the code. If you watch videos on that site often and need a workaround, open the Inspect tool, search for "vsc-nosource," and delete it. I checked the video you linked and it works.

**Comment by igrigorik** [comment]
Please reopen if you can provide more details.
