### ISSUE TITLE
Speed repeatedly drops to 0.00

### ISSUE THREAD

**Issue by Benu-Athanasia** [igrigorik/videospeed#510]
As the title says, the speed keeps suddenly jumping down to 0.00 every 5 minutes or so. So far I'm seeing this on HBO GO and VRV.

It's more of a nuisance than anything, but HBO is seeing it as a streaming error and giving me this every few times it drops, "Can’t Play Video We’re having trouble playing this video. Please try again later."

I *think* it might be connected into the commercial breaks somehow. At least that's how it looked on VRV. Not sure about HBO GO since I'm really new to both sites.

**Comment by Benu-Athanasia** [comment]
Disneynow is now doing it as well.

**Comment by igrigorik** [comment]
I believe this should have been addressed in one of previous releases. Closing, please reopen if the problem is still there.

**Comment by Benu-Athanasia** [comment]
Nope. Error is still there and has spread to Disney Now.

**Comment by igrigorik** [comment]
Hmm. Do you have any public test URLs?

**Comment by Benu-Athanasia** [comment]
Do you mean the url to a video I've encountered this problem on? Because it's done it several times on this video despite my download speed being 56 mbps
[https://disneynow.com/shows/star-wars-resistance/season-02/episode-12-212/vdka15054931]

**Comment by ChadBailey** [comment]
I have tested this URL and it is working as expected. Can you confirm if it's fixed?

**Comment by ChadBailey** [comment]
Going to close this for now, please reopen if you're still experiencing a problem.
