### ISSUE TITLE
PDF documents fail to display

### ISSUE THREAD

**Issue by grahamoz** [igrigorik/videospeed#511]
Recently I have noticed that this is causing website hosted PDF documents not to display. I only get a blank grey browser tab.

**Comment by jacobcolbert** [comment]
Can you post an example link? I've never seen this problem.

**Comment by grahamoz** [comment]
Hi. I just tried it again and the PDF display is now working. Previously I had to disable the video speed plugin to get PDF's to display. Maybe a recent update has fixed the issue.
Thank you.
