### ISSUE TITLE
conflict on playing/pausing shorcuts

### ISSUE THREAD

**Issue by alfredcai** [igrigorik/videospeed#513]
Hi, I often view some websites which contain many audios/videos on one page. This extension doesn't work very well. When I press "Play" or "Pause" shortcut on such pages, the extension would work on all audios/videos.

So I wonder how to choose and control one of them?

**Comment by jacobcolbert** [comment]
The only way to only control one video with VSC is with the mouse using the overlay. If you have suggestions on how to handle this better I'd think about it.
