### ISSUE TITLE
Controls work, but speed not displayed, on Bitchute

### ISSUE THREAD

**Issue by JimGroat** [igrigorik/videospeed#515]
The controls work on bitchute.

On youtube, the speed is shown at the top left of the video.

The speed isn't shown on bitchute.

Thank you.

**Comment by thewheat** [comment]
Think this could be solved with https://github.com/igrigorik/videospeed/pull/529 (that has been merged so perhaps the next release will include it)

Using the code changes locally does allow the controls to show 
![image](https://user-images.githubusercontent.com/892961/66263547-3e69cb00-e827-11e9-93f6-00ee0de6e5a6.png)
