### ISSUE TITLE
Video Speed Controller UI overtakes fixed navbars on some sites

### ISSUE THREAD

**Issue by gruiz17** [igrigorik/videospeed#516]
Probably not a world-ending issue, but still an interesting visual quirk -- when some video streaming sites have a fixed navbar at the top, and you scroll down, the UI of VSC scrolls such that it appears on _top_ of the navbar.

Here's an example of what I mean by title, on Rakuten Viki:

![uiBug](https://user-images.githubusercontent.com/2757082/64905274-90855980-d68a-11e9-8256-9c2bfde760e0.gif)

I'm guessing this is borne of the fact that `z-index` on `#controller` in `shadow.css` [is set to 9999999](https://github.com/igrigorik/videospeed/blob/master/shadow.css#L24).

Interestingly, this doesn't happen on YouTube, even though YouTube's navbar `z-index` is set to 2020.

If possible, what ways are there to make sure there's some consistency to the scrolling behavior with VSC wrt sites with fixed navbars?

---

Steps for reproduction:

1. With VSC, Go to a video on Viki
2. Scroll down

**Comment by ChadBailey** [comment]
Great bug report, thanks for the detail! I went ahead and took a stab at fixing this one since it seems simple enough. I've tested my fix on as many sites as I could think of, but if you know of any other examples please do share.

**Comment by ChadBailey** [comment]
I was able to fix this bug in https://github.com/igrigorik/videospeed/pull/539 but I realized this will probably be the lesser evil than having some situations where the controller is unreachable. For this reason, I closed my request and it was not merged in.

**Comment by ChadBailey** [comment]
I'm labeling this as won't fix and closing because this behavior is preferred to not being able to access the controller at all. Still hoping one day we can come up with a clever way to do both
