### ISSUE TITLE
Pressing key for preferred speed, if you are already on preferred speed, causes speed to reset.

### ISSUE THREAD

**Issue by JimGroat** [igrigorik/videospeed#517]

**Comment by Skarrum** [comment]
I agree, while this is an issue it's rather inconvenient if I forget what time I'm at and hit the key bind for that time, or I accidentally double-click. While it's not urgent I would love to see an option to at least toggle this feature on or off in the settings menu.

**Comment by mjjones90** [comment]
What do you mean by "reset?" Does it revert back to 1.0 speed or whatever speed you were on before switching to the preferred speed? The preferred speed key is intended to "toggle between current and user configurable preferred speed" according to the Read Me file.

**Comment by jacobcolbert** [comment]
Yeah also not sure what you mean here

**Comment by Skarrum** [comment]
I just assumed that he was talking about the toggle, and what I meant was that it would be nice to be able to disable that feature.

**Comment by igrigorik** [comment]
You can now disable / remove default shortcuts. Resolving.
