### ISSUE TITLE
Need to reload every time

### ISSUE THREAD

**Issue by solzard** [igrigorik/videospeed#518]
I restrict this extension's site access to "on specific sites" and added YouTube as `*://youtube.com/*`; However, every time opening YouTube videos, I need to click the extension's icon and reload a page. 

Environment:
* Chrome: Version 77.0.3865.75
* macOS: 10.14.6

**Comment by jacobcolbert** [comment]
I'm not sure what you mean. The extension icon in the extension tray does not have the option to reload. What exactly do you have to do?

**Comment by igrigorik** [comment]
Closing, please reopen if the problem is still there.
