### ISSUE TITLE
Please add fast forward button

### ISSUE THREAD

**Issue by FrozenFury** [igrigorik/videospeed#52]
You have a backwards button, but add forwards button. thx

**Comment by igrigorik** [comment]
This was added in https://github.com/igrigorik/videospeed/pull/49, but it's not live in public extension yet. If you want to play with it, install the extension from source.

**Comment by FrozenFury** [comment]
How do I install extension from source?

**Comment by igrigorik** [comment]
You'll have to checkout the github repository onto your computer and then follow instructions on: http://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system

**Comment by FrozenFury** [comment]
Thanks!

**Comment by FrozenFury** [comment]
Oh I have another suggestion. Allow it so that arrow keys can be configured as keys so that you can use arrow keys to move forward and backward.
