### ISSUE TITLE
Branch for privacy concerned users

### ISSUE THREAD

**Issue by frankclaassens** [igrigorik/videospeed#522]
Hi,

I want to second the request that came from the closed issue below:
https://github.com/igrigorik/videospeed/issues/360

@kamalmarhubi  does have a point, and you do seem to have a user-base who are more privacy focused that your overall user base. Would you consider implementing this change in a new branch? If you are, then I am willing to keep it inline with master during every release.

And @kamalmarhubi already said he would have a go at the implementation.

Please do look into this...I can assure you that you will attract a lot more users and gain more trust from others should you do this as it shows goodwill.

Cheers

**Comment by igrigorik** [comment]
There is a false dichotomy here, there are not two group of users and privacy is something we've paid close attention to throughout the history of this extension. I understand the perception of "all websites" grant but you can audit the code and verify how this grant is used. 

Maintaining a separate branch is neither a good product or maintenance decision. If folks are interested in contributing time and expertise, ptal at https://github.com/igrigorik/videospeed/issues/479 — I think that's the right place to start. As a side note, if you do, please open a design discussion first, so we can iron out how the interface and opt-in would look like for existing users.
