### ISSUE TITLE
Not working on app.pluralsight.com

### ISSUE THREAD

**Issue by jlauerswi** [igrigorik/videospeed#525]
Pressing D or S (etc.) worked until 1 month ago or so. It now immediately resets to 1.00 playback speed each time. So if D is pressed, it will briefly go to 1.10 speed, but then immediately revert to 1.00 speed. Same for S. Also, "Speed setting saved: 1.10" is logged in the console, and then "Speed setting saved: 1.00" instantly after.

It works for other sites like Youtube still, so it's definitely a PluralSight-specific problem.

**Comment by jacobcolbert** [comment]
Some websites unfortunately monitor playback conditions and revert any changes. While there might be workarounds we are not interested in playing a bunch of domain specific cat and mouse games. Sorry!

**Comment by jlauerswi** [comment]
Understood. I was able to write a helper extension as a workaround. Perhaps you could add functionality for users to add site-specific workarounds without having to create a helper extension as I did.

**Comment by jacobcolbert** [comment]
Can I see the fix you made? Curious what you did.

I definitely see the argument for this, but the issue is when the fix breaks in the future then people will be upset. If the fix were general enough without decreasing performance on other sites I could perhaps be convinced.

**Comment by jlauerswi** [comment]
[This is the repo.](url)

Yeah I can see it breaking pretty easily. It's not great, but it's better than using PluralSight's speed slider :).
