### ISSUE TITLE
Disable website keybinds for viewing controller

### ISSUE THREAD

**Issue by Skarrum** [igrigorik/videospeed#526]
So I found a keybind layout I enjoy with num0 showing and hiding the controller, num1-9 setting the speed from 1 to 9 percent sequentially, and num+ and num- changing it by .10 speed in either direction. On all the other options you can disable website keybinds for each individual action, but the same doesn't apply to the show/hide controller option. For example, since I can't disable that if I want to view my controller while watching Youtube, or another site with similar keybinds it will send me to the beginning of the video.

**Comment by jacobcolbert** [comment]
This is an oversight. Not sure why this was implemented seperately. Will take a look soon hopefully.

**Comment by thewheat** [comment]
Hope it was ok that I created a PR for this 😄  https://github.com/igrigorik/videospeed/pull/533
