### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by FrozenFury** [igrigorik/videospeed#53]
Allow arrow keys to be configured for fast forward and rewind.

Add a turn off the lights function so that everything but the video is darkened. See Turn Off The Lights extension for more details.

Thx

**Comment by igrigorik** [comment]
- You can configure the keys in options already. 
- FWIW, "turn off the lights" is out of scope for this extension; my goal is to keep this lean and mean. The fact that there are other extensions already providing this functionality is yet another reason to avoid duplicating it.

**Comment by FrozenFury** [comment]
How do I configure left and right key? When I try nothing shows up. Here's
a gif of me trying to do it:
http://gyazo.com/ecd1ece447e9d0768c9e54e9c9973d07

**Comment by igrigorik** [comment]
Ah, right.. today we restrict shortcut keys to anything that inserts a character (keypress). To support arrow and other keys we'd need to update logic to use keydown.
