### ISSUE TITLE
mytuner-radio.com: audio speed control not working

### ISSUE THREAD

**Issue by alon91** [igrigorik/videospeed#530]
Seems like VSC works for some audio players, not for others. I looked for documentation on which players are / aren't eligible but couldn't find anything.

- Audio stream sites where VSC works:
  - https://tunein.com/radio/Sports-Radio-1043-The-Fan-s33298/
- Audio stream sites where VSC does not work:
  - https://player.radio.com/listen/station/kroq
  - https://mytuner-radio.com/radio/la-buena-1019-fm-417308/

Any guidelines to follow here?

**Comment by thewheat** [comment]
For https://mytuner-radio.com/radio/la-buena-1019-fm-417308/ it looks like they are using [SoundManager](http://www.schillmania.com/projects/soundmanager2/doc/) for the playback 

Running `soundManager.versionNumber` in console gives version "V2.97a.20140901" (which I think means 2014). 

SoundManager does support setting playbackRate but I think the version they are using is an old one that doesn't support it http://www.schillmania.com/projects/soundmanager2/doc/

* * * 

The https://player.radio.com/listen/station/kroq doesn't load for me as it looks geolocked but I do see mention of a "TD SDK Player"  which means it could be similar to sondmanager above where it is a custom library that is loading audio in a custom fashion 
![image](https://user-images.githubusercontent.com/892961/66696717-eccab000-ed00-11e9-9dfe-c082bced557a.png)

**Comment by alon91** [comment]
Thanks so much for doing the research, @thewheat! 

Sounds like generally speaking the audio player has to support certain properties (perhaps just `playbackRate`) and that some players do others (older or custom) do not.

My use case is a bit niche -- I'm trying to use VSC to sync AM radio streams in my browser with video on my TV. The good news is that *lots* of different sites tend to stream the same radio station so at least I can experiment to find which ones use players that are compatible with VSC.

Thank you again!

**Comment by thewheat** [comment]
You're most welcome @alon91 !

> I'm trying to use VSC to sync AM radio streams in my browser with video on my TV

That's an Interesting use 😄 Hope you are able to find different sites to achieve what you need 🙌 

Or if somebody with more knowledge of ways to get things to work that would be great too! I'm so dependent on VSC that I wouldn't want to watch video/listen to audio without it 😂
