### ISSUE TITLE
Enable use of "arrow keys" for shortcuts

### ISSUE THREAD

**Issue by habassa5** [igrigorik/videospeed#532]
Seems the most obvious keystroke shortcuts would use arrows keys instead of what appear to be random letters... I've tried to change the default shortcuts to utilize the arrow keys but they don't take. Please fix.

**Comment by thewheat** [comment]
I do see that the code filters out only certain keypresses. I've added support for arrow keys and function keys in this PR https://github.com/igrigorik/videospeed/pull/534 if the authors are happy to support them 👍
