### ISSUE TITLE
Firefox add-on is corrupt

### ISSUE THREAD

**Issue by bethrobson** [igrigorik/videospeed#535]
Firefox add-ons - when I try to install into firefox from addons.mozilla.org, I get a message saying it's corrupt.

"Installation aborted because the add-on appears to be corrupt" on addons.mozilla.org.

**Comment by thewheat** [comment]
Hi @bethrobson 👋just confirming, the extension you're referring to is https://addons.mozilla.org/en-US/firefox/addon/videospeed/ right? 

I've just installed it on my end so I'm not sure what could be wrong there 🤔
![image](https://user-images.githubusercontent.com/892961/66922265-4d3b5380-f059-11e9-8505-da002b75a94b.png)

- Perhaps the install got corrupted somehow. Clearing caches may https://support.mozilla.org/en-US/kb/how-clear-firefox-cache
- There seems to be other people experiencing the same issue with other extensions which makes me think it could even be a Firefox issue https://support.mozilla.org/en-US/questions/1264500
- Lastly I believe the Firefox extension is a modification from this Chrome extension repository. So if the issue still persists I think the right place to ask would this link https://github.com/codebicycle/videospeed/issues which is issues for the Firefox extension 👍

**Comment by mariusi7** [comment]
I have it installed v 0.5.1 , last updated April 15, 2018 and it works fine
You could download this version ..
