### ISSUE TITLE
How do i blacklist the homepage of a website but not the rest of the website? 

### ISSUE THREAD

**Issue by throwaway2342** [igrigorik/videospeed#542]

**Comment by thewheat** [comment]
Hi @throwaway2342 👋Do you have an example of the website in question?

**Scenario 1**
If the homepage is `domain.com/index.html` you could add that to the blacklist and it wouldn't match on `domain.com/page1`. 

**Scenario 2**
If this is something like `domain.com` is the homepage and the rest of the site is `domain.com/page1`, with the current implementation I don't think it is possible.

Currently the blacklist works on
- getting the current URL of the page you're on (e.g. domain.com/page1)
- and if it matches any line specified in your blacklist (e.g. domain.com)
Then it will not load
https://github.com/igrigorik/videospeed/blob/ac53d3ea2ba5ca508cc46e1295e81be36416e5af/inject.js#L288-L303

If https://github.com/igrigorik/videospeed/issues/167 is implement to allow regex in the blacklist, there could be a way to achieve Scenario 2 😃 Then using something like `domain\.com$` (depending on the implementation of the regex) would work for that scenario

**Comment by throwaway2342** [comment]
Hello, 

What is a regex?  
The homepage in question is "youtube.com" 

I tried putting domain\.com$ ........in the blacklist and it still doesn't block video speed controller on the homepage in question

**Comment by thewheat** [comment]
> What is a regex?
A regex is a regular expression and allows for more complex search and matching of text. Thus it would allow a more robust blacklisting solution. It is a bit technical to use so it can be a bit complicated as well 😅

> The homepage in question is "youtube.com"

Ah ok, if it is youtube I don't think this would be possible until we have an added feature that is discussed in https://github.com/igrigorik/videospeed/issues/167 to allow regex in the blacklist

> I tried putting domain.com$ ........in the blacklist and it still doesn't block video speed controller on the homepage in question

I'm afraid this won't work in the current version. We would need to add regex support to the extension first. Once that is implemented we can revisit this, unless anybody else has another way that this could be done

**Comment by ChadBailey** [comment]
Fixed in https://github.com/igrigorik/videospeed/pull/546

If the changes are merged in, the way you will do this is just add `/(.+)youtube\.com(\/*)$/gi` to your blacklist.
