### ISSUE TITLE
BUG: Youtube homepage search query acting weird when website keybindings are disabled in favor of videospeedcontroller key bindings

### ISSUE THREAD

**Issue by throwaway2342** [igrigorik/videospeed#543]
Lets say i am on youtube.com (the homepage) and I type in "asdfg" in the search bar.........lets also say I have keybindings set up for the extension namely "d" and "s".......upon typing this word in the search bar only "afg" shows up while s and d are cut out.......What do I do about this problem aside from blacklisting youtube or choosing not to disable key bindings for the extension....if it helps i have ublock, im using chrome and I have a mac. Please help me this bug is super annoying...I feel like the key bindings for this extension shouldn't always be enabled in certain areas especially in cases where you are typing things in a search query......please help..

**Comment by thewheat** [comment]
@throwaway2342 I don't seem to experience the bug you're seeing there 😕 See the GIF below (using the standard `s` and `d` keys): Am I doing anything differently to how you're searching on your end?

![2019-11-15 at 4 47 PM](https://user-images.githubusercontent.com/892961/68929663-c4cee080-07c7-11ea-9e36-6956b513196f.gif)

I'm also on a Mac and using the latest `Version 78.0.3904.97 (Official Build) (64-bit)` of Chrome. 
- Ublock origin https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm is my only other extension 
- But I also tried install Ublock https://chrome.google.com/webstore/detail/ublock-free-ad-blocker/epcnnfbjfcgphgdmggkamkmgojdagdnn and things seem to work fine as well 

Could you perhaps try disabling Ublock and any other extensions via chrome://extensions/ temporarily to see if there could be any weird conflicts? 

Maybe even uninstalling and reinstalling the extension could help?

**Comment by Eisys** [comment]
Even for testing, NO ONE should ever install uBlock
uBlock Origin is the only real version. The other is malware.

As for the issue, I also don't experience it. Works just like the gif.

**Comment by throwaway2342** [comment]
> Even for testing, NO ONE should ever install uBlock
> uBlock Origin is the only real version. The other is malware.
> 
> As for the issue, I also don't experience it. Works just like the gif.

I meant ublock origin

**Comment by throwaway2342** [comment]
> @throwaway2342 I don't seem to experience the bug you're seeing there 😕 See the GIF below (using the standard `s` and `d` keys): Am I doing anything differently to how you're searching on your end?
> 
> ![2019-11-15 at 4 47 PM](https://user-images.githubusercontent.com/892961/68929663-c4cee080-07c7-11ea-9e36-6956b513196f.gif)
> 
> I'm also on a Mac and using the latest `Version 78.0.3904.97 (Official Build) (64-bit)` of Chrome.
> 
> * Ublock origin https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm is my only other extension
> * But I also tried install Ublock https://chrome.google.com/webstore/detail/ublock-free-ad-blocker/epcnnfbjfcgphgdmggkamkmgojdagdnn and things seem to work fine as well
> 
> Could you perhaps try disabling Ublock and any other extensions via chrome://extensions/ temporarily to see if there could be any weird conflicts?
> 
> Maybe even uninstalling and reinstalling the extension could help?

This test should only be done on the youtube homepage (with ublock origin on-- and with cosmetic filtering enabled) and the settings for video speed extension should look similar to this 

<img width="631" alt="Screen Shot 2019-11-16 at 1 44 52 AM" src="https://user-images.githubusercontent.com/36759333/68991354-cd003d80-0812-11ea-9508-4136056dcf12.png">


With show experimental features ON and then you select "disable websites key bindings" 

It may not work the first time and if that is the case close the youtube tab, type youtube and re-open it the site again and type stuff relating to the key bindings in the search bar if it doesn't show up keep closing the tab and typing in youtube in the address bar again and again until the error does show up. But yea thats whats happening to me persay

**Comment by throwaway2342** [comment]
> @throwaway2342 I don't seem to experience the bug you're seeing there 😕 See the GIF below (using the standard `s` and `d` keys): Am I doing anything differently to how you're searching on your end?
> 
> ![2019-11-15 at 4 47 PM](https://user-images.githubusercontent.com/892961/68929663-c4cee080-07c7-11ea-9e36-6956b513196f.gif)
> 
> I'm also on a Mac and using the latest `Version 78.0.3904.97 (Official Build) (64-bit)` of Chrome.
> 
> * Ublock origin https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm is my only other extension
> * But I also tried install Ublock https://chrome.google.com/webstore/detail/ublock-free-ad-blocker/epcnnfbjfcgphgdmggkamkmgojdagdnn and things seem to work fine as well
> 
> Could you perhaps try disabling Ublock and any other extensions via chrome://extensions/ temporarily to see if there could be any weird conflicts?
> 
> Maybe even uninstalling and reinstalling the extension could help?

Even with ublock off and disabled the bug still occurs. I think it has something to do with the video ad on the main page and the keybindings over-riding the youtube search bar query

**Comment by throwaway2342** [comment]
should be done on the youtube homepage ONLY

**Comment by throwaway2342** [comment]
aka youtube.com

**Comment by jacobcolbert** [comment]
I was able to recreate this. As you've said it only crops up when there is an ad playing on the homepage. Taking a look now.
