### ISSUE TITLE
Javascript error: TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by biztechprogramming** [igrigorik/videospeed#549]
When opening a page with an iframe, I am getting this javascript error:

TypeError: Cannot read property 'remove' of undefined

It is coming from a script called inject.js, and when I remove the videospeed from Chrome, this error goes away.

**Comment by jacobcolbert** [comment]
Is it any page with an iframe or a specific one? Can you link to an example?

What line number is the error coming from in inject.js?

**Comment by igrigorik** [comment]
Please reopen if you can provide more details.
