### ISSUE TITLE
Default speed & indicator showing.

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#55]
I would like to see a feature where you can specify a default starting speed for every video. Since Youtube introduced higher speeds, I've been watching most videos at 1.25 or 1.5x so this would save a little bit of time in the beginning of every video. The 'remember playback speed' kind of works, but an overall default would be alot better.

Also I'd like to have an option for the speed indicator in the corner to be always visible when not in fullscreen. Like it used to be, before an update a while ago. Or maybe make it so that the speed indicator becomes visible when you change the speed with keyboard controls.

**Comment by igrigorik** [comment]
> The 'remember playback speed' kind of works, but an overall default would be alot better.

It's hard to quantify "a lot". FWIW, the last speed vs default are exclusive, which becomes tricky to explain to users; and I'm aware of a lot more users asking for history vs default -- this is anecdotal data :)

> Or maybe make it so that the speed indicator becomes visible when you change the speed with keyboard controls.

As a confirmation signal? What's the utility?

**Comment by Eisys** [comment]
'A lot' meaning sometimes a video is really slow going and I watch at 1.75x or even 2x. But for the next video those speeds are too fast. So a default of 1.25x or so would be better. But overall not a big deal, it's not too diffcult pressing the keyoard a couple times on every video.

And sometimes I change speed mid-video just to mess around or sth, but if I randomly spam the speed up to like 3x, I wouldn't know, since the indicator isn't showing. So if it was always there or became visible when changing, I would be able to go back to the speed I was watching at. Of course this also has a workaround; pressing the 'reset speed' and then hitting the speed up twice(If I was watching at 1.5x).

So, in the end, both 'issues' have a solution as is, it's just I feel if added, they would make it a better addon. Or maybe I'm just super lazy.

**Comment by igrigorik** [comment]
Fair enough, and don't get me wrong.. appreciate the feedback :)

Re, "check current speed" case: if you move the mouse you should see the speed indicator fade in.

**Comment by igrigorik** [comment]
Closing -- for now at least -- as this is a low priority feature.
