### ISSUE TITLE
Not working on CW

### ISSUE THREAD

**Issue by jpford13** [igrigorik/videospeed#550]
Trying to use this extension for the first time. I'm watching a show on the CW's online streaming site (cwtv.com), and the control panel for the extension pops up, but when I change the speed nothing happens. I have tried in Chrome, Firefox, and Safari. Has anyone gotten it to work for the CW or had similar issues?

**Comment by jacobcolbert** [comment]
This website unfortunately specifically blocks speed changes. And it is definitely not in scope to try to play cat and mouse with them getting around their blocks. Sorry!
