### ISSUE TITLE
automatic upload to chrome webstore via github actions

### ISSUE THREAD

**Issue by deef0000dragon1** [igrigorik/videospeed#551]
The current version of the video speed controller on the chrome store is listed as last updated on the 3rd of august. Automatic uploading would allow for quicker integration of feature additions and bug fixes.

With the introduction of github actions, simple CI/CD integration is really easy. 
Someone has already made an action to upload to the webstore even. 
https://github.com/trmcnvn/chrome-addon

I would be willing to write everything up to make it if it was tagged etc. if it would be included.

**Comment by igrigorik** [comment]
Neat. I like the idea, however I don't think we want to submit a new version on each PR. 

I often land PRs and then reserve a few weeks minimum for "burn-in", to ensure that we're not introducing regressions.. imperfect, but validated by dogfooding.

To your point though, we're definitely due for a new release!

**Comment by deef0000dragon1** [comment]
I know that you can set it up to trigger on tags, and on specific branches. I was thinking that every time a commit for master was tagged with a version number (v1.2.3 or whatever), then it would then push it up. 

that or have it so that any pr/merge into a "publish" branch would do it, though its a bit messier.

**Comment by igrigorik** [comment]
Ah, cool. Triggering on a tag makes sense 👍 

If you're willing to wire that up, that would be awesome.

**Comment by deef0000dragon1** [comment]
#555 will automatically trigger whenever a branch is tagged with a version number. I would have made it specifically master, but I think that there may be a bug with actions not respecting and conditionals right now. 

#556 will upload a version whenever a push is made to master.

I made 2 so that you can make a dev extension that can always be up to date, while still having a second one that will publish on tag. 

I did some testing to make sure that everything works out, but there are still some things that need to be done on your end. Specifically the args on the zip command, and the setting of the secrets.

**Comment by igrigorik** [comment]
Nice, thanks for wiring this up!

> Specifically the args on the zip command

What in particular do you have in mind here?

**Comment by deef0000dragon1** [comment]
I dont know what specifically does or does not need to be included in the zip that gets uploaded, and the .git/.github files are included.

**Comment by thewheat** [comment]
Not familiar if `zip` commands will be different when run in Github actions but I'd think you'd want the following which should zip files excluding hidden/dot files/folders. 
```
zip -r ./vscd.zip *
```

Pretty sure this is what's needed to include the core components without extra things like the `.git` directory (unless it is desirable to be included in the extension). But will let those more core to the project speak on what they'd prefer be included 👍

If you want to specifically include a hidden/dot file/folder you can add it at the end e.g.
```
zip -r ./vscd.zip * .git
```

**Sample testing in macOS** (`tree -a` prints the structure of the current directory)

![image](https://user-images.githubusercontent.com/892961/70871632-26a78380-1fdc-11ea-8a7f-9886fa342f4a.png)

**Comment by deef0000dragon1** [comment]
if I remember correctly, when I ran the tests myself, zip zippped everything, including the .git files. I think that is because I zipped the directory (./) instead of the files IN the directory (*) . Will make the relevant changes. Thanks for helping me figure that out.

**Comment by ChadBailey** [comment]
> I often land PRs and then reserve a few weeks minimum for "burn-in", to ensure that we're not introducing regressions.. imperfect, but validated by dogfooding.

I like this... I'm not sure how to test it without the incredibly irritating error about devloper mode being enabled each time I open Chrome. Is it possible to get around this? I imagine you all have accounted for this somehow here but I know next to nothing about how the Chrome store works (perhaps there's a way I can subscribe to a dev channel?)

**Comment by deef0000dragon1** [comment]
Assuming the #556 gets pulled in, and an extension on the store is made, there will be a dev version on the store available specifically to remove the need to use dev-mode.

**Comment by igrigorik** [comment]
Landed, debuggin.. :-)
