### ISSUE TITLE
Adding a position on progress bar - Seek Bar

### ISSUE THREAD

**Issue by nguadien** [igrigorik/videospeed#552]
Hi,

My job requires me to watch livestream video fastest possible.
I meet this problem right now:

+ When I speed up livestreams, I will eventually reach the latest progress of the livestream. However the livestream progress slows down without showing any obvious sign that it is slowing down. I have to speed up from time to time (like speed up to 1.10 for 5 sec to catch up then go back to 1.00). My problem is that I don't know my current position versus what the browser has cached so far.

=> I really need a Seek Bar (display only, updating once per 100ms) to show my current video progress on the cached / downloaded video so far. Thus I will surely know when I'm falling behind to manually speed up, instead of randomly speedup now or then like currently doing.

So is a Seek Bar that is display only, updating once per 100ms feasible?

**Comment by igrigorik** [comment]
This use case very much resonates with me, as I've run into the same challenge. 

However, this use case is out of scope for the extension: we do not control the UI of the player, nor can we normalize the UI across all the players out there. This functionality ("showing what is buffered") belongs in core player.. Thanks for raising this, appreciate the feedback and request!
