### ISSUE TITLE
Does this trigger YouTube throttling?

### ISSUE THREAD

**Issue by Steve-357** [igrigorik/videospeed#557]
Sometimes even when I'm using a VPN I experience very intermittent playback and degradation of streaming quality when watching at accelerated speeds, say 1.8x to 2.5x.

I use this on a dedicated Internet connection, via Ethernet, with a typical speed of 24Mbps down.

This is a Windows 10 Pro desktop with latest version of Chrome.  64GB RAM.

Please advise.

**Comment by thewheat** [comment]
Hey Steve 👋 I don't think that this extension would cause throttling specifically: it should just be trying to play the video at the desired speed: downloading the content / data would be outside its control. 

I watch things at 2x speed or faster without too much issue but that is my own case so not a definitive answer.

As you mention it is intermittent, I wonder if it could be something else going on in your network at the time it throttles which could lead to lower bandwidth at the time which causes the throttling? Maybe somebody who has networking experience could suggests ways to help identify possible culprits? 😅

**Comment by ChadBailey** [comment]
I can confirm that this doesn't trigger any type of throttling on YouTube's side.

Your ISP, however, might have some sort of restriction in place. If that is the case, I (or anyone else not familiar with it) wouldn't be able to inform you how to deal with that or how VSC impacts it.

**Comment by Steve-357** [comment]
Thanks for the info. :)

FYI, a couple of times when I've been watching Hulu on Chrome and using the
speed controller, the "speed indicator box" appears in the center of the
screen, even after restarting the browser & clearing cache.

Regards,

Steve

**Comment by igrigorik** [comment]
+1 to above replies. Resolving.
