### ISSUE TITLE
Autoshow controller

### ISSUE THREAD

**Issue by LatinSuD** [igrigorik/videospeed#558]
It may be an interesting option to automatically show controller whenever you start changing speed of a video.

Not sure if autohiding would be good, though.

**Comment by thewheat** [comment]
Hey there 👋 when you mention for it to automatically show, do you mean that you have it set to hidden by default?

If so, there was a recent change to allow the controller to show on speed changing 😃
- See the change here: https://github.com/igrigorik/videospeed/pull/538 
- I don't believe this is merged into the main release on the Chrome web store but if you're really keen to test out the current latest version
    - download it
    - unzip/extract it 
    - and then load it as an unpacked extension (see details here: https://techapple.net/2015/09/how-to-install-load-unpacked-extension-in-google-chrome-browser-os-chromebooks/ )

But if I understood that wrongly and what I mentioned is not what you're referring to, please do share a few more details 👍

**Comment by LatinSuD** [comment]
#538 looks good to me.

Yes I have it hidden by default because I only use the extension seldomly. But when I use it I want to have an indicator of the speed, even if it is briefly.

**Comment by thewheat** [comment]
Cool 👌 Thanks for confirming! Hope a new version can get released so it can be automatically updated 😃

**Comment by igrigorik** [comment]
Shipping in next release (this week). Resolving 👍
