### ISSUE TITLE
support disabling stock shortcuts

### ISSUE THREAD

**Issue by vapier** [igrigorik/videospeed#559]
could support be added for disabling some of the default set of shortcuts ?
i never want to use "Reset speed" & "Preferred speed" myself.

i found i could hack around the UI, but that's no fun :).

```js
chrome.storage.sync.get(['keyBindings'], (items) => {
  const { keyBindings } = items;
  keyBindings[4].key = 1000;
  keyBindings[5].key = 1000;
  chrome.storage.sync.set(items);
});
```

**Comment by igrigorik** [comment]
You can do this via the existing settings panel.

- Click on the keycode you want to disable
- Hit ESC to clear out the key
- Save

That should do the trick!

**Comment by vapier** [comment]
the UI could use work here.  there's no text or hint that pressing ESC does anything.  i did what i thought made sense: select the text, delete it (so the field just says "press a key"), and then hit save.  that doesn't display any error, but reloading the page resets the field.

**Comment by igrigorik** [comment]
Yep, noted. Thanks for the feedback.
