### ISSUE TITLE
Exclusions website

### ISSUE THREAD

**Issue by FrozenFury** [igrigorik/videospeed#56]
Create a exclusions website filter that tells the extension what websites not to run on. Kind of like adblock's version of it.

Thanks!

**Comment by igrigorik** [comment]
Interesting idea. Have you found many sites on which the extension breaks?

**Comment by FrozenFury** [comment]
Sorry for the late reply. Actually no, I haven't found a lot of websites where the extension fails, but there are a few websites which use HTML5 and other keys for controls, so the extension comes into conflict with the website.

**Comment by igrigorik** [comment]
Simple fix: use `shift-<key>` on those sites; we recognize both lower and upper-case keys.

**Comment by igrigorik** [comment]
Closing, for now at least.. as this is a low priority feature.
