### ISSUE TITLE
Hulu browser reload causes controller to move to center

### ISSUE THREAD

**Issue by LightCC** [igrigorik/videospeed#562]
Occasionally, the controller will show up in the center of the screen. I've had it happen both on Chrome and on Brave.

This appears to happens everytime, when I reload a Hulu tab in the browser that has a video with the controls showing up. Killing the tab and reloading Hulu, or restarting the browser, fixes the issue. However, closing all the video overlays (including the smaller overlay the video reduces to), so Hulu is back to the browsing page, then reopening a new video, does NOT fix the issue.

Browsing from that tab to another streaming site DOES reset the controller position to default. I've tried with Netflix and Amazon Prime.

May be related to #536

**Comment by LightCC** [comment]
I just found out about the "drag-and-drop" feature to move the controller position around.

It turns out when this centering problem occurs on Hulu, that the drag and drop gets disabled. You can see the Hand Icon show up, but dragging doesn't do anything - the controller won't move from the center.

**Comment by ChadBailey** [comment]
This sounds like a synchronization issue, like maybe the video container exists first, then is asynchronously populated after we've placed the controller. I'm going to see if I can dig deeper into the root cause

**Comment by TheAlienDrew** [comment]
Yeah I'm experiencing every time a video is loaded. It goes to the center, so I have to drag it to the side manually.

**Comment by TheAlienDrew** [comment]
I've noticed that it seems to be related to the shadow gradients that pop on screen upon a mouse move over, at least on Hulu.

I'm pretty sure the cause is one or more of the elements after using this selector `#web-player-app > div.ControlsContainer`.

**Comment by TheAlienDrew** [comment]
I started experiencing the center issue again recently.
