### ISSUE TITLE
Controller Missing w/ JWPlayer

### ISSUE THREAD

**Issue by nshahzad06** [igrigorik/videospeed#564]
I used Videospeed with a website (Sketchymedical.com) for school that uses JWPlayer (v8.11.10). For almost a year it worked fine. Now I can't see the controller (Flash is disabled + even tried an extension to force HTML5 = no resolution) but my preset keys still work. Only problem is that sometimes when I increase/decrease the speed, I dont know what speed I'm at. 

I've tried reseting Chrome settings, uninstalling/re-installing Videoplayer, blocking Flash. It works on Youtube but not with JWPlayer. 
Note: JWPlayer is an HTML5 playing client

Any help would be appreciated!

**Comment by kubalav** [comment]
I have too one site without speed indicator after latest update.
As temporary workaround change first line in "inject.css" as comment:
FROM
.vsc-nosource { display: none !important; } 
TO
/*.vsc-nosource { display: none !important; } */

**Comment by igrigorik** [comment]
Should be resolved via https://github.com/igrigorik/videospeed/pull/567
