### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by CodyMaldonado** [igrigorik/videospeed#565]
The controller isn't working. 

I think that after I updated chrome yesterday the controller now longer works.

Please help - thank you.

**Comment by thewheat** [comment]
Thanks for the report @CodyMaldonado, are there any example sites that you have where it doesn't show up? I've uninstalled my version and installed the latest and it does seem to show up as per normal 😕 

**Test sites**
- Youtube https://www.youtube.com/watch?v=8AXNd3dB2sY
![image](https://user-images.githubusercontent.com/892961/71465094-9dbbf380-27f6-11ea-9b81-ac7015522308.png)
- Vimeo https://vimeo.com/8733915
![image](https://user-images.githubusercontent.com/892961/71465218-ec698d80-27f6-11ea-9a3b-c206357369b6.png)

**Comment by thewheat** [comment]
Maybe it could be related to this issue https://github.com/igrigorik/videospeed/issues/566 where it doesn't load the controller in that certain scenarios but it does still work using keyboard shortcuts?

**Comment by ChadBailey** [comment]
I'm experiencing this too. I suspect it _might_ be related to this PR https://github.com/igrigorik/videospeed/pull/538 because enabling the "Hide controller by default" option makes it show up when adjusting the speed for me.

**Comment by igrigorik** [comment]
Should be resolved via https://github.com/igrigorik/videospeed/pull/567

**Comment by CodyMaldonado** [comment]
Please watch this video:
https://www.loom.com/share/7b29d53ea4ad4588aa52343507a8fdee


Cody D Maldonado
