### ISSUE TITLE
Controller not showing up on Youtube in a certain situation.

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#566]
When on a channel's "videos" page(ie https://www.youtube.com/user/LinusTechTips/videos) and I click on a video, the controller doesn't show up. Speed controls work. 
If I refresh, it shows up normal.

If I disable SPF(using Youtube+) it starts working normal again.

**Comment by thewheat** [comment]
Thanks for the report @Eisys , I can replicate this problem and I think I've found the problem and it was introduced in [this PR](https://github.com/igrigorik/videospeed/pull/529) that I created. Will create a new PR to try fix this 👍 

I'm not familiar with SPF or Youtube+: did a quick search but didn't find anything obvious. Would you be able to share a bit more details about them if it helps out others as a workaround 😃

**Comment by Eisys** [comment]
Seems you got it fixed it already. Thank you.

SPF is this(taken from Youtube+[ https://github.com/ParticleCore/Particle/wiki/Features#spf_off ]):
"Disable SPF
SPF (Structured Page Fragments) will be disabled. This feature is most commonly known by the red loading bar that appears on the top of YouTube when changing pages and is used to provide a faster and less bandwidth consuming navigation for the user, turning it off will make YouTube pages open like new pages during navigation."

Youtube+ is/was an addon for the old youtube layout which I still use.
