### ISSUE TITLE
Not working on Disney+

### ISSUE THREAD

**Issue by iiayjayo** [igrigorik/videospeed#570]
It used to work, but it no longer does. I've tried disabling then enabling and reloading the page, and that didn't work. I tried removing the extension then adding it again, that didn't work. I checked on YouTube and Netflix and it works there, just not on Disney+.

**Comment by jedawson** [comment]
it does work partially. you need to use the keyboard extensions. but the controller box won't appear.

**Comment by thewheat** [comment]
@iiayjayo there has been a new `0.5.9` with does fix a bug where the controller box didn't appear. Could you try [updating the extension](https://github.com/thewheat/videospeed/wiki#updating-to-the-latest-version) and let us know if it is still a problem? Hopefully it is fixed 🤞
![image](https://user-images.githubusercontent.com/892961/72358655-ded56280-3727-11ea-975e-6440f7c3f453.png)

Also Disney+ is not available in my country but for people who do have access to it, is there are test page that we could visit or does it all require a login?

**Comment by jedawson** [comment]
i've tested it and it works so i'm closing this error. 
please reopen in the future if you feel like disney plus's code updates breaks this extension again.
