### ISSUE TITLE
Add Preferred speed on holding button

### ISSUE THREAD

**Issue by AlexanderMur** [igrigorik/videospeed#571]
I'm using 1-9 buttons as Preferred speed buttons. I'd like to hold button to set the Preferred speed and then on keyup - reset speed.
For example i'm watching 1x speed. Holding the button increases playback rate to 2 on keyup - reset speed to 1 or what speed was before.

**Comment by ChadBailey** [comment]
I don't think I fully follow your suggestion. Are you suggesting that - for example - holding the number 4, then releasing, would set your rate and preferred speed to 4?

**Comment by ChadBailey** [comment]
I was never able to understand this request and no response. Closing this out for now. Please do reopen if you would like to respond to my questions.
