### ISSUE TITLE
Not working on https://offers.tribefit.co/members-area

### ISSUE THREAD

**Issue by mecolialyssa** [igrigorik/videospeed#574]
When I first downloaded it worked, but now the controller is not showing up on my screen for this site. The videos are YOUTUBE based. When i go on Youtube the controller does not show on the video screen either.

**Comment by thewheat** [comment]
Hmmm looks like that page needs a login, do you know if there is a way to obtain a free/trial login? 😅

There was a recent version 0.5.9 release with a bug fix which could solve the problem as well. Is it possible to [try update](https://github.com/thewheat/videospeed/wiki#updating-to-the-latest-version) and see if gets fixed?
![image](https://user-images.githubusercontent.com/892961/72357563-222ed180-3726-11ea-98c7-24f62157eae5.png)

**Comment by ChadBailey** [comment]
I'm closing this due to no response. Please re-open/open a new issue if the problem presists. Thanks @thewheat for taking the time to help!!!
