### ISSUE TITLE
Controls are not showing up for vimeo videos

### ISSUE THREAD

**Issue by jakhay** [igrigorik/videospeed#575]
Controls are not showing up for vimeo videos

Tried firefox and chrome on mac.

**Comment by igrigorik** [comment]
I believe this is a dupe of https://github.com/igrigorik/videospeed/issues/572, please reopen if this is still an issue with 0.5.9.

**Comment by jakhay** [comment]
Webstore (and chrome) still show version 0.5.8, although the update date (on Chrome webstore) shows Jan 8.
Controls now show up in Vimeo, but are not responding to mouseover or mouse clicks.

**Comment by jakhay** [comment]
Comments added. Did not see a way to “reopen” this one.

Thanks for looking into this!
