### ISSUE TITLE
Control Regularly Doesn't Show Up

### ISSUE THREAD

**Issue by NetJon** [igrigorik/videospeed#576]
The speed controls often don't show up on Youtube or Vimeo.

Here is the latest:  https://player.vimeo.com/video/352485178?api=false&autoplay=auto&byline=false&color=%23444444&portrait=false&title=false

No matter what I do (including trying different browser with no cookies etc.) the controls do not show up on that video.

**Comment by eisbehr** [comment]
Looks like a duplicate of #572, which was closed because it is fixed in the most recent release, but the version on the chrome web store still appears to be the broken 0.5.8 release.

**Comment by igrigorik** [comment]
Triple facepalm! Pushed the tag but did not rev the version number in the manifest. 

Rolling out now: https://github.com/igrigorik/videospeed/commit/0389c61db733e86698edc1e1cd5e4298a2777c1d/checks?check_suite_id=399171106

**Comment by NetJon** [comment]
Just updated to 0.5.9.

Hopefully that'll work.  :-)

**Comment by NetJon** [comment]
Well, it DOES work now on the specific example vimeo video that I gave earlier.

So that is a good sign.

Thanks.
