### ISSUE TITLE
Able to get this working on mobile platforms (iOS/Android)?

### ISSUE THREAD

**Issue by queuebit** [igrigorik/videospeed#58]
I rely on videospeed everyday (who has time for 1x?!), but I end up queueing videos longer than 10min to watch on my laptop. 

Is there a way to get something like this working for iOS / Android? Hacks are fine for me, but it would be fun to build an app too.

**Comment by igrigorik** [comment]
You can't run extensions on mobile Chrome, so unless the video player itself offers the speed change functionality (Youtube should, I believe), then the answer is "no".. sadly.
