### ISSUE TITLE
I can't use it on the websites which use Flash.

### ISSUE THREAD

**Issue by lqhsr** [igrigorik/videospeed#590]
This feature has puzzled me for a long time.

**Comment by ChadBailey** [comment]
As far as I know, this is a design choice and support for Flash isn't planned.

With that said, perhaps if you supplied a website you are experiencing this problem as an example I could look more closely to confirm the issue.

**Comment by ChadBailey** [comment]
I'm going to close this as I haven't gotten a response to my request for steps to reproduce. Please re-open or open a new issue if you have the steps to reproduce so I can look into it further.
