### ISSUE TITLE
Severe performance issues beginning merge #541

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#595]
I made a faulty assumption that the latest published version of VSC included PR #541 but from what I can see, it's only updated until the commit just before that.

I had planned to but didn't get a chance to test out #541 and now when developing a fix for #584 I was experiencing a severe performance hit. I checked out the last commit before that, and no performance issues up to this commit (I imagine the version bump is what indicated that was the version pushed out to the chrome extension store)

```
commit 0389c61db733e86698edc1e1cd5e4298a2777c1d
Author: Ilya Grigorik <ilya@igvita.com>
Date:   Mon Jan 13 21:45:05 2020 -0800

    bump to 0.5.9
```

I haven't had the opportunity to look at it on other PCs, but this particular laptop I'm on is a pretty powerful gaming laptop so I expect the story to only get worse.

When digging in a little deeper, it seems clear that there is a problem with the recursive call walking the DOM. The PR mentions performance a lot, I imagine this is why the author was concerned. Any change in speed takes roughly 500ms, so rapid subsequent changes results in a compounding effect resulting in the browser being completely locked up for over 200 seconds. Here is what the profile looks like:

![image](https://user-images.githubusercontent.com/15102816/74616986-7a277200-50f0-11ea-9c46-edc7d91c8f10.png)

I haven't had time to look close enough to draw some conclusions yet, but my thought is we should rethink how we approach enumerating controllers (the little clickable box), then how we reach those controllers once the DOM has already been scanned rather than scanning it on every interaction. If this is not a simple fix, we may want to consider also incorporating the architecture concerns I listed in #589 into the fix.

Hoping to take a closer look when I get the time, but wanted to be sure to report this before it gets pushed out to everyone - it will definitely have to be rolled back if others are experiencing this too.

**Comment by ChadBailey** [comment]
FYI I have tried on other PC's with the same result.

**Comment by jedawson** [comment]
I think that your test that you mentioned in #595 is extremely unrealistic. It appears to me that you decided to test what would happen if someone became extremely bored and decided to see what would happen if they changed the speed constantly. 
I have looked at the performance tab of the developer tools, and I don't see anything like what you've seen. My test consists of opening the video and then hitting the "g" key once to go up to the default faster speed.
![image](https://user-images.githubusercontent.com/20781285/75563133-714b7000-5a0f-11ea-8536-2d75f87cdd05.png)
The extension only takes less than 300 milliseconds. I have highlighted it in the screenshot. I'm running it on a seven year old base model macbook air. 
It would be better if your screenshot actually showed the time taken. Go to the Bottom-Up tab within the Performance tab and then select the Group by URL option from the dropdown menu. 

Reverting this pull request is like throwing the baby out with the bathwater. What actually needs to be done is to modify the runAction function: https://github.com/igrigorik/videospeed/blob/eaf5ac47f308fb4a1fc608bc862de5e01885f128/inject.js#L553
It is looks again for the video tags every time you click a button on the vsc controller UI or a shortcut key. Why doesn't it just store the video tags somewhere so it doesn't have to go through the whole DOM every time?

**Comment by ChadBailey** [comment]
You're right, I intentionally changed the speed rapidly in order to capture what was happening. Sorry if that appears as if I was trying to make it seem as if the issue was worse than it really was.

Irrespective of the performance screenshot above, I've tested on multiple machines and the performance is unacceptable to me for my usage pattern (adjusting the speed up several times to more than 2-3x is common for my usage).

> takes less than 300 milliseconds

I do not consider 295ms to be within acceptable margins given that means going from 1.0x to 1.3x will take an entire second, and 3 seconds to get to 2.0x speed. The issue is compounded if you issue the increase speed hotkey successively. I also have Macbook Pro, and it does not run within an acceptable speed to me. I wouldn't have even noticed this if I didn't think the hotkey wasn't even working at all the first time I tried as on first load it takes much longer.

**Comment by jedawson** [comment]
before the tweaks:
![image](https://user-images.githubusercontent.com/20781285/75574984-e70e0680-5a24-11ea-9c6b-74cada32bea5.png)

after the tweaks:
![image](https://user-images.githubusercontent.com/20781285/75575408-8af7b200-5a25-11ea-8bf8-a8b350e12805.png)

now the performance issues are fixed.

**Comment by ChadBailey** [comment]
nice work!
