### ISSUE TITLE
Compatibility with Twitch VODs..

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#60]
Could that be implemented? Twitch is going the way of HTML5 and watching VODs in a higher speed would be very nice.

**Comment by igrigorik** [comment]
In theory, there is nothing to implement.. Once they switch to HTML5 player the controls should just work. Is there an opt-in experiment to test this?

**Comment by Eisys** [comment]
I'm not sure. All I know is Twitch has a new player similar to YT, with transparent controls. That might not mean it's HTML5 though.

**Comment by igrigorik** [comment]
Sadly, Twitch is (still) using Flash.. If you disable flash plugin (via chrome://plugins/) nothing comes up.
