### ISSUE TITLE
Twitch livestream speed

### ISSUE THREAD

**Issue by sassazera** [igrigorik/videospeed#602]
The speed always change itself to 1.03 when watching twitch.

**Comment by ChadBailey** [comment]
Duplicate of #584, thanks for the report. Since that's a long thread, I'll summarize by saying a fix is known, and I had planned to try and make it in to the official build today.

**Comment by sassazera** [comment]
Ok, thanks. Can't live without it anymore haha

**Comment by ChadBailey** [comment]
I'm going to close this out and continue discussion on #584 but this should be fixed in the PR I just opened #604
