### ISSUE TITLE
Doesn't work on www.khanacademy.org videos

### ISSUE THREAD

**Issue by Layarion** [igrigorik/videospeed#603]
UPDATE: nvm just realized those were software simulations with audio attached, not videos.

https://www.khanacademy.org/computing/computer-programming/sql/more-advanced-sql-queries/pt/more-complex-queries-with-andor

in the SQL videos i noticed I can't use this, and I think these are just embedded YT videos.

**Comment by ChadBailey** [comment]
No problem, going to go ahead and close this. Feel free to re-open if needed
