### ISSUE TITLE
Add a full - screen shortcut, preferably double - click space full - screen

### ISSUE THREAD

**Issue by invisifire** [igrigorik/videospeed#605]

**Comment by ChadBailey** [comment]
I will say that I do find myself frustrated by players that refuse the ability to fullscreen, I feel the ability to fullscreen is a basic human right of all netizens and shouldn't be messed with.

With that said, I'm not sure this is within the scope of the project. What do you think @igrigorik ?

**Comment by igrigorik** [comment]
Given that there are existing extensions for this, I think I'd suggest we defer that to them:
https://chrome.google.com/webstore/search/fullscreen?hl=en&_category=extensions

**Comment by ChadBailey** [comment]
Thanks for the link, I hadn't considered searching for an extension for doing this. Closing this to keep the issues area tidy.
