### ISSUE TITLE
Unsearchable?

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#607]
For some reason when I search for "video speed controller" in the google chrome store, I can't find this extension?

![image](https://user-images.githubusercontent.com/15102816/76137714-a0607380-6005-11ea-8304-bf46fd67b0b9.png)

Not sure if anything can be done to resolve, but seems strange given this is the verbatim name of the listing https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk

**Comment by igrigorik** [comment]
If you click on "more extensions" you do see it show up as #4 (for me, at least). I agree that this an odd ranking function for the Chrome store, but that's not something we can control or affect.

**Comment by ChadBailey** [comment]
Thanks for the update... I thought perhaps this could be a simple configuration issue or something similar. I'll close this out
