### ISSUE TITLE
Google Music at speed 1.05 is changing pitch instead of speed

### ISSUE THREAD

**Issue by katriik** [igrigorik/videospeed#611]
While listening to Google Music, if I increase the speed from 1 to 1.05, it changes the pitch as well. If I continue to increase to 1.10, the pitch goes back to normal, and speed is increased normally.
The same happen the other way: 0.95 and pitch also change with speed. 0.90 and pitch goes back to normal.

**Comment by OneMaskedNinja** [comment]
I can confirm this also happens on Youtube.

**Comment by ChadBailey** [comment]
this is very likely (read: definitely) a bug in chrome itself and has nothing to do with VSC, so as such there's probably nothing that can be done unfortunately

**Comment by ChadBailey** [comment]
Although I'm certain enough in my diagnosis of it being an upstream Chromium issue that I don't think it warrants investigating, I will take a closer look at this one when I get the chance. I want to be sure I've done my part to confirm.

**Comment by katriik** [comment]
I'm not much into programming, but if there is any way I can help, please do let me know.

Thank you.

**Comment by igrigorik** [comment]
Controller has no control over pitch, that's deep in the browser's media stack. If you're still seeing this, please open an issue on crbug.com.
