### ISSUE TITLE
Update Github action trmcnvn/chrome-addon to v2

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#614]
I may well be at fault here for not using it correctly, but I can't get the github action to upload to chrome store working correctly.

First, I tagged for release v0.6.1 which resulted in an error 400 https://github.com/igrigorik/videospeed/actions/runs/51527911

Then, I decided to start from the master branch. I created release branch and modified only the version number to v0.6.2, tagged and pushed.

```sh
$ git clone https://github.com/igrigorik/videospeed.git videospeed-master
$ cd videospeed-master
$ git checkout -b "release/0.6.2"
Switched to a new branch 'release/0.6.2'
$ git add .
$ git status
On branch release/0.6.2
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   manifest.json

$ git commit -m "bump to v0.6.2"
[release/0.6.2 fb6c9c0] bump to v0.6.2
 1 file changed, 1 insertion(+), 1 deletion(-)
$ git tag -a v0.6.2 -m "bump to v0.6.2"
$ git push origin v0.6.2
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 424 bytes | 424.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/igrigorik/videospeed.git
 * [new tag]         v0.6.2 -> v0.6.2
```

Then got the same error 400. https://github.com/igrigorik/videospeed/actions/runs/62801046

I clicked rerun job, and it failed with the same error.

Just as a simple precursory check, I did see that the github action is now v2. Going to try updating the version as a simple first pass at fixing

https://github.com/trmcnvn/chrome-addon

**Comment by ChadBailey** [comment]
I attempted updating to v2

I put the changes in a branch https://github.com/igrigorik/videospeed/tree/bugfix/614-github-action-failing-error-400 (which I plan to delete once I get this sorted) in order to ensure there wasn't something wrong with my fork.

https://github.com/igrigorik/videospeed/runs/532697123?check_suite_focus=true

Did not resolve the error

**Comment by ChadBailey** [comment]
See above issue opened on upstream project https://github.com/trmcnvn/chrome-addon/issues/6

I suspect our next step may be to have @igrigorik try refreshing the secrets https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md

**Comment by ChadBailey** [comment]
After further digging, I [found](https://github.com/trmcnvn/chrome-addon/issues/4) that we should be able to [enable debug logging](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs) on the github action to have a clearer picture of what is generating the error.

**Comment by igrigorik** [comment]
Ah, think I finally tracked it down.. New fields I need to fill out in Chrome Store that were causing the uploads to error out. Seems to have gone through now: https://github.com/igrigorik/videospeed/actions/runs/63549290

New release is under review, fingers crossed, should be live soon.

**Comment by ChadBailey** [comment]
looks good, thanks igrigorik! closing this out

**Comment by ChadBailey** [comment]
reopening so i can add upgrading to v2 in the next release since the work has already been done

**Comment by ChadBailey** [comment]
TODO: Remove change to version number
