### ISSUE TITLE
Preferred speed is sometimes reset with Chrome 80.0.3987.149

### ISSUE THREAD

**Issue by geertengoossens** [igrigorik/videospeed#615]
hi,

Very glad to use the video speed controller addon in Chrome. I am viewing approx 750 video's per week which I should scan and this tool helps a lot.

However, seems that with Google chrome version 80.0.3987.149 preferred speeds is reset. Does not occur with every video. Tried the video speed controller with an earlier version and it works fine. 

Can you have a look?

**Comment by ChadBailey** [comment]
thanks so much for the report! assigned to our next bugfix release 0.6.3, we'll try to get to it as soon as we can.

**Comment by igrigorik** [comment]
Should, I believe, be resolved in latest release.
