### ISSUE TITLE
Facebook Videos No Longer Works

### ISSUE THREAD

**Issue by DanitiKain** [igrigorik/videospeed#618]
Looks like Facebook no longer works with this tool. It used to work.

**Comment by ChadBailey** [comment]
Thanks for the report. I don't know but think this may be related to #609 which has an open PR to fix. I'll test it myself and make sure my hypothesis is correct

**Comment by ChadBailey** [comment]
I'm unable to reproduce this, Facebook is working for me. Can you provide steps to reproduce?

Here are the steps I took:

1. Visit https://www.facebook.com/watch/
2. Click play on whatever video shows up
3. Use hotkeys and controller to adjust speed, both work

**Comment by DanitiKain** [comment]
It appears that it still works on FB classic mode. However, if you switch to their new interface it no longer works. Click top right to switch modes. There is an option to switch to new facebook.

**Comment by ChadBailey** [comment]
I can't find the option to switch modes, perhaps the new mode is just being rolled out to limited sized trial groups?

**Comment by DanitiKain** [comment]
That must be the case. https://www.androidpolice.com/2020/03/19/facebooks-new-web-interface-is-rolling-out-for-some-with-dark-mode-in-tow/

**Comment by halinagold** [comment]
Just to confirm that I see the issue as well, with the new Facebook design (which I'm not able to rollback), on my Windows 10 laptop. Until then this extension worked like a dream, so helpful. Thanks!
