### ISSUE TITLE
Default play speed with Pluralsight is 0.5

### ISSUE THREAD

**Issue by SeanFeldman** [igrigorik/videospeed#62]
Pluralsight on chrome plays all videos at speed of 0.5 and requires manual reset upon any play or skip operation.

**Comment by igrigorik** [comment]
Apologies about the delay. Unfortunately don't have an account with them, so can't verify/test this. And that's really odd behavior.. Have you tried enabling "remember playback setting" setting in options?

**Comment by igrigorik** [comment]
Closing, feel free to reopen if this is still an issue.
