### ISSUE TITLE
https://joinnow.live/ not working

### ISSUE THREAD

**Issue by rvadhvana** [igrigorik/videospeed#624]

**Comment by igrigorik** [comment]
Unfortunately they don't provide any examples on their site for us to test. Please reopen if you have an example we can take a look at.

**Comment by pepijnmm** [comment]
the videospeed extension seems to work. Only again the layer problem(so need to use keyboard to change speed). Has the same as #690 (same bypass overlay works as sbs.com.au/primevideo)
