### ISSUE TITLE
Prime stutters when <x1.6

### ISSUE THREAD

**Issue by bundy23** [igrigorik/videospeed#629]
Amazon prime seem okay up to x1.5 but once you go past that it gets very stuttery. The quicker you go, the worse it gets.

**Comment by ilanerukh** [comment]
Having this issue as well in Panopto viewer, which the videos are stored in cloudfront.

**Comment by igrigorik** [comment]
Unfortunately this is a streaming/HLS delivery issue, nothing we can address in the player.
