### ISSUE TITLE
hitbox.tv overlay too big

### ISSUE THREAD

**Issue by pluripotential** [igrigorik/videospeed#63]
The controller overlay covers the whole video screen on hitbox.tv, obstructing all video controls.

**Comment by igrigorik** [comment]
Can you capture a screenshot? For some reason none of the streams are loading for me.

**Comment by pluripotential** [comment]
http://i.imgur.com/qKUGIig.png <http://imgur.com/qKUGIig>

As you can see in the screenshot, there appears to be two overlays. One is
normal size, the other obstructs the entire screen. The screenshot is of a
VOD, but the same problem occurs a live stream.

**Comment by igrigorik** [comment]
Hmm, interesting.. Finally got the stream to load, few observations:

- Their code appears to have HTML5 fallback logic, but the stream itself doesn't work.. I can't load any stream with flash plugin disabled. 
- They inject empty video tags (no src attribute or source element) into the DOM multiple times, which is what triggers videospeed to display multiple controllers.

I guess I could check that the injected video tags have a src or source? That seems a bit sketchy though.. I imagine that would cause issues in other cases.

**Comment by igrigorik** [comment]
Added hitbox.tv to exclusion list for this extension (88cf0c8). Once they enable HTML5 video we can revisit.
