### ISSUE TITLE
Not working with v.redd.it

### ISSUE THREAD

**Issue by OneMaskedNinja** [igrigorik/videospeed#630]
On Reddit's embedded video player v.redd.it the controller is displayed, however you cannot actually adjust the speed using either hotkeys or the gui buttons.

Upon further testing, it works with v.redd.it sometimes, but pausing and unpausing the video resets the speed and makes the speed unable to be changed.

The more I mess around with it, I realize that v.redd.it videos seem to no longer get along with the extension. The second issue I mentioned with the pausing and unpausing, leads to a bug I've never seen before. When you unpause a video it treats the current set speed as the new "starting" speed, for lack of a better word, and starts modifying the speed based on the new, current, speed. For example if you start a video at 1.00 and slow it down to .50 then pause and unpause the video it starts playing as if the speed were 1.00 again, despite the fact that the speed should be .50. At this point changing the speed to 1.00 plays the video as if it were played at 2.00, seemingly doubling the speed starting from .50 not 1.00.

That description probably barely made sense. Sorry for any confusion.

**Comment by igrigorik** [comment]
Testing on (new) reddit, everything is showing up correctly. Fingers crossed, hope your issue is resolved via updates on their end.
