### ISSUE TITLE
Notice to users: Updates may be limited during COVID-19 outbreak

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#633]
# Explanation

> Sorry this is filed as a bug report, I figured this was the fastest and easiest way I could get the message out.

Hello everyone reading this... I think I speak for anyone who has ever contributed to this project when I say we all love building it, using it, and helping bring what I believe to be the best Chrome extension to you all.

With that said, I personally have been volunteering all of my available time by coordinating and executing on volunteer efforts to assist healthcare workers with PPE during COVID-19. As much as I love contributing to this project, when having to choose between this and providing support that could save someone's life I will always choose the later. Knowing all of the admirable efforts Google has been putting in to assisting with COVID-19, I suspect the owner @igrigorik may be in a similar boat.

That doesn't mean I don't intend to contribute at all, so if I find time I will absolutely do so... but no promises of if/when at this time.

Thank you all for understanding. I hope you and your family remain safe through this historically difficult time.

## Loading a previous version

If for some reason you are having a serious issue and _really_ need video speed controller in order to live through this quarantine, you may attempt loading a previous version as a temporary workaround. Here are some simple instructions for loading an older version.

1. Open the main [project github page](https://github.com/igrigorik/videospeed/tree/v0.5.9)
2. Click the top-left corner where it says "Branch: master" or perhaps "Tag: v0.5.9" if you followed the link in the previous step
3. Click the "Tags" tab, here you will find all available releases (at the time of writing, there are 3) - choose the one you want to download.
4. Click the green "Clone or download" button on the top-right corner
5. Click "Download Zip"

Once you have this zip file, you can extract it somewhere on your hard drive then within chrome manually type in the address bar `chrome://extensions`. Here, click `Developer mode` on the top-right to enable developer mode. Finally, click the "Load unpacked" button on the top-left and browse to the folder you extracted the zip file to.

**Comment by ChadBailey** [comment]
Quick update to this one guys... going to try and do some bug fixes only. In efforts of preventing regressions just going to focus on the open PRs which don't have conflicts and hopefully can make a relatively risk-free update that will enhance the experience for everyone.

My goal is to not make it any worse than it already is since I don't have a lot of bandwidth for recovering, so I will be cautious about what gets added in this time around.

**Comment by igrigorik** [comment]
Sounds great, thanks a lot for your help and time Chad! 🙏

**Comment by ChadBailey** [comment]
I'm very nearly finished with all the projects which have gotten in the way! Excited to begin contributing again soon. I'll close this out once my current project concludes.

**Comment by ChadBailey** [comment]
I'm not 100% back yet, but I'm going to try and begin the process of learning all that I missed!

**Comment by pepijnmm** [comment]
> I'm not 100% back yet, but I'm going to try and begin the process of learning all that I missed!

Welcome back. most is unchanged only ui and #708 have been some big changes and #710 for some iframes fixes
