### ISSUE TITLE
Speed being reset on Disney Plus

### ISSUE THREAD

**Issue by Danielejava** [igrigorik/videospeed#639]
Hi, just wanted to say that on Disney Plus the option to keep the preferred speed is not working. I've tried refreshing the page, reopening the browser and any other solution. 

Hope that helps.

**Comment by igrigorik** [comment]
Their player forces a reset on each video which is something that we, unfortunately, can't override. You can define a preferred speed and bind it to a key, that you can use to quickly get back to your preference.

**Comment by pepijnmm** [comment]
I think there would be a way but it's a little hacky. We could get the currentTime of a video and after it played 1/0.5 sec set the preferred speed. The other solution could be #661 but then you can't change the speed anymore.
