### ISSUE TITLE
Show overlay speed whenever speed is changed

### ISSUE THREAD

**Issue by truth1ness** [igrigorik/videospeed#64]
It seems the overlay disappears when the mouse isn't hovered over the video for a few seconds. This is fine but I want to be able to see what the speed is when I change the speed. The overlay should return briefly whenever the speed is changed so the user can see what the current speed setting is.

**Comment by expeditor** [comment]
Definitely what I want.
Extension badge may be useful for this feature.

**Comment by Eisys** [comment]
Yes. So much yes.

**Comment by igrigorik** [comment]
Added in ca0f446. :)

**Comment by Eisys** [comment]
Works great. Thank you!
