### ISSUE TITLE
Show me how much time I've saved 

### ISSUE THREAD

**Issue by marketb12** [igrigorik/videospeed#643]
It would be really cool to see how much time I've saved by using this extension. IE: if i've watched 10 1 hour videos at 2x speed, I've saved 5 hours.

**Comment by siadat** [comment]
Yes, it would be very interesting to see the time we have saved. I have made [this pull request](https://github.com/igrigorik/videospeed/pull/185). Feel free to go over there and weigh in your argument for having it merged :)

**Comment by igrigorik** [comment]
@siadat neat-o, thanks for prototyping this! I agree with your judgement in the PR, time saved is a vanity metric. There is a related discussion in https://github.com/igrigorik/videospeed/issues/690 which is the inverse and, I think, may be a better option for us to explore.
