### ISSUE TITLE
speed indicator not visible on chrome

### ISSUE THREAD

**Issue by cms22** [igrigorik/videospeed#644]
I can't see the speed indicator when I've been watching videos using Chrome recently. I can still adjust the speed using "s" and "d" keys on the keyboard, but it would be nice to be able to actually see what speed I'm going at to know if I need to be doing it faster or can slow down depending on how much time I have available.

**Comment by cms22** [comment]
Then at other times it will show up but the indicator won't show the correct speed no matter how long you wait for it.

**Comment by igrigorik** [comment]
I believe this is fixed in latest release, closing.
