### ISSUE TITLE
the speed controls dasappear in full screen

### ISSUE THREAD

**Issue by fominfyodor** [igrigorik/videospeed#649]
I have noticed that the last few times I have used the extension, every time I change from window to full screen the speed controls disappear and don't showing up again, but they were before changing.

**Comment by sabbsol** [comment]
A change in YouTube I think, I see the same behaviour on Youtube, but not on many other videos.

**Comment by igrigorik** [comment]
I believe this is fixed/working in latest version. Please reopen if still a problem on your end.
