### ISSUE TITLE
overlay fades out with mouse still on the control

### ISSUE THREAD

**Issue by dexterouschen** [igrigorik/videospeed#65]
I don't know about other websites, but for YouTube specifically, I click on control to adjust playback speed but after maybe 3-5 seconds, overlay fades out even though mouse is still on the control, yet the functionality is there, which means if I keep on clicking, it will hit that invisible button instead of play/pause the video.

**Comment by pinheirorlc** [comment]
Sometimes I have the same problem, not only for youtube videos, but for vimeo too.

**Comment by igrigorik** [comment]
This one is tricky. YT, Vimeo, etc, all have own JS+CSS logic to stop the 'autohide' from firing and it's hard to know where that lives exactly.. As such, the only thing I can do here is to fix the "click on invisible element" -- fixed via 0862b14.
