### ISSUE TITLE
コントローラの表示非表示について

### ISSUE THREAD

**Issue by hachibei0106** [igrigorik/videospeed#651]
デフォルトで、「V」を押すと、コントローラーが表示/非表示される設定になっています。

最初は機能しています。

ところが、「速度アップ」や「巻き戻し」をすると、「V」をその後に押しても、
表示/非表示が機能しない（非表示のまま）になってしまいます。

どうしたらいいでしょうか？

**Comment by ChadBailey** [comment]
Even if only using google translate, please use English when posting bug reports so that we can better assist you.

Here is what google translate comes up with

> By default, pressing "V" will show / hide the controller. At first it is working. However, when "speed up" or "rewind" is performed, even if "V" is pressed after that, the display / non-display will not function (it will remain hidden). What should I do now?

This defect isn't known, I'll take a look.

**Comment by ChadBailey** [comment]
I just tested and not experiencing this in either the current or the upcoming release I'm currently working on. Please try out the new version once it drops and provide exact steps to reproduce if you are still experiencing the problem
