### ISSUE TITLE
video speed controller on android

### ISSUE THREAD

**Issue by kimsysy** [igrigorik/videospeed#652]
How about creating a new version for Android / ios users?

**Comment by gitSambhal** [comment]
You can use [https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en](Kiwi Browser) to install this plugin in Android.

**Comment by kubalav** [comment]
It doesn't work on Android.

**Comment by gitSambhal** [comment]
Previously it used to work but now it is not working from few days and not even in Windows.

**Comment by igrigorik** [comment]
Chrome extensions are not available on mobile, unfortunately. Fingers crossed, hopefully one day that will be a thing, but until that changes this is a cant-fix.

**Comment by gitSambhal** [comment]
@igrigorik  Chrome extensions are available in Mobile using [https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en](Kiwi Browser).

**Comment by igrigorik** [comment]
Yep. That's a not browser we test with or target with this extension.. if it works, great!
