### ISSUE TITLE
controller being displayed twice

### ISSUE THREAD

**Issue by watersidemouse** [igrigorik/videospeed#653]
the controller is being displayed twice, sometimes even in the same exact place. when i x one out, the other one stays, and when i press my hotkey for showing/hiding the controller, they start alternating. i even tried getting rid of the extension and re-installing it, but the issue persists.

![Annotation 2020-05-12 224844](https://user-images.githubusercontent.com/65267180/81765803-c6414300-94a2-11ea-9d5f-6fe76fbe828b.png)

**Comment by igrigorik** [comment]
I believe this was a transient issue that was fixed in latest release. If still a problem next week (after new version ships), please reopen.

**Comment by watersidemouse** [comment]
Thanks
