### ISSUE TITLE
Github action failing

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#657]
I attempted to cut a bugfix release and looks like the github action is failing again (hope this is OK... I attempted to only merge in fixes rather than enhancements). Not sure what the root cause is, but might be a repeat of https://github.com/igrigorik/videospeed/issues/614#issuecomment-604238519

Action in question:
https://github.com/igrigorik/videospeed/actions/runs/107451821

**Comment by igrigorik** [comment]
Thanks for pushing the release! There was a missing field in the updated privacy policy in Chrome Web Store, which I had to provide.. 0.6.2 should be in the review queue and rolling out once that's cleared.

**Comment by ChadBailey** [comment]
thanks for the quick response :) i'll go ahead and close this one out
