### ISSUE TITLE
Issues on HBO GO (Poland)

### ISSUE THREAD

**Issue by Celebes** [igrigorik/videospeed#659]
Extension doesn't work as expected on https://hbogo.pl/:
1) Even though I have "remember the speed" option enabled, the speed always starts at 1.0x, even if I set it to 2.0x on youtube for example
2) Increasing/Decreasing speed with shortcuts (A/D) works correctly, but doesn't update tooltip where current speed is displayed (so it incorrectly shows the same speed all the time, for example 2.0x, even though video is playing at 1.0x speed initially and increasing the video speed doesn't update said value)
3) Stopping video and resuming (even when it happens because of buffering for split second) makes the video playback speed reset back to 1.0x

Tested on Windows 10, Chrome 81.0.4044.138 (64-bit), extension version 0.6.1

**Comment by MajinBui** [comment]
Hi @Celebes, item 2 has most likely been fixed as part of version 0.6.2 (but has not gone live yet).  For items 1 and 3, I have a potential work around/fix for since some video players attempt force apply their speed instead of using VideoSpeed's.

**Comment by igrigorik** [comment]
@MajinBui thanks for triaging this. Closing, looks like you have another PR on the way -- let's review that separately.
