### ISSUE TITLE
Keyboard shortcuts affecting commenting

### ISSUE THREAD

**Issue by far-thole** [igrigorik/videospeed#66]
Not exactly an issue, but rather an annoyance or a "feature". When commenting on videos (with video still playing), the keyboard shortcuts still work (however, when paused, they do not).

**Comment by igrigorik** [comment]
Hmm, grrr... Looks like youtube switched from using an input field to a contenteditable div, which is why this happening now. I'll have to look into and see if/how we can detect this.

**Comment by igrigorik** [comment]
Resolved via 37e2d32.
