### ISSUE TITLE
How can I make CSS fix permanent?

### ISSUE THREAD

**Issue by kubalav** [igrigorik/videospeed#665]
How can I make changes in inject.css file permanent? After update extension all changes gone.

**Comment by toppits** [comment]
how do you make anything work via that file? If i edit it, chrome says its may be corrupted and disables it.

**Comment by kubalav** [comment]
I simple edited file. I use Opera and I have activated developer mode.

**Comment by igrigorik** [comment]
You can download the extension source from GitHub and install the extension as an unpacked extension.
