### ISSUE TITLE
speed resets if we pause the video

### ISSUE THREAD

**Issue by saiteja1912** [igrigorik/videospeed#666]
I just increased my speed to 2.5 and paused the video for a while and then played it again. The speed has been reset to 1.0 even after toggling remember playback speed.

**Comment by andrewma28** [comment]
Same situation as the comment above. Speed up to watch video, then pause, then when I press play, it reverts to 1.0x again. How do I fix this?

**Comment by enigmatikme** [comment]
Same issue.
