### ISSUE TITLE
Some condition with "last speed" prevents vids from playing

### ISSUE THREAD

**Issue by charlescanato** [igrigorik/videospeed#667]
First of all, forever thank you for such a quality addon! I was missing it in Chrome, since in Firefox I use it for a long time already (same behavior and icon, but I guess it's under another dev).

The problem: I've set a key for my preferred speed (1), and also have checked "remember playback speed". I don't know what I might have done or what might happened, but since two nights ago, YouTube was not playing anymore (and of course, working on incognito or other browsers) - the other synced machine (different Win, different Chrome version), the other machine also showed the same symptom.

I've just accepted it could be some change on YT code, or a combination of my uBlock+uMatrix, but in the last hour, I've researched. The only recent extension was videospeed, so I finally checked the console:

`Uncaught TypeError: speed.toFixed is not a function
    at setSpeed (inject.js:674)
    at tc.videoController.mediaEventAction (inject.js:215)`

So, debugging it the speed var for setSpeed was a **the string "0.00"**. Despite the runtime error, it was parsed as zero - so videospeed was really doing its job. I didn't think about increasing speed, since when the vid has the loading animation, you're not really expecting that it is playing on speed zero.

Well, anyway, your code does not really have a bug. I see that the code for "slower" limits to a min of 0.07 - and I checked that Chromium link about it, but believe me: zero IS being set as speed if that's the last speed read - can't imagine how I got it.

So I don't know if it'd make sense to transfer the checks to setSpeed, to limit min and max some other way - the video initialization does not go through "slower" or "faster", so that range is never checked.

I'm sorry if I didn't do a pull request, I'm not sure if this is something you might have left by design, and did not want to mess with your great code.

**Comment by pepijnmm** [comment]
About the error speed.toFixed #666
