### ISSUE TITLE
No controls for support.microsoft.com training videos

### ISSUE THREAD

**Issue by netjeff** [igrigorik/videospeed#668]
No controls shown for support.microsoft.com training videos.  A couple of examples:

- https://support.microsoft.com/en-us/office/video-what-is-microsoft-teams-422bf3aa-9ae8-46f1-83a2-e65720e1a34d
- https://support.microsoft.com/en-us/office/create-a-workbook-in-excel-94b00f50-5896-479c-b0c5-ff74603b35a3

Flash is disabled, so not Flash videos.

**Comment by alon91** [comment]
Tried both videos -- I can't see VSC's visual controller in the upper-left corner, but I am able to change speeds by clicking in the player and using keyboard shortcuts. So the player can be manipulated by VSC but blocks the visual component.

**Comment by netjeff** [comment]
Sure enough, keyboard shortcuts work even though controls not displayed.  I had not thought to try the shortcuts without seeing the controls.  So something on the page is interfering with the display.  I'm good for now, but maybe still leave this open, so that future people with same symptoms can find this, and give keyboard shortcuts a try?

**Comment by igrigorik** [comment]
Related: https://github.com/igrigorik/videospeed/issues/690 - let's continue there.
