### ISSUE TITLE
'Rewind' keyboard shortcut not working on Youtube

### ISSUE THREAD

**Issue by jordn** [igrigorik/videospeed#67]
I'm finding that the `a` keyboard shortcut (to rewind 10 s) is no longer working on the updated HTML5 youtube player. Is this true for others?

Chrome 45 and Video Speed Controller 0.25.0

**Comment by jordn** [comment]
To clarify, `a` only stops working after I have clicked on the video in some way. If I click back on to the surrounding page at all it works fine.

**Comment by igrigorik** [comment]
Hmm, odd.. can't reproduce it here. Any chance that you have other extensions that might be clashing?

**Comment by jordn** [comment]
Just tried with only this extension enabled – same behaviour as described.

Something is definitely iffy for me. The new `t` (skip forward button) doesn't work and I can't change playback speed when the video is paused... 

I've now tried loading the unpacked latest from the repo. Skip forward and change speed while paused work, but the issue of not being to skip backwards when the youtube video is focused persists.

**Comment by igrigorik** [comment]
Hmm, did you customize any of your shortcuts? Can you try resetting those to default values just in case?

**Comment by jordn** [comment]
Hadn't changed them and resetting them has had no effect. :confused:

**Comment by andrew-oxenburgh** [comment]
Hi,

I'm getting the same thing.

Running Chrome 46.0.2490.71 (64-bit) on OS-X 10.11 (El Capitan) on a late 2015 13" Mac Air.

Other controls great.

I'm using it anyway, and will have a look at it here, when I get an opportunity.

Great App!!

**Comment by igrigorik** [comment]
Hmm, doh.. It appears that YT player has started swallowing "A" keyPress events. It works fine if you focus on something other than the video element, but if you click on video and try "A" then it's a noop.

The only sensible workaround here is to remap the default keys to something that's not used.. and given YT's popularity I think it makes sense to change the defaults -- done, see 8850fd8. 

Once I push out the update you'll have to go into options and reset to defaults, or manually remap your keys.
