### ISSUE TITLE
Playback speed doesn't remember for YouTube ads

### ISSUE THREAD

**Issue by warman602** [igrigorik/videospeed#670]
Playback speed doesn't remember the speed I put it on when the YouTube ads start playing and will reset playback speed to YouTube 2 time speed instead of my  2.90 times speed when the video start

**Comment by Eisys** [comment]
I feel like if you are watching content at 2.9x speed, you don't have a lot of time to waste on watching ads in the first place.. 
Perhaps use an adblocker?

**Comment by warman602** [comment]
I like to keep the ads to support that YouTube creators since I can't do patreon

**Comment by pepijnmm** [comment]
Same issue as  #666

**Comment by igrigorik** [comment]
Closing, let's continue in #666.
