### ISSUE TITLE
Speed not remembered on Vudu & Amazon

### ISSUE THREAD

**Issue by thelapisfox** [igrigorik/videospeed#671]
I just recently started having an issue where neither Vudu nor Amazon will remember the speed when it switches to a new video and I have made sure that 'Remember Playback Speed' is checked. Also, this behavior is occurring in both Chrome and Firefox.

**Comment by pepijnmm** [comment]
Same issue as #666

**Comment by thelapisfox** [comment]
Adding that it's happening on Funimation.com now too.

**Comment by pepijnmm** [comment]
if in the console you get: Uncaught TypeError: speed.toFixed is not a function.
Then it is the same problem.

**Comment by thelapisfox** [comment]
Yup, you're correct

Uncaught TypeError: speed.toFixed is not a function
    at setSpeed (inject.js:674)
    at tc.videoController.mediaEventAction (inject.js:215)

**Comment by igrigorik** [comment]
Should be fixed in upcoming release.
