### ISSUE TITLE
Negative speed (rewind) feature?

### ISSUE THREAD

**Issue by KaranJain21** [igrigorik/videospeed#672]
I think the speed controller would benefit with a rewind (at desired speed) feature. For e.g. if you want to see what happened in a particular segment of slow-mo video and don't wont to go back a few seconds just to see a small shot again. Also, seeing videos in reverse is sometimes fun!
I would suggest having a toggle key that sets the speed to negative of whatever speed it was running at.

I am not sure how difficult this is but, in principle, it seems that it should not be too difficult to implement. I am willing to make the changes and do the testing myself if someone can point me towards the relevant segment in the code where this can be added (unfortunately, I am not that familiar with javascript).

**Comment by pepijnmm** [comment]
seems like for some website it would not work and a lot of browsers don't support it
https://stackoverflow.com/questions/5277293/is-it-possible-to-play-html5-video-in-reverse
https://github.com/whatwg/html/issues/3754
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate = "If playbackRate is negative, the media is not played backwards."

**Comment by KaranJain21** [comment]
Got it. It seems like a harder problem than I anticipated. The current best solution is probably to just use an existing video reverser which specifically converts and encodes the entire video in a reverse format (e.g. [clideo](https://clideo.com/reverse-video)). I will close this issue.
