### ISSUE TITLE
Stopped remembering default speed suddenly.

### ISSUE THREAD

**Issue by Sarthak-Bhagat** [igrigorik/videospeed#676]
I've tried reinstalling the add-on, chrome and re-enabled the settings, but I still have to press G every time a new tab plays a video. The weird thing is that it shows that the video is running at 2.5x speed when its clearly not.

**Comment by pepijnmm** [comment]
Same issue as #666

**Comment by igrigorik** [comment]
Merging, let's continue in #666.
