### ISSUE TITLE
editing inject.css, chrome considers it corruption and disables.

### ISSUE THREAD

**Issue by toppits** [igrigorik/videospeed#677]
Assuming thats the one to edit if i want, for example, make it trigger by hover over the step-up/step-down buttons, not the just the factor one? 

Circumstance is that when controlling it from the couch, i use a BT mouse which has a very high sensitivity so a slight slip up make the controls disappear. For that reason i'd alternatively would like to change the fade out time.

I'd also like to set the default coordinates to somewhere else.

On a side note, i'd like to suggest another button for reset.

**Comment by Eisys** [comment]
> On a side note, i'd like to suggest another button for reset.

Can't you change that in the settings? Or do you want multiple reset keys? Because you can also do that.

**Comment by toppits** [comment]
> > On a side note, i'd like to suggest another button for reset.
> 
> Can't you change that in the settings? Or do you want multiple reset keys? Because you can also do that.

Button, not shortcut

**Comment by igrigorik** [comment]
It sounds like you may be editing the installed extension from the Chrome store? If so, yes, that will cause issues. You should install it as an unpacked extension instead.

**Comment by toppits** [comment]
Oh, indeed. Will try. Thank you
