### ISSUE TITLE
Music sounds warped and distorted

### ISSUE THREAD

**Issue by belson17** [igrigorik/videospeed#679]
Most audio is ok but music sounds so badly distorted that I can't use this extension if there's music.

**Comment by igrigorik** [comment]
That shouldn't be surprising. Music + higher speeds changes the tempo, etc. This is not a bug, this is an inherent property of accelerating playback.

**Comment by belson17** [comment]
The same effect doesn't happen when using youtube's built-in speed setting.

**Comment by aliirmak** [comment]
> The same effect doesn't happen when using youtube's built-in speed setting.

when using standard youtube speeds like 1.25 through settings, the sound is ok.
when I increase the speed using videospeed to, for example, 1.10, music sounds 'wavy'. 
It seems like tempo/pitch is desynching (increasing and decerasing - not stable) during the playback.
