### ISSUE TITLE
Embedded YouTube videos title cover controls, making it inoperable.

### ISSUE THREAD

**Issue by joshdance** [igrigorik/videospeed#68]
This has been happening for a while, but I finally remembered to document it. 

Here is the page with the embedded YouTube video, although it happens everywhere. - https://medium.com/@yegg/32-fast-cheap-marketing-test-ideas-across-all-19-traction-channels-24e227c3a8e3

http://recordit.co/tzeYUdTwwF - screen recording of the issue. 

Gif of the issue.
![video speed controller](https://cloud.githubusercontent.com/assets/597887/10259475/fd048a4e-6925-11e5-84c9-31e503d759ab.gif)

On a lot of pages that embed YouTube videos, the title covers the controls making it impossible to speed the video up. 

My work around is just opening the YouTube video on its own page on YouTube. Not ideal.

**Comment by truth1ness** [comment]
+100 Omg this is so annoying. Please fix this. This was requested before but I can't find the request anymore. This really needs to be fixed. The buttons are not functional and you cannot see what speed you are on. Literally all that needs to be done is to move it down 15 pixels.

**Comment by igrigorik** [comment]
Resolved via e405a5c.
