### ISSUE TITLE
Resets on Udemy

### ISSUE THREAD

**Issue by enigmatikme** [igrigorik/videospeed#680]
Speed controller resets speed every time video is paused/started again. Have found this issue on some other platforms but issues have been opened on them. Anyone have a solution/fix?

**Comment by pepijnmm** [comment]
whas this not fixed after pull request: #678 ?

**Comment by msouder** [comment]
I'm still getting this error, yet it says I have the latest version, 0.6.3 from Jun 25, 2020.  Is there a 0.6.4 out there that fixes this?  For me, it forgets my speed during youtube ads (going back to 1) and stays at 1 afterwards.  All the while it shows my speed as my preferred speed on the display.

Uncaught TypeError: speed.toFixed is not a function
    at setSpeed (inject.js:674)
    at tc.videoController.mediaEventAction (inject.js:215)

**Comment by igrigorik** [comment]
New release shipping this week, should address this. Please reopen if still the case next week.

**Comment by greendesertsnow** [comment]
The issue has been resurrected.
Udemy found a way to reset the player speed : D
It's probably because each page is SSR. Can we assign the player speed to the whole domain?
