### ISSUE TITLE
Controls not available at IGTV

### ISSUE THREAD

**Issue by ymellorj** [igrigorik/videospeed#681]
The Instagram video feature (IGTV) has no option to control playback speed

https://about.instagram.com/features/igtv - this page explains the video feature. The video featured at this page has the option (since is not same as displayed on regular Instagram feed), but if you go to any page that has a igtv video available (example: [https://www.instagram.com/tv/CCGfvD3JppC/] ) there is no option displayed.

Thanks,

**Comment by kubalav** [comment]
You have to remove Instagram from blacklist in options.

**Comment by ymellorj** [comment]
Thanks for the feedback, sorry I didn't know such option exist and was enabled.
