### ISSUE TITLE
Video speed controller / Facebook

### ISSUE THREAD

**Issue by Mia101317** [igrigorik/videospeed#682]
Hello, I'm new here !
I use video speed controller and I love it.
But since 1 week I can't use it on Facebook.
Am I the only one ?
Do you find a way to use it ?
Thanks !
Marie

**Comment by glgibson** [comment]
im having the same issue and its driving me crazy!!! everything seems so slow not on FB as i listen to a lot of videos/webinars!!! hopefully someone comes up with a solution!

**Comment by jmaessen** [comment]
Can confirm.  It looks like Facebook recently pushed a change that alters the click-sensitive area in the top left corner of video frames to be quite a bit larger and overlap the controls.  One possibility would be to allow moving the controls elsewhere in the frame.

**Comment by suzancz** [comment]
It doesn't work for me either. I'm devistated! I have so many videos to watch and I need this tool... but it won't work. Not just because something else is in the area. When nothing else is in the area, it still doesn't work. :-( :-(  

It might be because of the new version of Facebook that's out? :-(

**Comment by glgibson** [comment]
I managed to get back onto the old version of Facebook, after messing around for a while in the settings top right of screen! Now I can watch all my videos at the speed I want!

**Comment by xenstar** [comment]
Hello, yeah on Facebook it doesn't work for me either. I guess because I am using Facebook new Version. 

Hopefully the developers will fix it soon.

**Comment by pepijnmm** [comment]
Same problem as #693

**Comment by igrigorik** [comment]
Lets continue in #693
