### ISSUE TITLE
新网站的不支持

### ISSUE THREAD

**Issue by xxy-ixq** [igrigorik/videospeed#686]
对于  语雀  平台的不支持

**Comment by pepijnmm** [comment]
do you have an example of https://www.yuque.com/ where it doesn't work(where you don't need to login)?
The video on the front page seems to work:
![image](https://user-images.githubusercontent.com/3217184/87428756-1f347100-c5e3-11ea-9cab-df701bc09607.png)

**Comment by igrigorik** [comment]
Please reopen if you have an example URL.
