### ISSUE TITLE
Issues With Adblock

### ISSUE THREAD

**Issue by TheAgedGamer** [igrigorik/videospeed#687]
Ever since today. When I click another video. It will always go to 2X speed rather than staying at the remembered speed. And When i use it without Adblock it works perfectly fine. Is anyone else having this issue?

**Comment by igrigorik** [comment]
It sound like AdBlock might be changing the speed, which is persisted by this extension. Unfortunately, if so, there is nothing we can do about this.. This should be routed to the adblock team on why they have or want that behavior.
