### ISSUE TITLE
Create userscript of this extension?

### ISSUE THREAD

**Issue by TheAlienDrew** [igrigorik/videospeed#688]
I noticed that Issue https://github.com/igrigorik/videospeed/issues/239 was closed because of primary usage of Chrome specific features, but this was also in 2017. It's 2020 now, and I'm just wondering if the extension is more likely to get a userscript port instead, as I like to run my browser lightly off extensions.

Even if it's a userscript that works only on Chrome, that's still something I'd be interested in.

**Comment by igrigorik** [comment]
No current plans to offer it as an official userscript. Nothing against userscript, it's a problem of burden of maintenance.
