### ISSUE TITLE
Update for new Facebook interface

### ISSUE THREAD

**Issue by andrewaizumi** [igrigorik/videospeed#693]
Would you be willing to update this extensions to work with the new Facebook interface? 
Currently, it only works with the old one. 
Thank you.

**Comment by igrigorik** [comment]
Yes, absolutely. If someone can debug and figure out why it's not working with new design, that would be much welcome!

**Comment by pepijnmm** [comment]
The shortcuts still work for me but I idd can't click on the speed control.
It seems that the div in data-instancekey is on top of the video with position absolute and is full width/height. this div contains the player controller and the play button in the center when a video hasn't started yet. Not sure how we can put the speed controller on top of the facebook control div.
![image](https://user-images.githubusercontent.com/3217184/89837499-5f96f880-db69-11ea-8f9a-194fbb2f4527.png)

**Comment by igrigorik** [comment]
Related, #618: let's continue there.
