### ISSUE TITLE
REQ: Need Video Quality Change Shortcut

### ISSUE THREAD

**Issue by imsuvesh** [igrigorik/videospeed#694]
If we could map a key for changing video quality that would help a lot for some of the videos where we just want to listen to audio and don't want to waste data loading 1080p video.
Like 
Key 1 for 144p
2 for 240p
....

**Comment by pepijnmm** [comment]
is it not different for every player how they implemented it?
Can't find a html5 function for that.

**Comment by ChadBailey** [comment]
Unfortunately, @pepijnmm is correct this is not possible.
