### ISSUE TITLE
request: I want to always show control buttons on Video on Android Firefox/Edge etc...

### ISSUE THREAD

**Issue by kryu2** [igrigorik/videospeed#695]
request: I want to always show control buttons on Video on Android Firefox/Edge etc.
Because when I tap videos like YouTube shows buttons belong to site.
I have no idea that I can see Video Speed Contoroller buttons.

**Comment by sirati97** [comment]
the extension did work on older versions of android firefox.

however the mobile youtube player has the same problem like this issue  https://github.com/igrigorik/videospeed/issues/693

**Comment by igrigorik** [comment]
You can hit "v" shortcut (or change it to whatever key you like in settings) to toggle perma-visible controller.

**Comment by sirati97** [comment]
i am sorry but on a phone the concept of pressing a key is a bit more complicated.

while being outside of a textbox and as such anywhere where this plugin would listen for it, the keyboard is not shown to the user
