### ISSUE TITLE
Request: Add custom CSS supprot for Controller

### ISSUE THREAD

**Issue by snowman** [igrigorik/videospeed#696]
The font-size is too small for me. 

The font-size of `3rem` now is perfect for me by using `Grease Monkey`.

And there maybe other people  want to set other settings like `position` of controller. 

Thanks a great job 👍

**Comment by snowman** [comment]
For thoes interesting, here is the code:

```javascript
// ==UserScript==
// @name        CSS - Video Speed Controller
// @description Change styles of Video Speed Controller
// @version     1.0
// @author      100000011101
// @match       <all_urls>
// @require     http://code.jquery.com/jquery-3.4.1.slim.min.js
// @grant       GM_addStyle
// @grant       GM.getValue
// ==/UserScript==

(function() {
  $(document).ready($ => {
    const styles = `
    #controller {
      opacity: 0.8;
    }

    #controller:hover {
      opacity: 0.8;
    }

    #controller button {
      font-size: 2rem;
    }

    #controller span.draggable {
      font-size: 3rem
    }
  `;

    const shadowInternalCSS = shadowRoot => styles =>
      $(`<style class="custom" type="text/css">${styles}</style>`).appendTo(
        shadowRoot
      );

    const containerSelector = "div.vsc-controller[data-vscid]";

    setTimeout(
      () => shadowInternalCSS($(containerSelector).get(0).shadowRoot)(styles),
      1000
    );
  });
})();
```

**Comment by pepijnmm** [comment]
Maybe you can give some more info on #499 to help implement it. Although your proposal is different from that issue.

**Comment by igrigorik** [comment]
@snowman neat script! I'm wary of adding a straight up CSS/JS injection capabilities, as that will undoubtedly get abused in various ways. That said, I do think it's a great idea to offer some preconfigured options for controller styling and size. Perhaps something you'd be willing to contribute? Let's continue in #499.
