### ISSUE TITLE
Captions don't sync beyond 2x speed

### ISSUE THREAD

**Issue by VimalMollyn** [igrigorik/videospeed#698]
Hi!

So I was watching a lecture at 2.5x the other day, and I noticed that the captions were lagging behind by a bit. Any idea why this could be happening? It's important to note that these were auto-generated captions, I'm not sure if this happens with the other captions.

Thanks!

**Comment by pepijnmm** [comment]
Sounds like a browser problem or the website that you used has a weird way of subtitle implementation.

**Comment by igrigorik** [comment]
Can you share example URL where this is happening?

**Comment by igrigorik** [comment]
Related: #537, let's continue there.
