### ISSUE TITLE
Speed settings do not persist between videos in Jellyfin player

### ISSUE THREAD

**Issue by pooki3bear** [igrigorik/videospeed#699]
Video speed controller resets the speed to 1.00 when changing episodes. The error below is show in my console.

![Screen Shot 2020-08-28 at 12 23 50 AM](https://user-images.githubusercontent.com/24210410/91533574-f501ee80-e8c4-11ea-937a-74775b8c64eb.png)

**Comment by pepijnmm** [comment]
Already fixed with https://github.com/igrigorik/videospeed/pull/678
Not sure when the Google store version will be updated @igrigorik

**Comment by msouder** [comment]
@pepijnmm Any idea when the updated version will be pushed to the google store?

**Comment by pepijnmm** [comment]
Nope sorry. I am just a developer that sometimes makes a pull request and checks issues.

**Comment by igrigorik** [comment]
Could have sworn I already pushed the update for this. Apologies for the delay, will get the new version out this weekend.
