### ISSUE TITLE
Periscope videos don't have controls

### ISSUE THREAD

**Issue by joshdance** [igrigorik/videospeed#70]
Not flash, pretty sure it is HTML5, but no controls pop up. 

https://www.periscope.tv/w/1BdxYarWEzExX

**Comment by igrigorik** [comment]
If I disable flash plugin in chrome via chrome://plugins/, I get...

![image](https://cloud.githubusercontent.com/assets/10652/11017110/be3b0dc0-8549-11e5-9b99-ff1f1c688cc6.png)

Unfortunate, to say the least.
