### ISSUE TITLE
Contoller disappears after some time 

### ISSUE THREAD

**Issue by Nomannoman** [igrigorik/videospeed#701]
There should be a button enabled which allows users to make the controller disappear when user wishes

**Comment by pepijnmm** [comment]
![Screenshot_20200906-134849](https://user-images.githubusercontent.com/3217184/92325288-961d4180-f049-11ea-9b6c-abe7963d6117.png)
Have you read the first page of this github?

**Comment by Nomannoman** [comment]
Thank you. I understood.
