### ISSUE TITLE
No effect on Vimeo

### ISSUE THREAD

**Issue by luismarques** [igrigorik/videospeed#71]
The extension seems to have no effect on Vimeo / Chrome 46.0.2490.80 (64-bit) / OS X. (The video on Vimeo seems to HTML5 and not Flash)

**Comment by igrigorik** [comment]
Any particular link? Testing on vimeo.com seems to work on this end.. I see the controller and it works as expected. Try disabling flash in your plugin settings: chrome://plugins.

**Comment by adishavit** [comment]
FYI:
This works: https://vimeo.com/157708450
This (orgianl link)  doesn't: https://vimeo.com/157708450?utm_content=bufferbe624&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
