### ISSUE TITLE
Feature request: apply to audio streams as well

### ISSUE THREAD

**Issue by nucatus** [igrigorik/videospeed#711]
Sorry if this is not the proper channel for a feature request. However, since I love so much how this plugin works for video streams, I'd love to have the same shortcuts having the same effect on audio streams, like podcasts & stuff.

Thanks!

**Comment by igrigorik** [comment]
Good news, this is already a thing! 👍 

![image](https://user-images.githubusercontent.com/10652/94512158-39d4ba00-01d0-11eb-8dc4-15c55d292a88.png)

Enable the audio option in extension settings and that should do the trick.
