### ISSUE TITLE
Support for Teamtreehouse.com

### ISSUE THREAD

**Issue by anthonyattard** [igrigorik/videospeed#72]
The speed cannot be adjusted on Teamtreehouse.com The current vido speed shows in VSC but cannot be modified. The speed can only be changed with their built in control which is limited to 2x.

**Comment by igrigorik** [comment]
Unfortunately I don't think we can do anything about this on this end... It looks like they have own logic that listens to updates to the playback speed and resets it to their own setting.

**Comment by anthonyattard** [comment]
Thanks for looking into it.

**Comment by ChadBailey** [comment]
Pulling this one out of the vault, but it looks like this may be fixed by the recent fix I'm pushing for twitch.tv. Once it's been merged, I'd love someone to test for me to confirm (I don't have an account to test)
