### ISSUE TITLE
Call the keyevents using script

### ISSUE THREAD

**Issue by iamgmujtaba** [igrigorik/videospeed#725]
Hi There,

Thank you for the amazing plugin and repository.
I just want to know, can I call keyevents using the script like an API function?

For example, the keyboard key 'V' is used in the shortcuts setting, and using the javascript I can show/hide the controller.

Thank you

**Comment by pepijnmm** [comment]
You can't access the content script file variables. https://stackoverflow.com/questions/9602022/chrome-extension-retrieving-global-variable-from-webpage/9636008#9636008 .
What you of couse could do is simulate a key press for example pressing V:
```
var evt = new KeyboardEvent('keydown', {'keyCode':86}); 
document.dispatchEvent(evt); 
```
to find out which code is which check: https://keycode.info/
