### ISSUE TITLE
Youtube Live - Color problem

### ISSUE THREAD

**Issue by miticocampo** [igrigorik/videospeed#73]
Dear developers,
I am experiencing problem while watching Youtube lives, since the speed indicator is confused with the Google logo in the background.
Is it possible to add a feature to change the colour and characters dimensions of the speed indicator or   a feature to move the indicator in the videoplayer.

Thanks so much for your tool.

![img](https://cloud.githubusercontent.com/assets/16059281/11452309/8713c800-95e3-11e5-8397-deb6e91ee57a.png)

**Comment by igrigorik** [comment]
Merging with https://github.com/igrigorik/videospeed/issues/82.
