### ISSUE TITLE
After changing site blacklist I'm unable to change speed from 1x on netflix

### ISSUE THREAD

**Issue by mariusi7** [igrigorik/videospeed#733]
Increasing speed doesn't work on netflix.com, it immediately resets to 1.00. Preferred speed (2x) doesn't work either.
No error in Console.
Still works on other website.
Works in different Google user's Chrome. Works in incognito mode.
How it started: needed speed on Instagram, removed all blacklisted sites.

What I tried unsuccessfully:
- put back the list of blacklisted sites
- reset extension settings
- reinstalling it (multiple times)
- cleared the browser (history, cookies, cache)
- deleted all folders for "nffaoalbilbmmfgbnbgppjihopabppdk" in my profile (including under Sync Extension Settings) and reinstall
- switched Sync OFF, reinstalled the extension with it off

Any idea what can I do @igrigorik  ? 

Version 0.6.4, Chrome 87.0.4280.66 (Win 10 and Chrome OS)
Current settings: https://i.imgur.com/gkNp2Cd.png

**Comment by pepijnmm** [comment]
"nffaoalbilbmmfgbnbgppjihopabppdk" is your extension GUID?
You tried the most options I can think of(reinstall, delete settings,cache)
You probobly already tried most options from this list: https://superuser.com/questions/451129/is-it-possible-to-reset-all-google-chrome-extension-settings

Another not great solution you can try is to sideload the extension. Then it should not use any settings left by the extension.
check out https://github.com/igrigorik/videospeed/issues/731#issuecomment-735287877 if you not sure how to sideload extensions.

**Comment by mariusi7** [comment]
The problem magically went away by itself after 2 days (no change)
