### ISSUE TITLE
Doesn't work on Whats App Web (Chrome)

### ISSUE THREAD

**Issue by abg88** [igrigorik/videospeed#735]
I could use Videospeed Controller to speed up Whats App Web audios in Opera, but I've not been able to do the same in Chrome. Why is that?

PS: I REALLY like this extension.

**Comment by pepijnmm** [comment]
![image](https://user-images.githubusercontent.com/3217184/100519893-0cd66080-319b-11eb-8473-a4b6bd763af3.png)
works for me(I use the master from git). did you enable "Work on audio" in options?

**Comment by abg88** [comment]
Jeez, I totally forgot I had enabled this option in Opera xD
Thanks! It's working great on Chrome.
