### ISSUE TITLE
Save per webpage

### ISSUE THREAD

**Issue by iVictim** [igrigorik/videospeed#74]
Maybe you could make it remember my settings per webpage, like auto skip videos... Works perfectly as an adblocker for some pages, where they detect ad blockers :)

**Comment by igrigorik** [comment]
It's not the intent of this extension to be an ad-blocker.. :) 

Adding per URL memory would also result in having to persist URLs you've visited + your settings, which would result in ~history mechanism that I'd like to avoid (would require additional warnings, disclosures, etc).

Closing as wontfix. Thanks for the feedback!
