### ISSUE TITLE
Wrong controller UI shape in embedded videos on Discord 

### ISSUE THREAD

**Issue by Mhowser** [igrigorik/videospeed#746]
As you can see, the speed controller UI is misshaped and clips off the thumbnail. Also I think it should not show up until the video is actually playing.
![speed error](https://user-images.githubusercontent.com/24195572/103800462-523f4680-5001-11eb-8bce-a7566ef99864.png)

**Comment by kuzmeech** [comment]
@pepijnmm, thank you, looks like it fixes it! 
![image](https://user-images.githubusercontent.com/2181438/107303540-39391380-6a4d-11eb-85a4-640af1ba834f.png)
