### ISSUE TITLE
How to blacklist twitch channels but not VODS

### ISSUE THREAD

**Issue by rocketer13579** [igrigorik/videospeed#749]
So I'm trying to use the regex to blacklist these sites:
https://www.twitch.tv
https://www.twitch.tv/lcs
https://www.twitch.tv/[insertrandomchannel]

While not blacklisting the following:
https://www.twitch.tv/videos/12345678

Below is what I've come up with and though it seems to have proper functionality on regexpal.com and regex101.com, it doesn't seem to work with this extension. (Yeah its definitely sloppy and inefficient but it should work no?)
It doesn't actually blacklist normal twitch channels
/(https:\/\/www\.)twitch\.tv(?!\/videos\/[0-9]+)(.*)/g

I also tried this solution from issue #167 and it also seems to not properly blacklist normal twitch channels
/(.+)twitch\.tv\/[^\/]+$/g

I also looked at issue #542 but I want to blacklist certain subdomains, not just the main domain

**Comment by deefdragon** [comment]
I have attempted to use the regex for this exact scenario myself, but have been unable to get it to work.

**Comment by silentbrains** [comment]
Could you try this? `/www\.twitch\.tv\/(?!videos)` (leave off the trailing regex stuff)

**Comment by deefdragon** [comment]
That works. It took me a bit to realize, but going from a stream page to a vod page (and or the other way arround), you have to reload to get the controller to show up. I expect this is due to the single page nature of twitch.

**Comment by silentbrains** [comment]
Ah, whoops, thanks for catching that. I'm not sure why it has that behavior.

**Comment by rocketer13579** [comment]
huh the controller doesn't show up on stream pages (even when I use the "show controller" shortcut), but the keyboard shortcuts still affect the speed of livestreams. I suppose this means that the regex properly works but the twitch video player has some weird stuff goin on
