### ISSUE TITLE
Youtube videos' visuals freeze for a while after tabbing out

### ISSUE THREAD

**Issue by JuniorUdale** [igrigorik/videospeed#761]
Since the most recent Chrome update, there's been an issue with sped up Youtube videos, where tabbing out makes the visuals "speed up" too much, then hang for a while while they wait for the video to catch up. To reproduce:
* Open a Youtube video
* Speed the video up (only tested at 2x speed)
* Tab out for ~5 seconds (the audio should remain normal)
* Tab back to the video
* The video's visuals will be past what they should be: here, for example, 10 seconds of video time has passed, but the visuals will display as though ~15 seconds have passed
* The video will then "catch up" with the out of sync visuals after a short while.
Currently on Chrome 88.

**Comment by pepijnmm** [comment]
Do you also have that when turning the extension off and use YouTube build in speed changer? Not sure if it's something we can fix if then the problem also acurse. We just use html5 build in speed changer

**Comment by JuniorUdale** [comment]
Oh, it does seem to be an issue with the built-in speed settings as well, huh. Looks like this is just on my end then!
