### ISSUE TITLE
No Effect - Kaltura Video Player

### ISSUE THREAD

**Issue by cam1daman** [igrigorik/videospeed#78]
My university uses Kaltura Video Player to post lectures online.  After downloading this video speed extension, I see tooltip icon, with buttons to adjust speed.  However the buttons are unresponsive in speeding up video.

Any-thoughts? Much appreciated.

**Comment by igrigorik** [comment]
Do you have a public URL that I can test? As a sanity check, have you tried disabling flash in your chrome://plugins?

**Comment by cam1daman** [comment]
I disabled flash player, no luck. Best public example I could fine was on the company website.  Unfortunately your extension does not appear on the public ones.  

Example:
http://corp.kaltura.com/Products/Video-Applications/Canvas-Video-App

Screenshot of embeded player on university site:
![image](https://cloud.githubusercontent.com/assets/16637878/12226921/54492316-b7e9-11e5-9c39-1f0ece557af2.png)

**Comment by igrigorik** [comment]
This should be addressed once we merge https://github.com/igrigorik/videospeed/pull/80.

**Comment by igrigorik** [comment]
Closing, #80 should resolve this.
