### ISSUE TITLE
controller position botched on youtube

### ISSUE THREAD

**Issue by paulirish** [igrigorik/videospeed#786]
in https://github.com/igrigorik/videospeed/pull/752 i changed how the controller is positioned. 
this change is landed in git, but hasn't gone to CWS yet.

today @pepijnmm  reported a bug about my change:

> @paulirish For me this merge breaks the youtube controller position(just noticed hadn't updated in a while)
> I tested compared to enforce normal white-space rendering for controller (#753) so only this commit changed things
> Before merge:
> <img alt="Screenshot_8" width="235" src="https://user-images.githubusercontent.com/3217184/111382338-272f3e00-86a7-11eb-876a-04b0971c1114.png">
> after merge
> <img alt="Screenshot_7" width="585" src="https://user-images.githubusercontent.com/3217184/111382398-3b733b00-86a7-11eb-9164-f3b03c57d303.png">

i can repro this as well.

fixing this is going to require some more thinking (and some testing..)  

We'll have to find a positioning calculation that's respectful of offsetParent but still gives results across all target sites.

**Comment by 0x7633** [comment]
Many players have this problem. Here are 2 more examples:

instagram.com:
![image](https://user-images.githubusercontent.com/52445324/111441528-5f378f00-8742-11eb-9a73-d448f7ab1cab.png)

fox.com.tr:
![image](https://user-images.githubusercontent.com/52445324/111441684-83936b80-8742-11eb-8dff-9b46c5c9289e.png)

**Comment by pepijnmm** [comment]
@igrigorik is it maybe better to reverse https://github.com/igrigorik/videospeed/commit/a25373f1d831fe06430c2e9e87dc1bd1aabd25b1
if it breaks more then it fixes?
if no one will fix it as temp we could do also do if else where if is for hulu right?(for now I will just stay on the previous release.

**Comment by russelldavis** [comment]
Update: there's a simple fix by subtracting the `getBoundingClientRect` of the `offsetParent`. PR here: https://github.com/igrigorik/videospeed/pull/854
