### ISSUE TITLE
Green video patches

### ISSUE THREAD

**Issue by crimsonBlazee** [igrigorik/videospeed#787]
This is reproducible on my laptop and desktop, both running Windows. Regardless of the video speed set through the video controller extension, I can reproduce this by:
1. Toggling to fullscreen on any YouTube video (not sure about other websites)
2. Switch to a different virtual desktop
3. Switch back to the original virtual desktop
4. Now the fullscreen video has the green artifacts, as seen in the screenshot below

![image](https://user-images.githubusercontent.com/32075539/111568401-0df5c280-8777-11eb-9ee7-48b665143ea9.png)

**Comment by pepijnmm** [comment]
Is this not a chrome bug? Does it not happen is you disable the extension?

**Comment by crimsonBlazee** [comment]
I thought I already ruled this out by disabling the extension on Chrome. Looks like I was wrong. Thanks for catching that. I will close this issue.

**Comment by crimsonBlazee** [comment]
In case someone else comes across this Chrome bug, here is a set of instructions that I found helpful and it may be of some use to your situation as well:

https://support.google.com/youtube/answer/1230977?hl=en
