### ISSUE TITLE
This extension does not work in Brave browser! disappointing! 

### ISSUE THREAD

**Issue by polkmniujhb** [igrigorik/videospeed#797]
Please help

**Comment by ChadBailey** [comment]
This extension does work in Brave, that is my primary browser. If you're having trouble please open a new issue with more details.

**Comment by polkmniujhb** [comment]
Chad,
I gave you all the details. Never-mind. 
    On Wednesday, April 14, 2021, 11:30:11 PM MDT, Chad Bailey ***@***.***> wrote:  
 
 


Closed #797.
