### ISSUE TITLE
Move Controls 

### ISSUE THREAD

**Issue by Shot007** [igrigorik/videospeed#82]
Please make it so that controls can be moved especially on Netflix videos, this is extremely annoying and it makes it difficult to increase/decrease the speeds on Netflix videos.

**Comment by atlas6523** [comment]
This was already opened as this issue: #75 https://github.com/igrigorik/videospeed/issues/75 . It's always a good courtesy to do a little checking to make sure that your issue hasn't already been asked or discussed.  It makes it easier for everyone, including yourself, to see what the group's thoughts are on the problem.

**Comment by Shot007** [comment]
I saw it. But also noticed it was over 2 months ago. I thought a newer post might make the developer see how important this is and how others are also affected by it.

**Comment by igrigorik** [comment]
Closing, landed via https://github.com/igrigorik/videospeed/pull/120.
