### ISSUE TITLE
Remember playback speed & Sites disabled can result in background speed increase

### ISSUE THREAD

**Issue by ZKjellberg** [igrigorik/videospeed#834]
If you use a website with **Remember playback speed** and set to an accelerated speed such as 1.8 and then add the website to **Sites on which extension is disabled**, the extension will appear disabled yet will still retained the accelerated speed.

**Comment by thewheat** [comment]
Thanks for the report @ZKjellberg 

When you mentioned that it still retains the accelerated speed, do you mean on a page reload or without reloading the page?

- If you mean **without a page reload**, I believe that is just the way the plugin works but could be treated as a feature request
- If you do mean that it happens even with a page reload, I could not replicate the issue. On reloading the page the control didn't show and it played at normal speed. Are there any steps below that I'm doing which are different? 

**My steps are as follows**

- Go to a Youtube video
- Set a speed
- Add site to disabled list 
![image](https://user-images.githubusercontent.com/892961/131211109-ce18d56d-2224-4b88-ae83-cc8d5303552c.png)
- Click save
- Reload page

**Comment by ZKjellberg** [comment]
I sadly have not been able to replicate the issue. I was experiencing websites defaulting to 1.8 preferred speed (without any memory of ever setting that speed) and then somehow having that speed even retained when whitelisted. 

The issue was first encountered on swr3.de (a German radio station) with the 'Work on audio' feature enabled.

I've tested the workflow again on this website and was unable to replicate.
