### ISSUE TITLE
VSC speed keeps getting reset whenever a new video plays on YT

### ISSUE THREAD

**Issue by OctoChara** [igrigorik/videospeed#836]
As the total says, VSC resets every time a new video plays on YouTube. Earlier this morning, an error message happened on YouTube so I ended some of Brave’s tasks so I could reload the page and continue the video. Then after that it just stopped working properly and it’s getting pretty annoying having to press the G key every time I wanna watch a vid at my preferred speed. Sorry to bother you with this.

EDIT 1: “Remember Playback Speed” is on, I saved the setting and restarted the app, restarted my pc,  ended all of brave’s tasks. Restarted the extension’s settings to default (did te necessary steps to apply them), and put my settings back.

Edit 2: I deleted the app, reinstalled it, and tried again, still didn’t work. I’ll try more things tomorrow. I also would like to mention that I have no coding experience whatsoever.

**Comment by djasil** [comment]
It started happening to me on YT playlists. Checking the option **Force last saved speed** solved it. See if it works in your case too.

**Comment by OctoChara** [comment]
> It started happening to me on YT playlists. Checking the option **Force last saved speed** solved it. See if it works in your case too.

I can’t find that setting.

**Comment by djasil** [comment]
Apparently the version from Chrome Web Store doesn't have this setting. You have to pack and import the extension from this repository.
![img1](https://user-images.githubusercontent.com/25281624/129998342-eaa3317b-c16d-415c-ae3f-3119cb029438.png)
This setting was included in Sep 18, 2020 (see commit history).

**Comment by OctoChara** [comment]
It worked! Thank you! Everything’s fixed and I’m able to continually watch vids at my preferred speed!
