### ISSUE TITLE
Netflix- Can't change speed (shortcut method) in fullscreen

### ISSUE THREAD

**Issue by atlas6523** [igrigorik/videospeed#85]
While playing a video in Netflix, fullscreen, you cannot change the speed with the shortcut keys.  The gui does however, still work.  Same qualifications as the other issue I opened.  I don't know if you can fix this, but I still love and appreciate your work even if you can't.  Thanks for all of this.

**Comment by igrigorik** [comment]
Can you try "shift-KEY"? Netflix may be capturing those keys in their app.

**Comment by igrigorik** [comment]
Closing. Please feel free to reopen if shift-KEY doesn't work.
