### ISSUE TITLE
Video Speed controller per IPad 

### ISSUE THREAD

**Issue by sofi2201** [igrigorik/videospeed#858]
Anche se dopo aver installato chrome sul dispositivo e aver installato l’estensione si Speed, non appare nei video la possibilità di accelerane la riproduzione. Come posso fare? È compatibile con iPad?

**Comment by Kyle-Ye** [comment]
> Anche se dopo aver installato chrome sul dispositivo e aver installato l’estensione si Speed, non appare nei video la possibilità di accelerane la riproduzione. Come posso fare? È compatibile con iPad?

Maybe you can try the Safari Extension Version https://testflight.apple.com/join/fyXYXyHP

**Comment by Kyle-Ye** [comment]
Chrome on iPad seemed not allowed to install extension
