### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Kyle-Ye** [igrigorik/videospeed#875]
I make a Mac-Safari version of this project last year, and someone was asking me for a iOS version.(Available since iOS 15)

> See https://github.com/igrigorik/videospeed/pull/766

But that means it needs to update it to the App Store (Or TestFlight) (Of course I will make it free and open-source if it can be on App Store https://github.com/Kyle-Ye/Video-Speed-Controller) 

This project is licensed under MIT. I don’t know if the two are compatible (The App Store License and the project's MIT license)

Can anyone help with it?  @igrigorik 🥰

**Comment by ajayyy** [comment]
The license should be fine, the only issue is with GPL family

**Comment by Kyle-Ye** [comment]
TF link: https://testflight.apple.com/join/fyXYXyHP (Feedback is welcome)

**Comment by parkleo121212** [comment]
> TF link: https://testflight.apple.com/join/fyXYXyHP (Feedback is welcome)

I was waiting for it! I use it on my iPhone with 15.1 db, it works very good! Settings open well and rewind and forward, speed control works pretty nice! 
But I found some bug that when you set speed over 2, video stop or lag a lot. 
And for better experience on mobile device, it would be better if there are one more button on controller which can switch between normal speed and preferred speed. Love your app, and is it okay to share TF link on other community? Thanks! 😊

**Comment by Kyle-Ye** [comment]
> > TF link: https://testflight.apple.com/join/fyXYXyHP (Feedback is welcome)
> 
> I was waiting for it! I use it on my iPhone with 15.1 db, it works very good! Settings open well and rewind and forward, speed control works pretty nice! But I found some bug that when you set speed over 2, video stop or lag a lot. And for better experience on mobile device, it would be better if there are one more button on controller which can switch between normal speed and preferred speed. Love your app, and is it okay to share TF link on other community? Thanks! 😊

1. "When you set speed over 2, video stop or lag a lot" I think it's the normal behavior as the original extension behaves like this. And that's why most the video platforms which give the speed control will limit the max speed to x2
2. "it would be better if there are one more button on controller which can switch between normal speed and preferred speed" Can you describe it more clearly, maybe post a Feature Request Issue on this repo https://github.com/Kyle-Ye/Video-Speed-Controller/issues/new/choose
3. "is it okay to share TF link on other community?" Of course, you can. And after you share on other community, would you mind send me the community website/post?
