### ISSUE TITLE
Extension breaks video playback in Instagram

### ISSUE THREAD

**Issue by strabbit** [igrigorik/videospeed#88]
When the extension is enabled, playing video in Instagram results in audio being heard, but only a still image from the video is shown. Disabling the extension results in normal behavior.

**Comment by igrigorik** [comment]
I've looked into this earlier this weekend. There is an odd interaction with the Instagram code that's really hard to debug.. without being super invasive. After a few attempts, I ended up settling on a simple strategy: disable extension on instagram + twitter, where you see these short loop videos -- the extension doesn't add anything for those; if anything, it's a nuisance.

Resolved in https://github.com/igrigorik/videospeed/commit/2e5d4981dc5498830c5677b93a4b2436b5cf05d3. 

Closing. The above fix will be in the next release.
