### ISSUE TITLE
Feature Request - Downloads

### ISSUE THREAD

**Issue by RajatShenoi** [igrigorik/videospeed#909]
Hey there, first of all I would love to THANK YOU for all the help you've done with this extension. This is very useful.

The one thing I would request is, I know that you will gain access to the video link in order to forward and rewind it. So if there would be a feature which will help us get the link of the video using which we can access that video file, it will help a lot!

**Comment by i-c-u-p** [comment]
Probably won't get added. For downloading videos a good tool is [yt-dlp](https://github.com/yt-dlp/yt-dlp/)
