### ISSUE TITLE
Controls fade out after I set speed.  Not able to bring back or adjust after that.

### ISSUE THREAD

**Issue by lavedon** [igrigorik/videospeed#91]
Hello,

Thank you for this wonderful extension.  I apologize if this has been asked elsewhere, I looked through the closed issues but couldn't find anything.

In the past couple of days I noticed that after I adjust the speed for a YouTube video or Netflix video the controls fade away.  Keyboard short cuts will also not work once the control panel fades out.  

I am using version  0.2.7.

In reading the other issues, I understand that when the YouTube controls are visible the extension controls are supposed to be visible also I believe? Previously, the controls were always visible on any video unless I pressed X.  This worked well for my purposes.  If the keyboard shortcuts still worked I wouldn't mind having the controls fade out.  The problem is not being able to bring them back.

If this is a new feature, is there a way to make it optional?  Is there a way to choose to have the controls always displayed or bring them back?  The only way I have to adjust the video once I set the initial speed is to reload the web page.

Thank you for any help, and thanks for all your hard work on this fantastic extension!

--Luke

**Comment by taxandria** [comment]
I've been noticing this exact problem. The speed control in the top left of the video fades out and I can't get it back without refreshing the page. Did you change something in the past couple of days? I will have to find another speed controller if this isn't fixed. Been using this one for months now and it's been great.

**Comment by vfenelon** [comment]
I am having almost the same problem, nevertheless when I used the keyboard controls, it works the control appears  but return to fade out quickly.

**Comment by Geroc** [comment]
Thanks for making this convenient extension. I've noticed this frustrating issue in the last few days also. This is such a great extension, so if a fix is on the horizon, that'd be much appreciated.

**Comment by Eisys** [comment]
You guys should revert back 0.2.6.
0.2.7 has quite a few little problems.

You can do this by [going to this link](https://github.com/igrigorik/videospeed/tree/20fc3472eb428317861ba75463b1cf8ab3b1bd03), Download as ZIP, unpack it and drop the folder into the extensions page. Make sure to disable the newer version.

**Comment by lavedon** [comment]
Thanks Eisys!!

**Comment by g8tr1522** [comment]
I had this problem too. Thanks for the solution

**Comment by indy14** [comment]
Oh literally drag and drop the file into the chrome extensions page on the browser...

Here i was trying to copy the folder to Google\Chrome\User Data\Default\Extensions\nffaoalbilbmmfgbnbgppjihopabppdk....

Thanks!

**Comment by bananakid** [comment]
I report the same issue. Rolling back to 0.2.6 helped.

**Comment by hho** [comment]
@igrigorik: The offending commit is f1827ba. Once the controller is set to invisible, the mouseover doesn't seem to trigger anymore.

**Comment by craigalan** [comment]
Everything works until I adjust the speed, then the controls fade out and then I can't get they to re-appear.  This is in regards to YouTube and NetFlix...the latest version seems to work with Tablo.

Regardless, reverting back to previous version works for everything.  Hope a fix is found.

Thanks for the great extension!

**Comment by igrigorik** [comment]
@hho indeed. Removed that behavior in: e2f7dbf. 

Testing locally, the behavior appears to be fixed. That said, I'd appreciate if you guys could test this on your end before we cut the next release:
- git checkout or download the ZIP of latest code from the repo
- installing the latest extension manually: https://developer.chrome.com/extensions/getstarted#unpacked

**Comment by Eisys** [comment]
@igrigorik Tried it out. Seems to work just fine so far. And the numpad keys work too.

**Comment by igrigorik** [comment]
@Eisys ... \o/ - thanks for confirming!
