### ISSUE TITLE
Feature request: add "stop autoplay" functionality for YouTube

### ISSUE THREAD

**Issue by okyr-ux** [igrigorik/videospeed#912]
I realize that such functionality might be not in scope of this extension, but I think it would be extremely convenient for the users.

**Comment by okyr-ux** [comment]
I realize that such functionality might be not in scope of this extension, but I think it would be extremely convenient for the users.

**Comment by brunubarbosa** [comment]
In which case, it would be useful?

**Comment by farzher** [comment]
> In which case, it would be useful?

every once in a while youtube will randomly re-enable autoplay for people. i remember 1 day specifically when autoplay would enable everytime you reload the page.

here it is, march 4th: https://twitter.com/search?q=(youtube%20autoplay)%20until%3A2022-03-05%20since%3A2022-03-03&src=typed_query&f=top

**Comment by okyr-ux** [comment]
> In which case, it would be useful?

Our browser is our space, where we control almost everything. The browser extension is a part of our browser.

A website, on the other hand, is not our space, so it's harder to implement our preferences to the website's contents. One site decides to auto-play videos, another site decides something else. As a user, I would like to be able to have more control over the video playback.

I've just noticed it's possible to add a Pause action in Settings — that's great! Maybe, it's easy to implement auto-pause on video start setting?

**Comment by igrigorik** [comment]
This is out of scope for this extension. The intent is to provide a platform agnostic set of speed controls.. we don't want to specialize for YT or other platforms.
