### ISSUE TITLE
Make "Reset Speed" toogle (to jump back to last "Cruise Speed") ?

### ISSUE THREAD

**Issue by metadirective** [igrigorik/videospeed#92]
Love this extension, thanks so much! 

Very often each video has a "cruise speed" for me that I adjust at the beginning with D/S keys.  
Then comes a concept or something I'm unfamiliar with; I Reset Z, understand it but want to jump back to "cruise speed"; I must then hit many key strokes. 

I'd love if I could go back to my speed before Reset. Did I miss something? Any advice?

Anyway thanks again!

PS: I use VideoSpeed a lot with screencasts on visual tools like Blender. I use R to rewind but often I can't stay in "cruise speed" because the visual action (clics and shortcuts etc) is more quicker than the "talking action".

**Comment by igrigorik** [comment]
> I'd love if I could go back to my speed before Reset. Did I miss something? Any advice?

No, what you're seeing is the 'as designed' behavior. We remember your last set speed setting (if you enabled that option) and then apply it on the next video. The behavior you're describing is currently not possible.. The closest would be: unset the 'remember playback speed' option, which means that every video would start from 1x and you can adjust it as needed.
