### ISSUE TITLE
LinkedIn Learning is limiting max speed to 2.0. Can something be done?

### ISSUE THREAD

**Issue by BWevv** [igrigorik/videospeed#920]
It seems as if LinkedIn Learning is capping speed at 2.0. I didn't notice this being the case until the beginning of February. Whenever i try to increase the speed past 2.0 (2.5, 3.0, etc.), the controller reverts back to 2.0.

You won't get the speed cap issue by previewing classes. In my experience, it's only happening when logged in and actually taking a course.

**Comment by magnus-ISU** [comment]
This is what the "Force video speed" feature is supposed to work around, I believe. It stops websites from seeing change-speed events. Have you tried that?

**Comment by BWevv** [comment]
This worked. Thank you!

**Comment by ps202104** [comment]
How do we use the "Force video speed" feature?

**Comment by ps202104** [comment]
I see "Force Last saved speed" feature is a check box under options:
chrome-extension://nffaoalbilbmmfgbnbgppjihopabppdk/options.html
https://github.com/igrigorik/videospeed/pull/661 "Force video speed"

**Comment by aizazulhaq34** [comment]
U can also paste below in Dev tools<console
document.querySelector('video').playbackRate = 15

Adjust rate at last as per convenience.
