### ISSUE TITLE
Adding an option for audio stretching instead of being choppy when slowed down?

### ISSUE THREAD

**Issue by coldiceEVO** [igrigorik/videospeed#931]
The ancient way of audio slow down by stretching is much bearable at very low speed. It would lowered the frequency, thus the sound pitch is lowered. 
The current way of chopping can be very hard on the ears. The intention for corrected pitch by chopping creates too much audio glitching sound at extrema low speed. Most likely this is how youtube or the entire browser(mine is chrome and firefox)/html5 handles audio playback speed.

**Comment by igrigorik** [comment]
Unfortunately (and thankfully :)) this is handled by the browser's media engine, we have no control over it.
