### ISSUE TITLE
Shortcut do not work anymore

### ISSUE THREAD

**Issue by dankmeme23** [igrigorik/videospeed#94]
None of the shortcut work. It's been like this for few weeks.

**Comment by Eisys** [comment]
See #89

**Comment by igrigorik** [comment]
We've landed https://github.com/igrigorik/videospeed/pull/96, which should fix this behavior.

It'll take at least a few days to test and release it to the store. In the meantime, you can try installing the latest extension manually: https://developer.chrome.com/extensions/getstarted#unpacked - if you do, and still run into problems, please let me know!
