### ISSUE TITLE
NOT working in Alison.com

### ISSUE THREAD

**Issue by 13thRavenPurple** [igrigorik/videospeed#955]
NOT working in Alison.com using Brave Browser Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)

**Comment by ChadBailey** [comment]
Can you elaborate? Does the speed not adjust at all, or does it quickly bounce back to the original speed?

**Comment by ChadBailey** [comment]
Please re-open with additional details when you find time.
