### ISSUE TITLE
Problem with site exclusion

### ISSUE THREAD

**Issue by Clemens123** [igrigorik/videospeed#961]
First of all, thanks very much for the extension, I love it! 😍

Now I'm trying to exclude twitch.tv (livestream) from being accelerated by the extension, but it does not work. I added the following regexes in the options, but none of them seem to take effect:
```
/(.+)twitch\.tv(\/*)$/gi
.*twitch\.tv.*
/.*twitch\.tv.*/gi
/.*twitch\.tv.*/g
```
Is this a bug or am I doing something wrong?

#regex #blacklist #whitelist #disabled

**Comment by ChadBailey** [comment]
Thanks for the report and link to relevant issue, sounds like this bug is still not resolved... I'm going to take a look into it and see what I can do.

**Comment by ChadBailey** [comment]
I have confirmed the issue, the release on the chrome store is missing the latest fix/commit.

![image](https://user-images.githubusercontent.com/15102816/187818030-c73a7981-af7a-488e-9974-ec13cb5a0493.png)

I don't think I have the ability to cut a new release, will have to wait on @igrigorik to investigate.

**Comment by igrigorik** [comment]
Thanks for the nudge. Tried to do a quick push but looks like our workflow is [broken](https://github.com/igrigorik/videospeed/runs/8200860733?check_suite_focus=true) — doh. Will need to dig into that first, to figure out what's going on there.

**Comment by igrigorik** [comment]
Sorry about the delay. v0.7.3 should be live now.
