### ISSUE TITLE
Why does it come out with a chewing sound when the audio speeds up?

### ISSUE THREAD

**Issue by grabsurprise** [igrigorik/videospeed#962]
Always when I accelerate the speed, there is a chewing of the audio. Sounds like audio compression or cut information. I can't use it to listen to accelerated music because the audio is horrible.

**Comment by pepijnmm** [comment]
this is a browser problem. videospeed just uses speed features that are already inside the browser. maybe use a different browser? or maybe your pc can't handle the speed.

**Comment by grabsurprise** [comment]
Lol. You are right. This is a browser problem. I use chrome 105, and my pc can handle max 2x. But when I listen music in youtube with acceleration of 1.15, 1.25... All have chewing of the audio. It's clear with music. Minimal chewing, but have.

**Comment by ChadBailey** [comment]
Sounds like this has been confirmed as a PC issue. Please feel free to re-open/open a new issue if you have any further problems.
