### ISSUE TITLE
v0.8.1 Beta Testers Wanted!

### ISSUE THREAD

**Issue by ChadBailey** [igrigorik/videospeed#964]
Hello,

I have completed the initial version of the all-new video speed controller code base (see #963 )! To make testing easier for everyone, I have temporarily published it to the [chrome web store](https://chrome.google.com/webstore/detail/video-speed-controller-be/kgciknbfdanakgjeeoihchpljcejkkdj?hl=en&authuser=1) but you may also elect to test manually by [cloning the github page](https://github.com/chadbailey/videospeed-refactoring).

This new version should work nearly the same as the existing one, with a few subtle differences (mostly a re-colored icon to make it obvious you have the beta version installed). Most of the changes are under the hood. The developer experience should be radically different (hopefully in a good way)

If I can get some brave souls to please try it and report back if it's working or if there are any issues I would greatly appreciate it. My plan is to get enough people to test that we can confidently say it works at least as good as the existing one, then pull in the changes to this main repository. Ideally, I'd love to continue this cycle another 3 or 4 times until we reach a respectable test bed.

Thanks!

**Comment by pepijnmm** [comment]
my first observation would be that the "options for Extention" isn't in the extension info page but only accessible through the top by right-clicking on the icon.
![image](https://user-images.githubusercontent.com/3217184/189107724-3d37a2d4-d02a-4f96-8655-1f8623d6b0d5.png)
![image](https://user-images.githubusercontent.com/3217184/189107776-ad25d471-582d-451f-91e2-3dfe59f6885d.png)

Other than that will use it for now as my default and let you know anything I notice.

in the end, I think it would be good to keep the code again on this repo as a lot more people have starred this project and have forked it. Archiving this repo and redirecting them to the new one is a bit more messy

**Comment by ChadBailey** [comment]
Appreciate you taking the time out to find these issues! I'll look into them

**Comment by ChadBailey** [comment]
Thanks so much @pepijnmm for the feedback. All issues have been fixed.

That said, you have my intentions reversed. The beta repo is only for beta testing since this will radically change the code base, I didn't want to risk all users of the extension to be negatively impacted. The intent was to wrap up beta testing, merge into _this_ repo, then archive the _beta repo_.

I think I wasn't clear enough on this, so to keep things tidy I'm going to open a new thread for v0.8.2 testing.

**Comment by WTrash** [comment]
Reddit has updated its video player, the extension no longer works, even for the non-beta version.

**Comment by ChadBailey** [comment]
Thanks for the report, I'll take a look!
