### ISSUE TITLE
Feature suggestion: skip Ad

### ISSUE THREAD

**Issue by vainamonen** [igrigorik/videospeed#967]
Please add a configuration option to skip Ads. Two actions at the same time:
- max speed (currently 16x);
- mute audio.

**Comment by magnus-ISU** [comment]
It is configurable for a reason.
Mute audio might be a feature though.

**Comment by ChadBailey** [comment]
I believe this would violate the single purpose principal. I would suggest taking a look at [sponsorblock](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone)
