### ISSUE TITLE
Controls misplaced on InfoQ

### ISSUE THREAD

**Issue by medb** [igrigorik/videospeed#97]
On InfoQ presentations controls are placed at top of the page (over the presentation title) instead of at top of the actual presentation video:
http://www.infoq.com/presentations/individual-empathy

**Comment by igrigorik** [comment]
This seems to fix it: https://github.com/igrigorik/videospeed/commit/b40b02b769ddae77795382b0e9ef7b7789c5ac7c - please give it a try.

**Comment by medb** [comment]
Just checked, works as expected
