### ISSUE TITLE
Facebook Videos

### ISSUE THREAD

**Issue by HA3IK** [igrigorik/videospeed#98]
Please, add speed controller on facebook videos.
Thanks for your work!

**Comment by igrigorik** [comment]
Hmm, it does work on their video pages (e.g. https://www.facebook.com/FacebookforDevelopers/videos/10153625387873553/), but not in stream.. Guessing, something to do with how the videos are injected.

**Comment by igrigorik** [comment]
Merging into https://github.com/igrigorik/videospeed/issues/103.
