### ISSUE TITLE
Not working on YouTube since YouTube's recent UI changes

### ISSUE THREAD

**Issue by ipince** [igrigorik/videospeed#989]
The speed control is no longer appearing on YouTube videos, and the shortcuts don't work either. I _think_ it might be related to the UI changes that YouTube has released over the past few days.

My versions:
Version 1.44.105 Chromium: 106.0.5249.91 (Official Build) (x86_64)

Extension: v0.7.3

**Comment by ian-hwang** [comment]
I'm working on youtube, but the program doesn't remember the previous speed and goes back to 1x speed.

**Comment by ipince** [comment]
Well, it seems like my extension was disabled for some reason (the extension was installed, but it was disabled in its own settings). So I'm closing this as not an issue. @ian-hwang ,I think you should file a separate issue for your problem.

**Comment by humam2104** [comment]
> I'm working on youtube, but the program doesn't remember the previous speed and goes back to 1x speed.

same thing happens with me, whenever a new video plays the player reverts to 1. Especially if it started the video using autoplay, and I was opening another software (alt tabbed)
